/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSButton.h>

@class NSMutableDictionary;

@interface _UXButton : NSButton {

	NSMutableDictionary* _titlesByState;
	NSMutableDictionary* _titleAttributesByState;

}
+ (Class)cellClass;
- (void)setTitle:(id)arg1;
- (id)accessibilityLabel;
- (BOOL)accessibilityPerformPress;
- (id)initWithFrame:(CGRect)arg1;
- (void)mouseUp:(id)arg1;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)setTitle:(id)arg1 forState:(unsigned long long)arg2;
- (void)tintColorDidChange;
- (id)_attributedStringForState:(unsigned long long)arg1;
- (id)_textColorForState:(unsigned long long)arg1;
- (void)setTitleAttributes:(id)arg1 forState:(unsigned long long)arg2;
@end

