/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXCollectionView.h"
#import "_UXCollectionViewOverdraw.h"

@class NSString;

@interface _UXCollectionView : UXCollectionView <_UXCollectionViewOverdraw>

@property (nonatomic) BOOL overdrawEnabled; 
+ (Class)documentClass;
- (BOOL)overdrawEnabled;
- (void)setOverdrawEnabled:(BOOL)arg1;
@end

