/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXView.h"

@class NSVisualEffectView, NSView;

@interface _UXContainerView : UXView {

	NSVisualEffectView* _effectView;
	BOOL _wantsMaterialBackground;
	NSView* _contentView;

}

@property (nonatomic) BOOL wantsMaterialBackground;              //@synthesize wantsMaterialBackground=_wantsMaterialBackground - In the implementation block
@property (nonatomic, strong) NSView *contentView;               //@synthesize contentView=_contentView - In the implementation block
- (void)setContentView:(id)arg1;
- (id)contentView;
- (void)wrapContentView;
- (void)setWantsMaterialBackground:(BOOL)arg1;
- (BOOL)wantsMaterialBackground;
@end

