/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <Cocoa/Cocoa.h>

@class NSIndexPath, NSString;

@interface _UXCollectionViewItemKey : NSObject <NSCopying> {

	unsigned long long _hash;
	NSIndexPath* _indexPath;
	NSString* _identifier;
	BOOL _isClone;
	unsigned long long _type;

}

@property (nonatomic, readonly) unsigned long long type;                     //@synthesize type=_type - In the implementation block
@property (nonatomic, strong, readonly) NSIndexPath *indexPath;              //@synthesize indexPath=_indexPath - In the implementation block
@property (nonatomic, strong, readonly) NSString *identifier;                //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic, readonly) BOOL isClone;                                //@synthesize isClone=_isClone - In the implementation block
+ (id)collectionItemKeyForCellWithIndexPath:(id)arg1;
+ (id)collectionItemKeyForDecorationViewOfKind:(id)arg1 andIndexPath:(id)arg2;
+ (id)collectionItemKeyForLayoutAttributes:(id)arg1;
+ (id)collectionItemKeyForSupplementaryViewOfKind:(id)arg1 andIndexPath:(id)arg2;
- (void)dealloc;
- (id)copyWithZone:(NSZone*)arg1;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)identifier;
- (void)setType:(unsigned long long)arg1;
- (unsigned long long)type;
- (void)setIdentifier:(id)arg1;
- (id)indexPath;
- (BOOL)isClone;
- (id)copyAsClone:(BOOL)arg1;
- (id)initWithType:(unsigned long long)arg1 indexPath:(id)arg2 identifier:(id)arg3;
- (id)initWithType:(unsigned long long)arg1 indexPath:(id)arg2 identifier:(id)arg3 clone:(BOOL)arg4;
- (void)setIndexPath:(id)arg1;
@end

