/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXCollectionViewLayoutProxyDelegate.h"
#import <Cocoa/Cocoa.h>
@protocol UXCollectionViewDataSource_Rearranging, UXCollectionViewDelegate_Rearranging;
@class NSArray, NSGestureRecognizer, NSEvent, UXCollectionView, UXCollectionViewCell, NSString, _UXCollectionViewLayoutProxy, UXCollectionViewLayout;

@interface _UXCollectionViewRearrangingCoordinator : NSObject <UXCollectionViewLayoutProxyDelegate, NSGestureRecognizerDelegate, NSDraggingSource, NSDraggingDestination> {

	struct {
		unsigned dataSourceImplementsCanMoveItemsAtIndexPaths : 1;
		unsigned dataSourceImplementsShouldExchangeItemsAtIndexPathsWithProposedIndexPaths : 1;
		unsigned dataSourceImplementsMoveItemsAtIndexPathsToIndexPath : 1;
		unsigned dataSourceImplementsExchangeItemsAtIndexPathsWithIndexPaths : 1;
		unsigned delegateImplementsShouldBeginDraggingSessionWithClickedItemAtIndexPath : 1;
		unsigned delegateImplementsImageForDraggedItemAtIndexPath : 1;
		unsigned delegateImplementsPasteboardWriterForItemAtIndexPath : 1;
		unsigned delegateImplementsDraggingItemForIndexPathProposedDraggingItem : 1;
		unsigned delegateImplementsUpdatesLayoutOnDrag : 1;
		unsigned delegateImplementsPreferredDraggingFormation : 1;
		unsigned delegateImplementsDragSourceIdentifier : 1;
		unsigned delegateImplementsCreatedDraggingSessionForItemsAtIndexPaths : 1;
		unsigned delegateImplementsDraggingSessionSourceOperationMaskForDraggingContext;
		unsigned delegateImplementsDraggingSessionWillBeginAtPoint : 1;
		unsigned delegateImplementsDraggingSessionMovedToPoint : 1;
		unsigned delegateImplementsDraggingSessionEndedAtPointDragOperation : 1;
		unsigned delegateImplementsPrepareForDragOperation : 1;
		unsigned delegateImplementsPerformDragOperation : 1;
		unsigned delegateImplementsDraggingEntered : 1;
		unsigned delegateImplementsDraggingUpdated : 1;
		unsigned delegateImplementsDraggingExited : 1;
		unsigned delegateImplementsDraggingEnded : 1;
	}  _collectionViewFlags;
	NSArray* _initialIndexPaths;
	NSArray* _targetIndexPaths;
	NSArray* _movedIndexPaths;
	NSArray* _exchangedIndexPaths;
	CGPoint _screenPoint;
	BOOL _initialIndexPathsAreContiguous;
	NSGestureRecognizer* _gestureRecognizer;
	double _dragStartTime;
	double _collectionViewReloadLastCallTime;
	double _dragEnteredTime;
	BOOL _updatesLayoutOnDrag;
	BOOL _autoscrolling;
	unsigned long long _sequenceNumber;
	NSEvent* _mouseDownEvent;
	BOOL _isRearranging;
	BOOL _enabled;
	BOOL _allowDragOutsideCells;
	BOOL _continuouslyUpdateInsideCells;
	BOOL _usePileForSingleItem;
	BOOL _allowAutoscroll;
	BOOL _shouldExchange;
	UXCollectionView* _collectionView;
	long long _initiationMode;
	double _rearrangingInitialDelay;
	double _rearrangingPreviewDelay;
	UXCollectionViewCell* _dropTargetCell;
	unsigned long long _dropOperation;
	NSString* _dragSourceIdentifier;
	NSRange _initialIndexRange;
	NSRange _targetIndexRange;
	NSRange _movedIndexRange;
	NSRange _exchangedIndexRange;

}

@property (nonatomic, readonly) _UXCollectionViewLayoutProxy *layoutProxy; 
@property (nonatomic, readonly) id<UXCollectionViewDataSource_Rearranging> dataSource; 
@property (nonatomic, readonly) id<UXCollectionViewDelegate_Rearranging> delegate; 
@property (nonatomic) NSRange initialIndexRange;                                                    //@synthesize initialIndexRange=_initialIndexRange - In the implementation block
@property (nonatomic) NSRange targetIndexRange;                                                     //@synthesize targetIndexRange=_targetIndexRange - In the implementation block
@property (nonatomic) NSRange movedIndexRange;                                                      //@synthesize movedIndexRange=_movedIndexRange - In the implementation block
@property (nonatomic) NSRange exchangedIndexRange;                                                  //@synthesize exchangedIndexRange=_exchangedIndexRange - In the implementation block
@property (nonatomic) BOOL shouldExchange;                                                          //@synthesize shouldExchange=_shouldExchange - In the implementation block
@property (nonatomic, strong) UXCollectionViewCell *dropTargetCell;                                 //@synthesize dropTargetCell=_dropTargetCell - In the implementation block
@property (nonatomic) unsigned long long dropOperation;                                             //@synthesize dropOperation=_dropOperation - In the implementation block
@property (nonatomic, readonly) NSString *dragSourceIdentifier;                                     //@synthesize dragSourceIdentifier=_dragSourceIdentifier - In the implementation block
@property (nonatomic, readonly) UXCollectionView *collectionView;                                   //@synthesize collectionView=_collectionView - In the implementation block
@property (nonatomic, readonly) UXCollectionViewLayout *collectionViewLayout; 
@property (nonatomic, readonly) BOOL isRearranging;                                                 //@synthesize isRearranging=_isRearranging - In the implementation block
@property (nonatomic) BOOL enabled;                                                                 //@synthesize enabled=_enabled - In the implementation block
@property (nonatomic) long long initiationMode;                                                     //@synthesize initiationMode=_initiationMode - In the implementation block
@property (nonatomic) BOOL allowDragOutsideCells;                                                   //@synthesize allowDragOutsideCells=_allowDragOutsideCells - In the implementation block
@property (nonatomic) BOOL continuouslyUpdateInsideCells;                                           //@synthesize continuouslyUpdateInsideCells=_continuouslyUpdateInsideCells - In the implementation block
@property (nonatomic) BOOL usePileForSingleItem;                                                    //@synthesize usePileForSingleItem=_usePileForSingleItem - In the implementation block
@property (nonatomic) BOOL allowAutoscroll;                                                         //@synthesize allowAutoscroll=_allowAutoscroll - In the implementation block
@property (nonatomic) double rearrangingInitialDelay;                                               //@synthesize rearrangingInitialDelay=_rearrangingInitialDelay - In the implementation block
@property (nonatomic) double rearrangingPreviewDelay;                                               //@synthesize rearrangingPreviewDelay=_rearrangingPreviewDelay - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy, readonly) NSString *description; 
@property (copy, readonly) NSString *debugDescription; 
- (void)dealloc;
- (BOOL)enabled;
- (id<UXCollectionViewDelegate_Rearranging>)delegate;
- (void)setEnabled:(BOOL)arg1;
- (void)draggingExited:(id)arg1;
- (id)collectionView;
- (id)collectionViewLayout;
- (void)concludeDragOperation:(id)arg1;
- (id<UXCollectionViewDataSource_Rearranging>)dataSource;
- (void)draggingEnded:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)draggingSession:(id)arg1 endedAtPoint:(CGPoint)arg2 operation:(unsigned long long)arg3;
- (void)draggingSession:(id)arg1 movedToPoint:(CGPoint)arg2;
- (unsigned long long)draggingSession:(id)arg1 sourceOperationMaskForDraggingContext:(long long)arg2;
- (void)draggingSession:(id)arg1 willBeginAtPoint:(CGPoint)arg2;
- (unsigned long long)draggingUpdated:(id)arg1;
- (unsigned long long)dropOperation;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (id)initWithCollectionView:(id)arg1;
- (id)layoutAttributesForElementsInRect:(CGRect)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (void)setDropOperation:(unsigned long long)arg1;
- (void)updateDraggingItemsForDrag:(id)arg1;
- (BOOL)wantsPeriodicDraggingUpdates;
- (void)createGestureRecognizer;
- (void)removeGestureRecognizer;
- (void)reloadLayout;
- (NSRange)movedIndexRange;
- (BOOL)allowAutoscroll;
- (BOOL)_allowAutoscrollForDraggingInfo:(id)arg1;
- (BOOL)_allowRearranging;
- (void)_autoscrollWithWindowLocation:(CGPoint)arg1;
- (void)_beginDraggingSessionForIndexPaths:(id)arg1;
- (void)_beginRearrangingItemsWithIndexPaths:(id)arg1;
- (void)_createdDraggingSession:(id)arg1 forItemsAtIndexPaths:(id)arg2;
- (void)_finishRearrangingForLocation:(CGPoint)arg1 shouldComplete:(BOOL)arg2;
- (void)_gestureRecognized:(id)arg1;
- (id)_imageForItemAtIndexPath:(id)arg1;
- (BOOL)_isEquivalentSourceOfDraggingInfo:(id)arg1;
- (BOOL)_isSourceOfDraggingInfo:(id)arg1;
- (void)_moveItemsAtIndexPaths:(id)arg1 toIndexPaths:(id)arg2;
- (void)_reloadCollectionViewWithAnimation;
- (BOOL)_shouldHandleExternalDrop:(id)arg1;
- (void)_updateDragSourceIdentifier;
- (void)_updateRearrangingStateForLocation:(id)arg1;
- (BOOL)allowDragOutsideCells;
- (BOOL)continuouslyUpdateInsideCells;
- (id)dragSourceIdentifier;
- (id)dropTargetCell;
- (NSRange)exchangedIndexRange;
- (NSRange)initialIndexRange;
- (long long)initiationMode;
- (BOOL)isRearranging;
- (id)layoutProxy;
- (double)rearrangingInitialDelay;
- (double)rearrangingPreviewDelay;
- (void)setAllowAutoscroll:(BOOL)arg1;
- (void)setAllowDragOutsideCells:(BOOL)arg1;
- (void)setContinuouslyUpdateInsideCells:(BOOL)arg1;
- (void)setDropTargetCell:(id)arg1;
- (void)setExchangedIndexRange:(NSRange)arg1;
- (void)setInitialIndexRange:(NSRange)arg1;
- (void)setInitiationMode:(long long)arg1;
- (void)setMovedIndexRange:(NSRange)arg1;
- (void)setRearrangingInitialDelay:(double)arg1;
- (void)setRearrangingPreviewDelay:(double)arg1;
- (void)setShouldExchange:(BOOL)arg1;
- (void)setTargetIndexRange:(NSRange)arg1;
- (void)setUsePileForSingleItem:(BOOL)arg1;
- (BOOL)shouldExchange;
- (NSRange)targetIndexRange;
- (BOOL)usePileForSingleItem;
@end

