/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXView.h"

@class NSString, NSAttributedString, NSButton, UXView, NSTextField, NSMutableArray, NSProgressIndicator, NSDictionary;

@interface _UXContentUnavailableView : UXView {

	BOOL _showProgress;
	NSString* _title;
	NSString* _message;
	NSAttributedString* _attributedMessage;
	NSString* _buttonTitle;
	NSButton* _actionButton;
	/*^block*/id _buttonAction;
	unsigned long long _progressIndicatorStyle;
	UXView* _containerView;
	NSTextField* _titleLabel;
	NSTextField* _messageLabel;
	NSMutableArray* _containerViewContraints;
	NSProgressIndicator* _progressIndicator;
	unsigned long long _vibrantOptions;

}

@property (nonatomic, strong) UXView *containerView;                                //@synthesize containerView=_containerView - In the implementation block
@property (nonatomic, strong) NSTextField *titleLabel;                              //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic, strong) NSTextField *messageLabel;                            //@synthesize messageLabel=_messageLabel - In the implementation block
@property (nonatomic, strong) NSMutableArray *containerViewContraints;              //@synthesize containerViewContraints=_containerViewContraints - In the implementation block
@property (nonatomic, strong) NSProgressIndicator *progressIndicator;               //@synthesize progressIndicator=_progressIndicator - In the implementation block
@property (nonatomic) unsigned long long vibrantOptions;                            //@synthesize vibrantOptions=_vibrantOptions - In the implementation block
@property (nonatomic, copy) NSString *title;                                        //@synthesize title=_title - In the implementation block
@property (nonatomic, copy) NSString *message;                                      //@synthesize message=_message - In the implementation block
@property (nonatomic, copy) NSAttributedString *attributedMessage;                  //@synthesize attributedMessage=_attributedMessage - In the implementation block
@property (nonatomic, readonly) NSDictionary *messageTextAttributes; 
@property (nonatomic, copy) NSString *buttonTitle;                                  //@synthesize buttonTitle=_buttonTitle - In the implementation block
@property (nonatomic, readonly) NSButton *actionButton;                             //@synthesize actionButton=_actionButton - In the implementation block
@property (nonatomic, copy) id buttonAction;                                        //@synthesize buttonAction=_buttonAction - In the implementation block
@property (nonatomic) BOOL showProgress;                                            //@synthesize showProgress=_showProgress - In the implementation block
@property (nonatomic) unsigned long long progressIndicatorStyle;                    //@synthesize progressIndicatorStyle=_progressIndicatorStyle - In the implementation block
- (id)initWithCoder:(id)arg1;
- (id)message;
- (void)setMessage:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)layout;
- (id)title;
- (void)setButtonTitle:(id)arg1;
- (void)_commonInit;
- (id)_textColor;
- (id)_tintColor;
- (id)buttonTitle;
- (id)containerView;
- (id)initWithFrame:(CGRect)arg1;
- (id)progressIndicator;
- (void)setContainerView:(id)arg1;
- (void)setProgressIndicator:(id)arg1;
- (void)updateConstraints;
- (id)buttonAction;
- (void)setButtonAction:(id)arg1;
- (id)titleLabel;
- (id)actionButton;
- (id)messageLabel;
- (void)setTitleLabel:(id)arg1;
- (void)setAttributedMessage:(id)arg1;
- (void)setShowProgress:(BOOL)arg1;
- (BOOL)showProgress;
- (void)setMessageLabel:(id)arg1;
- (BOOL)_hasVibrantText;
- (void)_actionButtonPressed:(id)arg1;
- (double)_buttonAlpha;
- (BOOL)_hasVibrantButton;
- (double)_labelAlpha;
- (id)_vibrantBaseColor;
- (id)attributedMessage;
- (unsigned long long)progressIndicatorStyle;
- (void)setProgressIndicatorStyle:(unsigned long long)arg1;
- (void)setVibrantOptions:(unsigned long long)arg1;
- (id)titleTextAttributes;
- (unsigned long long)vibrantOptions;
- (id)_textFieldWithFontSize:(double)arg1;
- (void)_updateProgressLayout;
- (void)_updateTextField:(id)arg1 withAttributedText:(id)arg2;
- (id)containerViewContraints;
- (id)messageTextAttributes;
- (void)setContainerViewContraints:(id)arg1;
@end

