/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


#import "UXKit-Structs.h"
@class NSMutableArray, NSDictionary;

@interface _UXFlowLayoutInfo : NSObject {

	NSMutableArray* _sections;
	BOOL _useFloatingHeaderFooter;
	BOOL _horizontal;
	BOOL _leftToRight;
	CGRect _visibleBounds;
	CGSize _layoutSize;
	double _dimension;
	BOOL _isValid;
	NSDictionary* _rowAlignmentOptions;
	BOOL _usesFloatingHeaderFooter;
	CGSize _contentSize;

}

@property (nonatomic, readonly) NSMutableArray *sections;                     //@synthesize sections=_sections - In the implementation block
@property (nonatomic) BOOL usesFloatingHeaderFooter;                          //@synthesize usesFloatingHeaderFooter=_usesFloatingHeaderFooter - In the implementation block
@property (nonatomic) double dimension;                                       //@synthesize dimension=_dimension - In the implementation block
@property (nonatomic) BOOL horizontal;                                        //@synthesize horizontal=_horizontal - In the implementation block
@property (nonatomic) BOOL leftToRight;                                       //@synthesize leftToRight=_leftToRight - In the implementation block
@property (nonatomic) CGSize contentSize;                                     //@synthesize contentSize=_contentSize - In the implementation block
@property (nonatomic, strong) NSDictionary *rowAlignmentOptions;              //@synthesize rowAlignmentOptions=_rowAlignmentOptions - In the implementation block
- (void)dealloc;
- (id)copy;
- (id)init;
- (double)dimension;
- (void)setContentSize:(CGSize)arg1;
- (void)setLeftToRight:(BOOL)arg1;
- (id)addSection;
- (CGSize)contentSize;
- (CGRect)frameForItemAtIndexPath:(id)arg1;
- (BOOL)horizontal;
- (void)invalidate:(BOOL)arg1;
- (BOOL)leftToRight;
- (id)rowAlignmentOptions;
- (id)sections;
- (void)setDimension:(double)arg1;
- (void)setHorizontal:(BOOL)arg1;
- (void)setRowAlignmentOptions:(id)arg1;
- (void)setUsesFloatingHeaderFooter:(BOOL)arg1;
- (id)snapshot;
- (BOOL)usesFloatingHeaderFooter;
@end

