/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


#import "UXKit-Structs.h"
@class NSMutableArray, _UXFlowLayoutSection;

@interface _UXFlowLayoutRow : NSObject {

	NSMutableArray* _items;
	CGSize _rowSize;
	CGRect _rowFrame;
	long long _index;
	BOOL _isValid;
	BOOL _complete;
	long long _verticalAlignement;
	long long _horizontalAlignement;
	BOOL _fixedItemSize;
	_UXFlowLayoutSection* _section;

}

@property (nonatomic) _UXFlowLayoutSection *section;                //@synthesize section=_section - In the implementation block
@property (nonatomic) CGSize rowSize;                               //@synthesize rowSize=_rowSize - In the implementation block
@property (nonatomic) CGRect rowFrame;                              //@synthesize rowFrame=_rowFrame - In the implementation block
@property (nonatomic) long long index;                              //@synthesize index=_index - In the implementation block
@property (nonatomic, readonly) NSMutableArray *items;              //@synthesize items=_items - In the implementation block
@property (nonatomic) BOOL complete;                                //@synthesize complete=_complete - In the implementation block
@property (nonatomic) BOOL fixedItemSize;                           //@synthesize fixedItemSize=_fixedItemSize - In the implementation block
- (void)dealloc;
- (id)init;
- (void)invalidate;
- (void)addItem:(id)arg1;
- (long long)index;
- (void)setIndex:(long long)arg1;
- (CGSize)rowSize;
- (id)section;
- (BOOL)complete;
- (id)copyFromSection:(id)arg1;
- (BOOL)fixedItemSize;
- (id)items;
- (void)layoutRow;
- (CGRect)rowFrame;
- (void)setComplete:(BOOL)arg1;
- (void)setFixedItemSize:(BOOL)arg1;
- (void)setRowFrame:(CGRect)arg1;
- (void)setRowSize:(CGSize)arg1;
- (void)setSection:(id)arg1;
- (id)snapshot;
@end

