/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


#import "UXKit-Structs.h"
@class _UXFlowLayoutSection, _UXFlowLayoutRow;

@interface _UXFlowLayoutItem : NSObject {

	CGRect _itemFrame;
	_UXFlowLayoutSection* _section;
	_UXFlowLayoutRow* _rowObject;

}

@property (nonatomic) _UXFlowLayoutSection *section;              //@synthesize section=_section - In the implementation block
@property (nonatomic) _UXFlowLayoutRow *rowObject;                //@synthesize rowObject=_rowObject - In the implementation block
@property (nonatomic) CGRect itemFrame;                           //@synthesize itemFrame=_itemFrame - In the implementation block
- (id)copy;
- (id)section;
- (CGRect)itemFrame;
- (id)rowObject;
- (void)setItemFrame:(CGRect)arg1;
- (void)setRowObject:(id)arg1;
- (void)setSection:(id)arg1;
@end

