/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import <AppKit/NSLayoutGuide.h>
#import "UXLayoutSupport.h"

@class NSLayoutYAxisAnchor, NSLayoutDimension, NSLayoutConstraint, NSString;

@interface _UXLayoutSpacer : NSLayoutGuide <UXLayoutSupport> {
    @public
	NSLayoutConstraint* _counterDimensionConstraint;
	NSLayoutConstraint* _dimensionConstraint;
	BOOL _horizontal;
	/*^block*/id _lengthUpdateBlock;

}

@property (nonatomic) double length; 
@property (nonatomic) BOOL horizontal;                               //@synthesize horizontal=_horizontal - In the implementation block
@property (nonatomic, copy) id lengthUpdateBlock;                    //@synthesize lengthUpdateBlock=_lengthUpdateBlock - In the implementation block
@property (readonly) NSLayoutYAxisAnchor *topAnchor; 
@property (readonly) NSLayoutYAxisAnchor *bottomAnchor; 
@property (readonly) NSLayoutDimension *heightAnchor; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy, readonly) NSString *description; 
@property (copy, readonly) NSString *debugDescription; 
+ (id)_horizontalLayoutSpacer;
+ (id)_verticalLayoutSpacer;
- (id)description;
- (double)length;
- (void)_activate;
- (void)setLength:(double)arg1;
- (BOOL)horizontal;
- (void)setHorizontal:(BOOL)arg1;
- (void)_setUpCounterDimensionConstraint;
- (void)_setUpDimensionConstraintWithLength:(double)arg1;
- (id)lengthUpdateBlock;
- (void)setLengthUpdateBlock:(id)arg1;
@end

