/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXNavigationDestination.h"

@class NSString, UXDestinationAuxiliaryStore, NSSet;

@interface _UXNavigationDestination : NSObject <UXNavigationDestination> {

	NSString* _destinationIdentifier;
	NSString* _destinationTitle;
	UXDestinationAuxiliaryStore* _destinationAuxiliaryStore;
	NSSet* _requiredDestinationAuxiliaryKeys;

}

@property (nonatomic, strong) NSString *destinationIdentifier;                                     //@synthesize destinationIdentifier=_destinationIdentifier - In the implementation block
@property (nonatomic, strong) NSString *destinationTitle;                                          //@synthesize destinationTitle=_destinationTitle - In the implementation block
@property (nonatomic, strong) UXDestinationAuxiliaryStore *destinationAuxiliaryStore;              //@synthesize destinationAuxiliaryStore=_destinationAuxiliaryStore - In the implementation block
@property (nonatomic, strong) NSSet *requiredDestinationAuxiliaryKeys;                             //@synthesize requiredDestinationAuxiliaryKeys=_requiredDestinationAuxiliaryKeys - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy, readonly) NSString *description; 
@property (copy, readonly) NSString *debugDescription; 
+ (BOOL)supportsSecureCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)destinationIdentifier;
- (void)setDestinationIdentifier:(id)arg1;
- (id)destinationAuxiliaryStore;
- (id)destinationTitle;
- (id)requiredDestinationAuxiliaryKeys;
- (void)setDestinationAuxiliaryStore:(id)arg1;
- (void)setDestinationTitle:(id)arg1;
- (void)setRequiredDestinationAuxiliaryKeys:(id)arg1;
@end

