/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXView.h"
#import "_UXBarItemsContainer.h"

@class UXNavigationItem, UXNavigationBar, NSView, NSMutableArray, NSMutableDictionary, NSLayoutConstraint, NSString;

@interface _UXNavigationItemContainerView : UXView <_UXBarItemsContainer> {

	BOOL _hidesGlobalTrailingView;
	UXNavigationItem* _item;
	UXNavigationBar* _navigationBar;
	unsigned long long _state;
	double _minimumWidthForExpandedTitle;
	double _minimumWidthForExpandedItems;
	NSView* _leftView;
	NSMutableArray* _leftItemViews;
	NSView* _titleView;
	NSMutableArray* _rightItemViews;
	NSView* _rightView;
	NSMutableArray* _itemsSortedByPriority;
	NSMutableDictionary* _overflowItemsByMinimumWidth;
	NSMutableArray* _addedConstraints;
	NSLayoutConstraint* _titleCenteringConstraint;
	NSView* _titleCenteringConstrainedTitleView;
	NSView* _titleCenteringTrackedView;
	NSView* _titleCenteringConstraintOwnerView;

}

@property (nonatomic, readonly) UXNavigationItem *item;                                      //@synthesize item=_item - In the implementation block
@property (nonatomic, weak, readonly) UXNavigationBar *navigationBar;                        //@synthesize navigationBar=_navigationBar - In the implementation block
@property (nonatomic) unsigned long long state;                                              //@synthesize state=_state - In the implementation block
@property (nonatomic) double minimumWidthForExpandedTitle;                                   //@synthesize minimumWidthForExpandedTitle=_minimumWidthForExpandedTitle - In the implementation block
@property (nonatomic) double minimumWidthForExpandedItems;                                   //@synthesize minimumWidthForExpandedItems=_minimumWidthForExpandedItems - In the implementation block
@property (nonatomic, strong) NSView *leftView;                                              //@synthesize leftView=_leftView - In the implementation block
@property (nonatomic, strong) NSMutableArray *leftItemViews;                                 //@synthesize leftItemViews=_leftItemViews - In the implementation block
@property (nonatomic, strong) NSView *titleView;                                             //@synthesize titleView=_titleView - In the implementation block
@property (nonatomic, strong) NSMutableArray *rightItemViews;                                //@synthesize rightItemViews=_rightItemViews - In the implementation block
@property (nonatomic, strong) NSView *rightView;                                             //@synthesize rightView=_rightView - In the implementation block
@property (nonatomic, strong) NSMutableArray *itemsSortedByPriority;                         //@synthesize itemsSortedByPriority=_itemsSortedByPriority - In the implementation block
@property (nonatomic, strong) NSMutableDictionary *overflowItemsByMinimumWidth;              //@synthesize overflowItemsByMinimumWidth=_overflowItemsByMinimumWidth - In the implementation block
@property (nonatomic, strong) NSMutableArray *addedConstraints;                              //@synthesize addedConstraints=_addedConstraints - In the implementation block
@property (nonatomic, strong) NSLayoutConstraint *titleCenteringConstraint;                  //@synthesize titleCenteringConstraint=_titleCenteringConstraint - In the implementation block
@property (nonatomic, weak) NSView *titleCenteringConstrainedTitleView;                      //@synthesize titleCenteringConstrainedTitleView=_titleCenteringConstrainedTitleView - In the implementation block
@property (nonatomic, weak) NSView *titleCenteringTrackedView;                               //@synthesize titleCenteringTrackedView=_titleCenteringTrackedView - In the implementation block
@property (nonatomic, weak) NSView *titleCenteringConstraintOwnerView;                       //@synthesize titleCenteringConstraintOwnerView=_titleCenteringConstraintOwnerView - In the implementation block
@property (nonatomic, readonly) BOOL hidesGlobalTrailingView;                                //@synthesize hidesGlobalTrailingView=_hidesGlobalTrailingView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy, readonly) NSString *description; 
@property (copy, readonly) NSString *debugDescription; 
+ (id)layoutContainerForItem:(id)arg1 navigationBar:(id)arg2;
- (void)dealloc;
- (id)init;
- (unsigned long long)state;
- (void)setState:(unsigned long long)arg1;
- (void)layout;
- (id)item;
- (id)hitTest:(CGPoint)arg1;
- (void)updateConstraints;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (id)leftView;
- (id)rightView;
- (void)setLeftView:(id)arg1;
- (void)setRightView:(id)arg1;
- (void)setTitleView:(id)arg1;
- (id)titleView;
- (id)navigationBar;
- (void)_updateTitleView;
- (void)prepareForTransition;
- (void)setOverflowItemsByMinimumWidth:(id)arg1;
- (void)_updateItemsViews:(id)arg1 withNewViews:(id)arg2;
- (void)_updateItemViews;
- (void)_updateItemsSortedByPriority;
- (void)_updateStateForWindow:(id)arg1;
- (id)addedConstraints;
- (void)cancelTransistion;
- (BOOL)hidesGlobalTrailingView;
- (id)itemsSortedByPriority;
- (id)leftItemViews;
- (double)minimumWidthForExpandedItems;
- (double)minimumWidthForExpandedTitle;
- (id)overflowItemsByMinimumWidth;
- (id)rightItemViews;
- (void)setAddedConstraints:(id)arg1;
- (void)setItemsSortedByPriority:(id)arg1;
- (void)setLeftItemViews:(id)arg1;
- (void)setMinimumWidthForExpandedItems:(double)arg1;
- (void)setMinimumWidthForExpandedTitle:(double)arg1;
- (void)setRightItemViews:(id)arg1;
- (void)setTitleCenteringConstrainedTitleView:(id)arg1;
- (void)setTitleCenteringConstraint:(id)arg1;
- (void)setTitleCenteringConstraintOwnerView:(id)arg1;
- (void)setTitleCenteringTrackedView:(id)arg1;
- (void)setTitleCenteringTrackedView:(id)arg1 updateConstraints:(BOOL)arg2;
- (id)subviewsIntersectedWithViews:(id)arg1 excludingHidden:(BOOL)arg2;
- (id)titleCenteringConstrainedTitleView;
- (id)titleCenteringConstraint;
- (id)titleCenteringConstraintOwnerView;
- (id)titleCenteringTrackedView;
- (void)updateLeftItemViewsAnimated:(BOOL)arg1;
- (void)updateRightItemViewsAnimated:(BOOL)arg1;
@end

