/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSView.h>

@protocol _UXSourceSplitViewCursorProvider;
@class NSView;

@interface _UXSourceSplitViewFullScreenOverlayContentView : NSView {

	NSView* _dividerView;
	id<_UXSourceSplitViewCursorProvider> _cursorProvider;

}

@property (nonatomic, weak) NSView *dividerView;                                              //@synthesize dividerView=_dividerView - In the implementation block
@property (nonatomic, weak) id<_UXSourceSplitViewCursorProvider> cursorProvider;              //@synthesize cursorProvider=_cursorProvider - In the implementation block
- (id)description;
- (id)hitTest:(CGPoint)arg1;
- (void)resetCursorRects;
- (void)setDividerView:(id)arg1;
- (id)dividerView;
- (id<_UXSourceSplitViewCursorProvider>)cursorProvider;
- (void)setCursorProvider:(id<_UXSourceSplitViewCursorProvider>)arg1;
@end

