/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "_UXContainerView.h"
#import "NSSplitViewItemSeparatorTrackingAdapter.h"

@interface _UXSourceSplitItemView : _UXContainerView <NSSplitViewItemSeparatorTrackingAdapter> {

	BOOL _isRegisteredWithTitlebar;
	double _dividerPosition;

}

@property (nonatomic) BOOL isRegisteredWithTitlebar;                //@synthesize isRegisteredWithTitlebar=_isRegisteredWithTitlebar - In the implementation block
@property (nonatomic) double dividerPosition;                       //@synthesize dividerPosition=_dividerPosition - In the implementation block
@property (readonly) CGRect splitFrame; 
@property (readonly) long long titlebarSeparatorStyle; 
@property (readonly) BOOL isSidebar; 
@property (readonly) BOOL isTrailingSidebar; 
- (double)dividerPosition;
- (BOOL)isRegisteredWithTitlebar;
- (BOOL)isSidebar;
- (BOOL)isTrailingSidebar;
- (void)setDividerPosition:(double)arg1;
- (void)setIsRegisteredWithTitlebar:(BOOL)arg1;
- (CGRect)splitFrame;
- (long long)titlebarSeparatorStyle;
@end

