/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSView.h>

@interface _UXSourceSplitViewShadowView : NSView {

	double _shadowRevealAmount;
	unsigned long long _shadowEdge;

}

@property (nonatomic) double shadowRevealAmount;                  //@synthesize shadowRevealAmount=_shadowRevealAmount - In the implementation block
@property (nonatomic) unsigned long long shadowEdge;              //@synthesize shadowEdge=_shadowEdge - In the implementation block
- (void)setFrameOrigin:(CGPoint)arg1;
- (id)hitTest:(CGPoint)arg1;
- (CGSize)intrinsicContentSize;
- (void)setShadowEdge:(unsigned long long)arg1;
- (void)setShadowRevealAmount:(double)arg1;
- (unsigned long long)shadowEdge;
- (double)shadowRevealAmount;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (id)makeShadowImage;
@end

