/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXCollectionReusableView.h"

@class UXView, UXLabel, NSBox;

@interface _UXTableHeaderView : UXCollectionReusableView {

	BOOL _floating;
	UXView* _contentView;
	UXLabel* _titleLabel;
	NSBox* _separator;

}

@property (getter=isFloating, nonatomic) BOOL floating;              //@synthesize floating=_floating - In the implementation block
@property (nonatomic, readonly) UXView *contentView;                 //@synthesize contentView=_contentView - In the implementation block
@property (nonatomic, readonly) UXLabel *titleLabel;                 //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic, readonly) NSBox *separator;                    //@synthesize separator=_separator - In the implementation block
- (void)prepareForReuse;
- (id)contentView;
- (id)initWithFrame:(CGRect)arg1;
- (BOOL)isFloating;
- (void)mouseDown:(id)arg1;
- (void)setFloating:(BOOL)arg1;
- (id)separator;
- (id)titleLabel;
@end

