/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "_UXViewControllerTransitionContext.h"

@class UXViewController, UXView;

@interface _UXViewControllerOneToOneTransitionContext : _UXViewControllerTransitionContext {

	/*^block*/id arbitraryTransitionCompletionHandler;
	UXViewController* _fromViewController;
	UXViewController* _toViewController;
	CGRect _fromStartFrame;
	CGRect _fromEndFrame;
	CGRect _toEndFrame;
	CGRect _toStartFrame;

}

@property (nonatomic, strong) UXViewController *fromViewController;              //@synthesize fromViewController=_fromViewController - In the implementation block
@property (nonatomic, strong) UXViewController *toViewController;                //@synthesize toViewController=_toViewController - In the implementation block
@property (nonatomic, readonly) UXView *toView; 
@property (nonatomic, readonly) UXView *fromView; 
@property (nonatomic) CGRect fromStartFrame;                                     //@synthesize fromStartFrame=_fromStartFrame - In the implementation block
@property (nonatomic) CGRect fromEndFrame;                                       //@synthesize fromEndFrame=_fromEndFrame - In the implementation block
@property (nonatomic) CGRect toEndFrame;                                         //@synthesize toEndFrame=_toEndFrame - In the implementation block
@property (nonatomic) CGRect toStartFrame;                                       //@synthesize toStartFrame=_toStartFrame - In the implementation block
- (id)fromViewController;
- (void)setFromViewController:(id)arg1;
- (void)setToViewController:(id)arg1;
- (id)toViewController;
- (CGRect)finalFrameForViewController:(id)arg1;
- (CGRect)fromEndFrame;
- (CGRect)fromStartFrame;
- (id)fromView;
- (CGRect)initialFrameForViewController:(id)arg1;
- (CGRect)toEndFrame;
- (CGRect)toStartFrame;
- (id)toView;
- (id)viewControllerForKey:(id)arg1;
- (/*^block*/id)arbitraryTransitionCompletionHandler;
- (void)setArbitraryTransitionCompletionHandler:(/*^block*/id)arg1;
- (void)setFromEndFrame:(CGRect)arg1;
- (void)setFromStartFrame:(CGRect)arg1;
- (void)setToEndFrame:(CGRect)arg1;
- (void)setToStartFrame:(CGRect)arg1;
@end

