/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@interface _UXWindowState : NSObject {

	unsigned long long _styleMask;
	unsigned long long _collectionBehavior;

}

@property (readonly) unsigned long long styleMask;                       //@synthesize styleMask=_styleMask - In the implementation block
@property (readonly) unsigned long long collectionBehavior;              //@synthesize collectionBehavior=_collectionBehavior - In the implementation block
+ (id)windowStateWithStyleMask:(unsigned long long)arg1 collectionBehavior:(unsigned long long)arg2;
- (unsigned long long)collectionBehavior;
- (unsigned long long)styleMask;
- (void)applyToWindow:(id)arg1;
@end

