/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSWindow.h>
@protocol _UXWindowDelegate;
@interface _UXWindow : NSWindow

@property (weak) id<_UXWindowDelegate> delegate; 
- (void)dealloc;
- (id)_getActiveUndoManager;
- (void)beginCriticalSheet:(id)arg1 completionHandler:(/*^block*/id)arg2;
- (void)beginSheet:(id)arg1 completionHandler:(/*^block*/id)arg2;
- (void)cancelOperation:(id)arg1;
- (id)initWithContentRect:(CGRect)arg1;
- (BOOL)makeFirstResponder:(id)arg1;
- (void)recalculateKeyViewLoop;
- (void)tintColorDidChange;
@end

