/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@protocol NSDraggingSource <NSObject>
@optional
-(void)draggingSession:(id)arg1 endedAtPoint:(CGPoint)arg2 operation:(unsigned long long)arg3;
-(void)draggingSession:(id)arg1 movedToPoint:(CGPoint)arg2;
-(void)draggingSession:(id)arg1 willBeginAtPoint:(CGPoint)arg2;
-(BOOL)ignoreModifierKeysForDraggingSession:(id)arg1;

@required
-(unsigned long long)draggingSession:(id)arg1 sourceOperationMaskForDraggingContext:(long long)arg2;

@end

