/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@protocol NSDraggingDestination <NSObject>
@optional
-(void)draggingExited:(id)arg1;
-(void)concludeDragOperation:(id)arg1;
-(void)draggingEnded:(id)arg1;
-(unsigned long long)draggingEntered:(id)arg1;
-(unsigned long long)draggingUpdated:(id)arg1;
-(BOOL)performDragOperation:(id)arg1;
-(BOOL)prepareForDragOperation:(id)arg1;
-(void)updateDraggingItemsForDrag:(id)arg1;
-(BOOL)wantsPeriodicDraggingUpdates;

@end

