/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@protocol NSMenuDelegate <NSObject>
@optional
-(CGRect*)confinementRectForMenu:(id)arg1 onScreen:(id)arg2;
-(BOOL)menu:(id)arg1 updateItem:(id)arg2 atIndex:(long long)arg3 shouldCancel:(BOOL)arg4;
-(void)menu:(id)arg1 willHighlightItem:(id)arg2;
-(void)menuDidClose:(id)arg1;
-(BOOL)menuHasKeyEquivalent:(id)arg1 forEvent:(id)arg2 target:(id*)arg3 action:(SEL*)arg4;
-(void)menuNeedsUpdate:(id)arg1;
-(void)menuWillOpen:(id)arg1;
-(long long)numberOfItemsInMenu:(id)arg1;

@end

