/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@protocol NSPopoverDelegate <NSObject>
@optional
-(void)popoverDidShow:(id)arg1;
-(id)detachableWindowForPopover:(id)arg1;
-(void)popoverDidClose:(id)arg1;
-(void)popoverDidDetach:(id)arg1;
-(BOOL)popoverShouldClose:(id)arg1;
-(BOOL)popoverShouldDetach:(id)arg1;
-(void)popoverWillClose:(id)arg1;
-(void)popoverWillShow:(id)arg1;

@end

