/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

@class NSObject;


@protocol NSSidebarTrackingAdapter <NSObject>
@property (readonly) double sidebarDividerPosition; 
@property (readonly) long long depthOfView; 
@property (readonly) NSObject *representedView; 
@property (readonly) BOOL isValidConfiguration; 
@property (readonly) double minimumDividerPosition; 
@property (readonly) double maximumDividerPosition; 
@property (readonly) BOOL isCollapsed; 
@property (getter=isOverlaidAsSidebar, readonly) BOOL overlaidAsSidebar; 
@property (readonly) double dividerWidth; 
@property (readonly) CGRect dividerCursorRect; 
@property  NSEdgeInsets sidebarAdditionalSafeAreaInsets; 
@optional
-(NSEdgeInsets*)sidebarAdditionalSafeAreaInsets;
-(CGRect)dividerCursorRect;
-(double)dividerWidth;
-(BOOL)isCollapsed;
-(BOOL)isOverlaidAsSidebar;
-(BOOL)isValidConfiguration;
-(double)maximumDividerPosition;
-(double)minimumDividerPosition;
-(void)setDividerPosition:(double)arg1;
-(void)setSidebarAdditionalSafeAreaInsets:(NSEdgeInsets)arg1;
-(void)toggleSidebar:(id)arg1;

@required
-(id)representedView;
-(long long)depthOfView;
-(double)sidebarDividerPosition;

@end

