/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@protocol NSSplitViewItemSeparatorTrackingAdapter
@property (readonly) CGRect splitFrame; 
@property (readonly) long long titlebarSeparatorStyle; 
@property (readonly) BOOL isSidebar; 
@property (readonly) BOOL isTrailingSidebar; 
@optional
-(BOOL)isTrailingSidebar;

@required
-(BOOL)isSidebar;
-(CGRect)splitFrame;
-(long long)titlebarSeparatorStyle;

@end

