/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@protocol NSWindowDelegate <NSObject>
@optional
-(void)windowDidFailToEnterFullScreen:(id)arg1;
-(void)windowWillMove:(id)arg1;
-(id)customWindowsToEnterFullScreenForWindow:(id)arg1;
-(id)customWindowsToEnterFullScreenForWindow:(id)arg1 onScreen:(id)arg2;
-(id)customWindowsToExitFullScreenForWindow:(id)arg1;
-(id)previewRepresentableActivityItemsForWindow:(id)arg1;
-(void)window:(id)arg1 didDecodeRestorableState:(id)arg2;
-(BOOL)window:(id)arg1 shouldDragDocumentWithEvent:(id)arg2 from:(CGPoint)arg3 withPasteboard:(id)arg4;
-(BOOL)window:(id)arg1 shouldPopUpDocumentPathMenu:(id)arg2;
-(void)window:(id)arg1 startCustomAnimationToEnterFullScreenOnScreen:(id)arg2 withDuration:(double)arg3;
-(void)window:(id)arg1 startCustomAnimationToEnterFullScreenWithDuration:(double)arg2;
-(void)window:(id)arg1 startCustomAnimationToExitFullScreenWithDuration:(double)arg2;
-(void)window:(id)arg1 willEncodeRestorableState:(id)arg2;
-(CGRect*)window:(id)arg1 willPositionSheet:(id)arg2 usingRect:(CGRect)arg3;
-(CGSize*)window:(id)arg1 willResizeForVersionBrowserWithMaxPreferredSize:(CGSize)arg2 maxAllowedSize:(CGSize)arg3;
-(CGSize*)window:(id)arg1 willUseFullScreenContentSize:(CGSize)arg2;
-(unsigned long long)window:(id)arg1 willUseFullScreenPresentationOptions:(unsigned long long)arg2;
-(void)windowDidBecomeKey:(id)arg1;
-(void)windowDidBecomeMain:(id)arg1;
-(void)windowDidChangeBackingProperties:(id)arg1;
-(void)windowDidChangeOcclusionState:(id)arg1;
-(void)windowDidChangeScreen:(id)arg1;
-(void)windowDidChangeScreenProfile:(id)arg1;
-(void)windowDidDeminiaturize:(id)arg1;
-(void)windowDidEndLiveResize:(id)arg1;
-(void)windowDidEndSheet:(id)arg1;
-(void)windowDidEnterFullScreen:(id)arg1;
-(void)windowDidEnterVersionBrowser:(id)arg1;
-(void)windowDidExitFullScreen:(id)arg1;
-(void)windowDidExitVersionBrowser:(id)arg1;
-(void)windowDidExpose:(id)arg1;
-(void)windowDidFailToExitFullScreen:(id)arg1;
-(void)windowDidMiniaturize:(id)arg1;
-(void)windowDidMove:(id)arg1;
-(void)windowDidResignKey:(id)arg1;
-(void)windowDidResignMain:(id)arg1;
-(void)windowDidResize:(id)arg1;
-(void)windowDidUpdate:(id)arg1;
-(BOOL)windowShouldClose:(id)arg1;
-(BOOL)windowShouldZoom:(id)arg1 toFrame:(CGRect)arg2;
-(void)windowWillBeginSheet:(id)arg1;
-(void)windowWillClose:(id)arg1;
-(void)windowWillEnterFullScreen:(id)arg1;
-(void)windowWillEnterVersionBrowser:(id)arg1;
-(void)windowWillExitFullScreen:(id)arg1;
-(void)windowWillExitVersionBrowser:(id)arg1;
-(void)windowWillMiniaturize:(id)arg1;
-(CGSize*)windowWillResize:(id)arg1 toSize:(CGSize)arg2;
-(id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2;
-(id)windowWillReturnUndoManager:(id)arg1;
-(void)windowWillStartLiveResize:(id)arg1;
-(CGRect*)windowWillUseStandardFrame:(id)arg1 defaultFrame:(CGRect)arg2;

@end

