/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXBarItem.h"
#import "UXKitAppearance.h"

@class NSColor, NSView, NSString, NSMenu, NSLayoutAnchor, UXViewController;

@interface UXBarButtonItem : UXBarItem <UXKitAppearance> {

	NSView* __view;
	BOOL _wantsToUseCustomWidth;
	BOOL _ignoresMultiClick;
	BOOL _isSystemItem;
	BOOL _condensed;
	float _visibilityPriority;
	NSColor* _tintColor;
	long long _tintAdjustmentMode;
	SEL _action;
	id _target;
	NSString* _toolTip;
	NSString* _identifier;
	NSString* _keyEquivalent;
	unsigned long long _keyEquivalentModifierMask;
	long long _buttonState;
	long long _style;
	double _width;
	NSView* _customView;
	NSMenu* _menu;
	NSLayoutAnchor* _baselineAnchor;
	UXViewController* _contentViewController;
	long long _systemItem;
	NSString* _label;
	UXBarButtonItem* __widthConstrainingItem;

}

@property (nonatomic, readonly) UXViewController *contentViewController;                                             //@synthesize contentViewController=_contentViewController - In the implementation block
@property (nonatomic, readonly) BOOL isSystemItem;                                                                   //@synthesize isSystemItem=_isSystemItem - In the implementation block
@property (nonatomic, readonly) long long systemItem;                                                                //@synthesize systemItem=_systemItem - In the implementation block
@property (nonatomic, readonly) NSView *_view; 
@property (getter=isCondensed, nonatomic) BOOL condensed;                                                            //@synthesize condensed=_condensed - In the implementation block
@property (nonatomic, copy) NSString *identifier;                                                                    //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic) float visibilityPriority;                                                                      //@synthesize visibilityPriority=_visibilityPriority - In the implementation block
@property (nonatomic, copy) NSString *label;                                                                         //@synthesize label=_label - In the implementation block
@property (setter=_setWidthConstrainingItem:, nonatomic, weak) UXBarButtonItem *_widthConstrainingItem;              //@synthesize _widthConstrainingItem=__widthConstrainingItem - In the implementation block
@property (nonatomic) long long style;                                                                               //@synthesize style=_style - In the implementation block
@property (nonatomic) double width;                                                                                  //@synthesize width=_width - In the implementation block
@property (nonatomic, strong) NSView *customView;                                                                    //@synthesize customView=_customView - In the implementation block
@property (nonatomic) SEL action;                                                                                    //@synthesize action=_action - In the implementation block
@property (nonatomic, weak) id target;                                                                               //@synthesize target=_target - In the implementation block
@property (nonatomic, strong) NSMenu *menu;                                                                          //@synthesize menu=_menu - In the implementation block
@property (nonatomic, strong) NSString *toolTip;                                                                     //@synthesize toolTip=_toolTip - In the implementation block
@property (nonatomic, strong) NSString *keyEquivalent;                                                               //@synthesize keyEquivalent=_keyEquivalent - In the implementation block
@property (nonatomic) unsigned long long keyEquivalentModifierMask;                                                  //@synthesize keyEquivalentModifierMask=_keyEquivalentModifierMask - In the implementation block
@property (nonatomic) long long buttonState;                                                                         //@synthesize buttonState=_buttonState - In the implementation block
@property (nonatomic) BOOL ignoresMultiClick;                                                                        //@synthesize ignoresMultiClick=_ignoresMultiClick - In the implementation block
@property (nonatomic, strong) NSLayoutAnchor *baselineAnchor;                                                        //@synthesize baselineAnchor=_baselineAnchor - In the implementation block
@property (nonatomic, strong) NSColor *tintColor;                                                                    //@synthesize tintColor=_tintColor - In the implementation block
@property (nonatomic) long long tintAdjustmentMode;                                                                  //@synthesize tintAdjustmentMode=_tintAdjustmentMode - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy, readonly) NSString *description; 
@property (copy, readonly) NSString *debugDescription; 
- (id)description;
- (id)identifier;
- (void)setEnabled:(BOOL)arg1;
- (void)setTarget:(id)arg1;
- (id)target;
- (SEL)action;
- (BOOL)isEnabled;
- (id)keyEquivalent;
- (unsigned long long)keyEquivalentModifierMask;
- (id)menu;
- (void)setAction:(SEL)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setTitle:(id)arg1;
- (long long)style;
- (id)image;
- (id)label;
- (void)setLabel:(id)arg1;
- (void)setWidth:(double)arg1;
- (double)width;
- (void)setStyle:(long long)arg1;
- (id)_view;
- (id)toolTip;
- (id)contentViewController;
- (BOOL)ignoresMultiClick;
- (void)setAccessibilityIdentifier:(id)arg1;
- (void)setAccessibilityLabel:(id)arg1;
- (void)setIgnoresMultiClick:(BOOL)arg1;
- (void)setKeyEquivalent:(id)arg1;
- (void)setKeyEquivalentModifierMask:(unsigned long long)arg1;
- (void)setMenu:(id)arg1;
- (void)setTintColor:(id)arg1;
- (void)setToolTip:(id)arg1;
- (void)setVisibilityPriority:(float)arg1;
- (id)tintColor;
- (float)visibilityPriority;
- (id)initWithTitle:(id)arg1 style:(long long)arg2 target:(id)arg3 action:(SEL)arg4;
- (void)setButtonState:(long long)arg1;
- (long long)buttonState;
- (id)customView;
- (id)initWithCustomView:(id)arg1;
- (id)initWithImage:(id)arg1 style:(long long)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)initWithBarButtonSystemItem:(long long)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)initWithContentViewController:(id)arg1;
- (BOOL)isSystemItem;
- (void)setCustomView:(id)arg1;
- (void)setTintAdjustmentMode:(long long)arg1;
- (long long)systemItem;
- (long long)tintAdjustmentMode;
- (void)tintColorDidChange;
- (void)_setWidthConstrainingItem:(id)arg1;
- (id)_viewOfClass:(Class)arg1;
- (id)_widthConstrainingItem;
- (id)baselineAnchor;
- (id)initWithBarButtonSystemItem:(long long)arg1 width:(double)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)initWithStyle:(long long)arg1 target:(id)arg2 action:(SEL)arg3;
- (BOOL)isCondensed;
- (double)preferredSpacingToItem:(id)arg1 proposedSpacing:(double)arg2;
- (void)setBaselineAnchor:(id)arg1;
- (void)setCondensed:(BOOL)arg1;
@end

