/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSSegmentedControl.h>

@class NSString, NSImage;

@interface UXBackButton : NSSegmentedControl {

	BOOL _hidesTitle;
	NSString* _title;
	NSImage* _image;

}

@property (nonatomic) BOOL hidesTitle;                     //@synthesize hidesTitle=_hidesTitle - In the implementation block
@property (nonatomic, copy) NSString *title;               //@synthesize title=_title - In the implementation block
@property (nonatomic, strong) NSImage *image;              //@synthesize image=_image - In the implementation block
- (id)description;
- (id)init;
- (void)setImage:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)image;
- (id)title;
- (id)accessibilityHitTest:(CGPoint)arg1;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityRole;
- (BOOL)hidesTitle;
- (void)setHidesTitle:(BOOL)arg1;
@end

