/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@class NSString, NSImage;

@interface UXBarItem : NSObject {

	BOOL _enabled;
	NSString* _title;
	NSString* _accessibilityLabel;
	NSImage* _image;
	long long _tag;
	NSString* _accessibilityIdentifier;

}

@property (getter=isEnabled, nonatomic) BOOL enabled;                       //@synthesize enabled=_enabled - In the implementation block
@property (nonatomic, strong) NSString *title;                              //@synthesize title=_title - In the implementation block
@property (nonatomic, copy) NSString *accessibilityLabel;                   //@synthesize accessibilityLabel=_accessibilityLabel - In the implementation block
@property (nonatomic, strong) NSImage *image;                               //@synthesize image=_image - In the implementation block
@property (nonatomic) long long tag;                                        //@synthesize tag=_tag - In the implementation block
@property (nonatomic, copy) NSString *accessibilityIdentifier;              //@synthesize accessibilityIdentifier=_accessibilityIdentifier - In the implementation block
- (id)init;
- (void)setEnabled:(BOOL)arg1;
- (void)setTag:(long long)arg1;
- (BOOL)isEnabled;
- (void)setImage:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)image;
- (id)title;
- (long long)tag;
- (id)accessibilityIdentifier;
- (id)accessibilityLabel;
- (void)setAccessibilityIdentifier:(id)arg1;
- (void)setAccessibilityLabel:(id)arg1;
@end

