/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@protocol UXCollectionViewDelegate <NSObject>
@optional
-(void)collectionView:(id)arg1 didEndDisplayingSupplementaryView:(id)arg2 forElementOfKind:(id)arg3 atIndexPath:(id)arg4;
-(void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
-(void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
-(void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
-(BOOL)collectionView:(id)arg1 shouldDeselectItemAtIndexPath:(id)arg2;
-(BOOL)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
-(void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
-(void)collectionView:(id)arg1 didPrepareForOverdraw:(CGRect)arg2;
-(void)collectionView:(id)arg1 indexPathsForSelectedItemsDidAdd:(id)arg2 remove:(id)arg3 animated:(BOOL)arg4;
-(void)collectionView:(id)arg1 indexPathsForSelectedItemsWillAdd:(id)arg2 remove:(id)arg3 animated:(BOOL)arg4;
-(void)collectionView:(id)arg1 itemWasDoubleClickedAtIndexPath:(id)arg2 withEvent:(id)arg3;
-(void)collectionView:(id)arg1 itemWasRightClickedAtIndexPath:(id)arg2 withEvent:(id)arg3;
-(void)collectionView:(id)arg1 mouseDownWithEvent:(id)arg2;
-(CGPoint*)collectionView:(id)arg1 targetContentOffsetOnResizeForProposedContentOffset:(CGPoint)arg2;
-(void)collectionViewDidEndDecelerating:(id)arg1;
-(void)collectionViewDidEndScrolling:(id)arg1;
-(void)collectionViewDidEndScrollingAnimation:(id)arg1;
-(void)collectionViewDidScroll:(id)arg1;
-(void)collectionViewWillBeginDecelerating:(id)arg1 targetContentOffset:(CGPoint)arg2;
-(void)collectionViewWillBeginScrolling:(id)arg1;

@end

