/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@class NSIndexPath;

@interface UXCollectionViewUpdateItem : NSObject {

	NSIndexPath* _initialIndexPath;
	NSIndexPath* _finalIndexPath;
	long long _updateAction;
	id _gap;

}

@property (nonatomic, strong, readonly) NSIndexPath *indexPathBeforeUpdate;              //@synthesize initialIndexPath=_initialIndexPath - In the implementation block
@property (nonatomic, strong, readonly) NSIndexPath *indexPathAfterUpdate;               //@synthesize finalIndexPath=_finalIndexPath - In the implementation block
@property (nonatomic, readonly) long long updateAction;                                  //@synthesize updateAction=_updateAction - In the implementation block
- (void)dealloc;
- (id)description;
- (long long)_action;
- (id)_gap;
- (id)_indexPath;
- (BOOL)_isSectionOperation;
- (id)_newIndexPath;
- (void)_setNewIndexPath:(id)arg1;
- (long long)compareIndexPaths:(id)arg1;
- (id)indexPathAfterUpdate;
- (id)indexPathBeforeUpdate;
- (id)initWithAction:(long long)arg1 forIndexPath:(id)arg2;
- (id)initWithInitialIndexPath:(id)arg1 finalIndexPath:(id)arg2 updateAction:(long long)arg3;
- (id)initWithOldIndexPath:(id)arg1 newIndexPath:(id)arg2;
- (long long)inverseCompareIndexPaths:(id)arg1;
- (long long)updateAction;
- (void)_setGap:(id)arg1;
@end

