/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXCollectionReusableView.h"

@class NSView;

@interface UXCollectionViewCell : UXCollectionReusableView {

	NSView* _contentView;
	BOOL _selected;
	BOOL _selectionBorderShouldUsePrimaryColor;
	BOOL _highlighted;

}

@property (nonatomic, readonly) NSView *contentView;                          //@synthesize contentView=_contentView - In the implementation block
@property (getter=isSelected, nonatomic) BOOL selected;                       //@synthesize selected=_selected - In the implementation block
@property (nonatomic) BOOL selectionBorderShouldUsePrimaryColor;              //@synthesize selectionBorderShouldUsePrimaryColor=_selectionBorderShouldUsePrimaryColor - In the implementation block
@property (getter=isHighlighted, nonatomic) BOOL highlighted;                 //@synthesize highlighted=_highlighted - In the implementation block
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)prepareForReuse;
- (BOOL)isAccessibilitySelectorAllowed:(SEL)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (id)_accessibilityIndexPath;
- (void)_setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)accessibilityPerformPress;
- (id)contentView;
- (id)initWithFrame:(CGRect)arg1;
- (BOOL)isAccessibilitySelected;
- (BOOL)isHighlighted;
- (BOOL)isSelected;
- (void)resizeSubviewsWithOldSize:(CGSize)arg1;
- (void)setAccessibilitySelected:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1;
- (BOOL)wantsUpdateLayer;
- (id)_accessibilityDefaultRole;
- (void)_axPerformDoubleClick;
- (id)_axSimulateClick:(unsigned long long)arg1 withNumberOfClicks:(unsigned long long)arg2;
- (id)_dynamicAccessibilityParent;
- (BOOL)selectionBorderShouldUsePrimaryColor;
- (void)setSelectionBorderShouldUsePrimaryColor:(BOOL)arg1;
@end

