/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <Cocoa/Cocoa.h>

@class NSMutableIndexSet, NSMutableDictionary;

@interface UXCollectionViewIndexPathsSet : NSObject <NSCopying, NSMutableCopying> {

	NSMutableIndexSet* _sectionIndexes;
	NSMutableDictionary* _sectionToItemIndexesMap;

}
+ (id)indexPathsSetWithIndexPathsSet:(id)arg1;
+ (id)indexPathsSet;
+ (id)indexPathsSetWithIndexPath:(id)arg1;
+ (id)indexPathsSetWithIndexPaths:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(NSZone*)arg1;
- (id)description;
- (id)init;
- (BOOL)isEqual:(id)arg1;
- (id)mutableCopyWithZone:(NSZone*)arg1;
- (unsigned long long)count;
- (id)allIndexPaths;
- (BOOL)containsIndexPath:(id)arg1;
- (id)sections;
- (id)initWithIndexPath:(id)arg1;
- (id)itemsInSection:(long long)arg1;
- (void)_addIndexPathsSet:(id)arg1;
- (void)_addOneIndexPath:(id)arg1;
- (void)_enumerateSectionItemIndexesWithBlock:(/*^block*/id)arg1;
- (id)_itemIndexesForSection:(unsigned long long)arg1 allowingCreation:(BOOL)arg2;
- (void)_removeItemIndexesForSection:(unsigned long long)arg1;
- (void)_removeOneIndexPath:(id)arg1;
- (void)enumerateIndexPathsUsingBlock:(/*^block*/id)arg1;
- (id)firstIndexPath;
- (id)indexPathsForSection:(long long)arg1;
- (id)indexPathsForSections:(id)arg1;
- (id)initWithIndexPaths:(id)arg1;
- (id)initWithIndexPathsSet:(id)arg1;
- (id)lastIndexPath;
@end

