/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


#import "UXKit-Structs.h"
@class UXCollectionViewUpdateItem, NSMutableArray, NSArray;

@interface UXCollectionViewUpdateGap : NSObject {

	UXCollectionViewUpdateItem* _firstUpdateItem;
	UXCollectionViewUpdateItem* _lastUpdateItem;
	NSMutableArray* _deleteItems;
	NSMutableArray* _insertItems;
	CGRect _beginningRect;
	CGRect _endingRect;

}

@property (nonatomic, strong) UXCollectionViewUpdateItem *firstUpdateItem;              //@synthesize firstUpdateItem=_firstUpdateItem - In the implementation block
@property (nonatomic, strong) UXCollectionViewUpdateItem *lastUpdateItem;               //@synthesize lastUpdateItem=_lastUpdateItem - In the implementation block
@property (nonatomic, readonly) NSArray *updateItems; 
@property (nonatomic, readonly) NSArray *deleteItems;                                   //@synthesize deleteItems=_deleteItems - In the implementation block
@property (nonatomic, readonly) NSArray *insertItems;                                   //@synthesize insertItems=_insertItems - In the implementation block
@property (nonatomic, readonly) BOOL isDeleteBasedGap; 
@property (nonatomic, readonly) BOOL hasInserts; 
@property (nonatomic, readonly) BOOL isSectionBasedGap; 
@property (nonatomic) CGRect beginningRect;                                             //@synthesize beginningRect=_beginningRect - In the implementation block
@property (nonatomic) CGRect endingRect;                                                //@synthesize endingRect=_endingRect - In the implementation block
+ (id)gapWithUpdateItem:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)init;
- (id)updateItems;
- (id)firstUpdateItem;
- (void)addUpdateItem:(id)arg1;
- (id)deleteItems;
- (BOOL)hasInserts;
- (id)insertItems;
- (BOOL)isDeleteBasedGap;
- (BOOL)isSectionBasedGap;
- (id)lastUpdateItem;
- (void)setFirstUpdateItem:(id)arg1;
- (void)setLastUpdateItem:(id)arg1;
- (CGRect)beginningRect;
- (CGRect)endingRect;
- (void)setBeginningRect:(CGRect)arg1;
- (void)setEndingRect:(CGRect)arg1;
@end

