/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSView.h>

@class UXCollectionView;

@interface UXCollectionDocumentView : NSView {

	UXCollectionView* _collectionView;

}

@property (nonatomic, weak) UXCollectionView *collectionView;              //@synthesize collectionView=_collectionView - In the implementation block
- (void)layout;
- (void)_invalidateFocus;
- (BOOL)acceptsFirstResponder;
- (id)accessibilityHitTest:(CGPoint)arg1;
- (id)collectionView;
- (id)initWithFrame:(CGRect)arg1;
- (BOOL)isFlipped;
- (BOOL)isOpaque;
- (void)prepareContentInRect:(CGRect)arg1;
- (void)setCollectionView:(id)arg1;
- (BOOL)wantsUpdateLayer;
@end

