/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


#import "UXKit-Structs.h"
@class UXCollectionReusableView, UXCollectionViewLayoutAttributes, NSMutableArray;

@interface UXCollectionViewAnimation : NSObject {

	UXCollectionReusableView* _view;
	UXCollectionViewLayoutAttributes* _finalLayoutAttributes;
	double _startFraction;
	double _endFraction;
	unsigned long long _viewType;
	NSMutableArray* _completionHandlers;
	NSMutableArray* _startupHandlers;
	/*^block*/id _animationBlock;
	struct {
		unsigned animateFromCurrentPosition : 1;
		unsigned deleteAterAnimation : 1;
		unsigned rasterizeAfterAnimation : 1;
		unsigned resetRasterizationAfterAnimation : 1;
	}  _collectionViewAnimationFlags;

}

@property (nonatomic, readonly) UXCollectionReusableView *view;                                       //@synthesize view=_view - In the implementation block
@property (nonatomic, readonly) unsigned long long viewType;                                          //@synthesize viewType=_viewType - In the implementation block
@property (nonatomic, readonly) UXCollectionViewLayoutAttributes *finalLayoutAttributes;              //@synthesize finalLayoutAttributes=_finalLayoutAttributes - In the implementation block
@property (nonatomic, readonly) double startFraction;                                                 //@synthesize startFraction=_startFraction - In the implementation block
@property (nonatomic, readonly) double endFraction;                                                   //@synthesize endFraction=_endFraction - In the implementation block
@property (nonatomic, readonly) BOOL animateFromCurrentPosition; 
@property (nonatomic, readonly) BOOL deleteAfterAnimation; 
@property (nonatomic) BOOL rasterizeAfterAnimation; 
@property (nonatomic) BOOL resetRasterizationAfterAnimation; 
- (void)dealloc;
- (id)description;
- (void)start;
- (id)view;
- (void)addCompletionHandler:(/*^block*/id)arg1;
- (void)addStartupHandler:(/*^block*/id)arg1;
- (BOOL)animateFromCurrentPosition;
- (BOOL)deleteAfterAnimation;
- (double)endFraction;
- (id)finalLayoutAttributes;
- (BOOL)rasterizeAfterAnimation;
- (BOOL)resetRasterizationAfterAnimation;
- (void)setRasterizeAfterAnimation:(BOOL)arg1;
- (void)setResetRasterizationAfterAnimation:(BOOL)arg1;
- (double)startFraction;
- (unsigned long long)viewType;
- (id)initWithView:(id)arg1 viewType:(unsigned long long)arg2 finalLayoutAttributes:(id)arg3 startFraction:(double)arg4 endFraction:(double)arg5 animateFromCurrentPosition:(BOOL)arg6 deleteAfterAnimation:(BOOL)arg7 customAnimations:(/*^block*/id)arg8;
@end

