/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSAccessibilityElement.h>

@class NSArray, UXCollectionViewLayout, NSMutableArray, UXCollectionView;

@interface UXCollectionViewLayoutAccessibility : NSAccessibilityElement {

	NSArray* _accessibilityVisibleChildren;
	UXCollectionViewLayout* _layout;
	unsigned long long __sectionCacheOffset;
	NSMutableArray* __sectionCache;

}

@property (nonatomic, weak) UXCollectionViewLayout *layout;                               //@synthesize layout=_layout - In the implementation block
@property (nonatomic) unsigned long long _sectionCacheOffset;                             //@synthesize _sectionCacheOffset=__sectionCacheOffset - In the implementation block
@property (nonatomic, strong) NSMutableArray *_sectionCache;                              //@synthesize _sectionCache=__sectionCache - In the implementation block
@property (nonatomic, weak, readonly) UXCollectionView *collectionView; 
@property (nonatomic, copy, readonly) NSArray *accessibilityVisibleChildren;              //@synthesize accessibilityVisibleChildren=_accessibilityVisibleChildren - In the implementation block
@property (nonatomic, copy) NSArray *accessibilitySelectedCells; 
+ (Class)sectionAccessibilityClass;
- (id)layout;
- (id)initWithLayout:(id)arg1;
- (void)setLayout:(id)arg1;
- (CGRect)accessibilityFrameInParentSpace;
- (id)_dequeueSectionWithIndex:(unsigned long long)arg1;
- (void)_dumpVisibleChildren;
- (id)_sectionCache;
- (unsigned long long)_sectionCacheOffset;
- (void)_trimSectionCacheToVisibleSections:(id)arg1;
- (id)_visibleSections;
- (unsigned long long)accessibilityArrayAttributeCount:(id)arg1;
- (id)accessibilityArrayAttributeValues:(id)arg1 index:(unsigned long long)arg2 maxCount:(unsigned long long)arg3;
- (id)accessibilityChildren;
- (long long)accessibilityColumnCount;
- (void)accessibilityDidEndScrolling;
- (CGRect)accessibilityFrame;
- (id)accessibilityHitTest:(CGPoint)arg1;
- (id)accessibilityIdentifier;
- (unsigned long long)accessibilityIndexOfChild:(id)arg1;
- (void)accessibilityInvalidateLayout;
- (id)accessibilityLabel;
- (id)accessibilityParent;
- (void)accessibilityPostNotification:(id)arg1;
- (void)accessibilityPrepareLayout;
- (id)accessibilityRole;
- (id)accessibilityRoleDescription;
- (long long)accessibilityRowCount;
- (id)accessibilitySelectedCells;
- (id)accessibilitySubrole;
- (id)accessibilityVisibleChildren;
- (id)collectionView;
- (id)nextSectionForSection:(id)arg1;
- (id)previousSectionForSection:(id)arg1;
- (void)setAccessibilitySelectedCells:(id)arg1;
- (void)set_sectionCacheOffset:(unsigned long long)arg1;
- (id)accessibilityParentForCell:(id)arg1;
- (id)accessibilityParentForReusableView:(id)arg1;
- (void)accessibilityPrepareForCollectionViewUpdates:(id)arg1;
- (void)set_sectionCache:(id)arg1;
@end

