/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSView.h>

@class UXCollectionViewLayoutAttributes, NSString, UXCollectionView;

@interface UXCollectionReusableView : NSView {

	UXCollectionViewLayoutAttributes* _layoutAttributes;
	NSString* _reuseIdentifier;
	UXCollectionView* _collectionView;
	struct {
		unsigned updateAnimationCount : 5;
		unsigned wasDequeued : 1;
	}  _reusableViewFlags;
	BOOL _isFloatingPinned;

}

@property (nonatomic, copy, readonly) NSString *reuseIdentifier;              //@synthesize reuseIdentifier=_reuseIdentifier - In the implementation block
@property (nonatomic, readonly) BOOL isFloatingPinned;                        //@synthesize isFloatingPinned=_isFloatingPinned - In the implementation block
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)prepareForReuse;
- (id)reuseIdentifier;
- (id)_collectionView;
- (void)_markAsDequeued;
- (id)accessibilityActionDescription:(id)arg1;
- (id)_accessibilityIndexPath;
- (void)_addUpdateAnimation;
- (void)_clearUpdateAnimation;
- (BOOL)_isInUpdateAnimation;
- (id)_layoutAttributes;
- (void)_setBaseLayoutAttributes:(id)arg1;
- (void)_setCollectionView:(id)arg1;
- (void)_setLayoutAttributes:(id)arg1;
- (void)_setReuseIdentifier:(id)arg1;
- (BOOL)_wasDequeued;
- (id)accessibilityActionNames;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityParent;
- (void)accessibilityPerformAction:(id)arg1;
- (BOOL)accessibilityPerformScrollToVisible;
- (id)accessibilityRole;
- (void)applyLayoutAttributes:(id)arg1;
- (void)didTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (id)initWithFrame:(CGRect)arg1;
- (BOOL)wantsUpdateLayer;
- (void)willTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (CGImageRef)_snapshot:(BOOL)arg1;
- (id)_accessibilityDefaultRole;
- (id)_dynamicAccessibilityParent;
- (id)_layoutSectionAccessibility;
- (BOOL)isFloatingPinned;
- (void)setIsFloatingPinned:(BOOL)arg1;
@end

