/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


@class NSArray;

@interface UXCollectionViewAnimationContext : NSObject {

	NSArray* _viewAnimations;
	long long _animationCount;
	id _completionHandler;

}

@property (nonatomic, strong) NSArray *viewAnimations;                   //@synthesize viewAnimations=_viewAnimations - In the implementation block
@property (nonatomic) long long animationCount;                          //@synthesize animationCount=_animationCount - In the implementation block
@property (nonatomic, copy, readonly) id completionHandler;              //@synthesize completionHandler=_completionHandler - In the implementation block
- (void)dealloc;
- (long long)animationCount;
- (id)completionHandler;
- (id)initWithCompletionHandler:(/*^block*/id)arg1;
- (void)setAnimationCount:(long long)arg1;
- (void)setViewAnimations:(id)arg1;
- (id)viewAnimations;
@end

