/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXView.h"

@interface UXControl : UXView {

	BOOL _highlighted;
	BOOL _selected;
	BOOL _enabled;
	BOOL _ignoresMultiClick;
	BOOL _sendsActionOnMouseDown;
	id _target;
	SEL _action;

}

@property (nonatomic, weak) id target;                                     //@synthesize target=_target - In the implementation block
@property (nonatomic) SEL action;                                          //@synthesize action=_action - In the implementation block
@property (getter=isHighlighted, nonatomic) BOOL highlighted;              //@synthesize highlighted=_highlighted - In the implementation block
@property (getter=isSelected, nonatomic) BOOL selected;                    //@synthesize selected=_selected - In the implementation block
@property (getter=isEnabled, nonatomic) BOOL enabled;                      //@synthesize enabled=_enabled - In the implementation block
@property (nonatomic) BOOL ignoresMultiClick;                              //@synthesize ignoresMultiClick=_ignoresMultiClick - In the implementation block
@property (nonatomic) BOOL sendsActionOnMouseDown;                         //@synthesize sendsActionOnMouseDown=_sendsActionOnMouseDown - In the implementation block
- (void)setEnabled:(BOOL)arg1;
- (void)setTarget:(id)arg1;
- (id)target;
- (SEL)action;
- (BOOL)isEnabled;
- (void)setAction:(SEL)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (BOOL)ignoresMultiClick;
- (id)initWithFrame:(CGRect)arg1;
- (BOOL)isFlipped;
- (BOOL)isHighlighted;
- (BOOL)isSelected;
- (void)mouseDown:(id)arg1;
- (BOOL)sendAction:(SEL)arg1 to:(id)arg2;
- (void)setIgnoresMultiClick:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)setTarget:(id)arg1 action:(SEL)arg2;
- (BOOL)_locationInsideForEvent:(id)arg1;
- (BOOL)sendsActionOnMouseDown;
- (void)setSendsActionOnMouseDown:(BOOL)arg1;
@end

