/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import <Cocoa/Cocoa.h>

@class NSMutableDictionary, NSString;

@interface UXDestinationAuxiliaryStore : NSObject <NSSecureCoding> {

	NSMutableDictionary* _namespaceDict;
	NSMutableDictionary* _globalDict;
	NSString* _lastAction;

}
+ (BOOL)supportsSecureCoding;
- (id)debugDescription;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)_allowedClassesForNSCoding;
- (id)_dictionaryForNamespace:(id)arg1;
- (void)_setRawValue:(id)arg1 forKey:(id)arg2 inNamespace:(id)arg3;
- (void)addEntriesFromDictionary:(id)arg1 inNamespace:(id)arg2;
- (id)dictionaryWithValuesForKeys:(id)arg1 inNamespace:(id)arg2;
- (id)nextActionForNamespace:(id)arg1;
- (void)setBlock:(/*^block*/id)arg1 forKey:(id)arg2 inNamespace:(id)arg3;
- (void)setNextAction:(id)arg1 forNamespace:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2 inNamespace:(id)arg3;
- (id)valueForKey:(id)arg1 inNamespace:(id)arg2;
@end

