/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

//typedef struct _NSZone* NSZoneRef;

typedef struct {
	unsigned long long field1;
	id field2;
	unsigned long long field3;
	unsigned long long field4[5];
} SCD_Struct_UX1;

//typedef struct CGPoint {
//	double x;
//	double y;
//} CGPoint;
//
//typedef struct CGSize {
//	double width;
//	double height;
//} CGSize;
//
//typedef struct CGRect {
//	CGPoint origin;
//	CGSize size;
//} CGRect;
//
//typedef struct NSEdgeInsets {
//	double top;
//	double left;
//	double bottom;
//	double right;
//} NSEdgeInsets;
//
//typedef struct NSRange {
//	unsigned long long location;
//	unsigned long long length;
//} NSRange;
//
//typedef struct CGImage* CGImageRef;
//
