/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXView.h"
#import <Cocoa/Cocoa.h>

@class NSTextField, NSArray, NSColor, NSString, NSFont, NSAttributedString;

@interface UXLabel : UXView <NSAccessibilityStaticText> {

	NSTextField* _concreteTextField;
	NSArray* _verticalDefaultConstraints;
	NSArray* _verticalCenteringConstraints;
	NSColor* _textColor;
	NSColor* _shadowColor;
	NSColor* _highlightedTextColor;
	long long _numberOfLines;
	CGSize _shadowOffset;

}

@property (nonatomic, copy) NSString *text; 
@property (nonatomic, strong) NSFont *font; 
@property (nonatomic, strong) NSColor *textColor;                            //@synthesize textColor=_textColor - In the implementation block
@property (nonatomic, strong) NSColor *shadowColor;                          //@synthesize shadowColor=_shadowColor - In the implementation block
@property (nonatomic) CGSize shadowOffset;                                   //@synthesize shadowOffset=_shadowOffset - In the implementation block
@property (nonatomic) long long textAlignment; 
@property (nonatomic) unsigned long long lineBreakMode; 
@property (nonatomic) BOOL selectable; 
@property (nonatomic, copy) NSAttributedString *attributedText; 
@property (nonatomic, strong) NSColor *highlightedTextColor;                 //@synthesize highlightedTextColor=_highlightedTextColor - In the implementation block
@property (getter=isHighlighted, nonatomic) BOOL highlighted; 
@property (nonatomic) long long numberOfLines;                               //@synthesize numberOfLines=_numberOfLines - In the implementation block
@property (nonatomic) double preferredMaxLayoutWidth; 
@property (nonatomic) BOOL centerVertically;
- (unsigned long long)lineBreakMode;
- (NSEdgeInsets)alignmentRectInsets;
- (double)firstBaselineOffsetFromTop;
- (id)initWithFrame:(CGRect)arg1;
- (CGSize)intrinsicContentSize;
- (double)lastBaselineOffsetFromBottom;
- (double)preferredMaxLayoutWidth;
- (void)setContentCompressionResistancePriority:(float)arg1 forOrientation:(long long)arg2;
- (CGSize)sizeThatFits:(CGSize)arg1;
- (void)sizeToFit;
- (CGRect)textRectForBounds:(CGRect)arg1 limitedToNumberOfLines:(long long)arg2;
- (id)textFieldCell;
@end

