/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

@class NSLayoutYAxisAnchor, NSLayoutDimension;


@protocol UXLayoutSupport <NSObject>
@property (nonatomic) double length; 
@property (readonly) NSLayoutYAxisAnchor *topAnchor; 
@property (readonly) NSLayoutYAxisAnchor *bottomAnchor; 
@property (readonly) NSLayoutDimension *heightAnchor; 
@required
-(double)length;
-(void)setLength:(double)arg1;
-(id)bottomAnchor;
-(id)heightAnchor;
-(id)topAnchor;

@end

