/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */


#import "UXKit-Structs.h"
@class NSArray, NSTextField, NSString, UXBarButtonItem, NSView, NSToolbarItemGroup;

@interface UXNavigationItem : NSObject {

	NSArray* _leftBarButtonItems;
	NSArray* _rightBarButtonItems;
	NSTextField* _internalTitleView;
	BOOL _hidesBackButton;
	BOOL _hidesAlternateTitleView;
	BOOL _hidesGlobalTrailingView;
	BOOL _leftItemsSupplementBackButton;
	NSString* _title;
	UXBarButtonItem* _backBarButtonItem;
	NSView* _titleView;
	NSString* _prompt;
	NSString* _identifier;
	NSView* _condensedTitleView;
	UXBarButtonItem* _switchLibraryButtonItem;
	NSToolbarItemGroup* _centerToolbarItemGroup;
	NSEdgeInsets _layoutMargins;

}

@property (nonatomic, readonly) NSTextField *internalTitleView; 
@property (nonatomic, copy) NSString *identifier;                                      //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic, strong) NSView *condensedTitleView;                              //@synthesize condensedTitleView=_condensedTitleView - In the implementation block
@property (nonatomic, strong) UXBarButtonItem *switchLibraryButtonItem;                //@synthesize switchLibraryButtonItem=_switchLibraryButtonItem - In the implementation block
@property (nonatomic, strong) NSToolbarItemGroup *centerToolbarItemGroup;              //@synthesize centerToolbarItemGroup=_centerToolbarItemGroup - In the implementation block
@property (nonatomic) NSEdgeInsets layoutMargins;                                      //@synthesize layoutMargins=_layoutMargins - In the implementation block
@property (nonatomic, strong) NSString *title;                                         //@synthesize title=_title - In the implementation block
@property (nonatomic, strong) UXBarButtonItem *backBarButtonItem;                      //@synthesize backBarButtonItem=_backBarButtonItem - In the implementation block
@property (nonatomic, strong) NSView *titleView;                                       //@synthesize titleView=_titleView - In the implementation block
@property (nonatomic, copy) NSString *prompt;                                          //@synthesize prompt=_prompt - In the implementation block
@property (nonatomic) BOOL hidesBackButton;                                            //@synthesize hidesBackButton=_hidesBackButton - In the implementation block
@property (nonatomic) BOOL hidesAlternateTitleView;                                    //@synthesize hidesAlternateTitleView=_hidesAlternateTitleView - In the implementation block
@property (nonatomic) BOOL hidesGlobalTrailingView;                                    //@synthesize hidesGlobalTrailingView=_hidesGlobalTrailingView - In the implementation block
@property (nonatomic, strong) NSArray *leftBarButtonItems; 
@property (nonatomic, strong) NSArray *rightBarButtonItems; 
@property (nonatomic) BOOL leftItemsSupplementBackButton;                              //@synthesize leftItemsSupplementBackButton=_leftItemsSupplementBackButton - In the implementation block
@property (nonatomic, strong) UXBarButtonItem *leftBarButtonItem; 
@property (nonatomic, strong) UXBarButtonItem *rightBarButtonItem; 
@property (nonatomic, strong) NSArray *leadingBarButtonItems; 
@property (nonatomic, strong) NSArray *trailingBarButtonItems; 
+ (id)keyPathsToObserve;
- (id)identifier;
- (id)initWithTitle:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setPrompt:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;
- (id)prompt;
- (NSEdgeInsets)layoutMargins;
- (void)setLayoutMargins:(NSEdgeInsets)arg1;
- (void)setTitleView:(id)arg1;
- (id)titleView;
- (id)rightBarButtonItem;
- (void)setRightBarButtonItem:(id)arg1;
- (BOOL)hidesBackButton;
- (id)backBarButtonItem;
- (id)leftBarButtonItems;
- (id)rightBarButtonItems;
- (void)setBackBarButtonItem:(id)arg1;
- (void)setHidesBackButton:(BOOL)arg1;
- (void)setLeftBarButtonItems:(id)arg1;
- (void)setRightBarButtonItems:(id)arg1;
- (void)setRightBarButtonItem:(id)arg1 animated:(BOOL)arg2;
- (void)setLeftBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (id)leadingBarButtonItems;
- (id)leftBarButtonItem;
- (BOOL)leftItemsSupplementBackButton;
- (void)setLeadingBarButtonItems:(id)arg1;
- (void)setLeftBarButtonItem:(id)arg1;
- (void)setLeftBarButtonItem:(id)arg1 animated:(BOOL)arg2;
- (void)setLeftItemsSupplementBackButton:(BOOL)arg1;
- (void)setRightBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (void)setTrailingBarButtonItems:(id)arg1;
- (id)trailingBarButtonItems;
- (void)_updateInternalTitleView;
- (id)centerToolbarItemGroup;
- (id)condensedTitleView;
- (BOOL)hidesAlternateTitleView;
- (BOOL)hidesGlobalTrailingView;
- (id)internalTitleView;
- (void)setCenterToolbarItemGroup:(id)arg1;
- (void)setCondensedTitleView:(id)arg1;
- (void)setHidesAlternateTitleView:(BOOL)arg1;
- (void)setHidesGlobalTrailingView:(BOOL)arg1;
- (void)setLeadingBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (void)setSwitchLibraryButtonItem:(id)arg1;
- (void)setTrailingBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (id)switchLibraryButtonItem;
@end

