/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXNavigationController.h"
@class UXNavigationController, UXViewController;
@protocol UXViewControllerInteractiveTransitioning, UXViewControllerAnimatedTransitioning;

NS_HEADER_AUDIT_BEGIN(nullability, sendability)
@protocol UXNavigationControllerDelegate <NSObject>
@optional
- (nullable id<UXViewControllerAnimatedTransitioning>)navigationController:(UXNavigationController *)navigationController animationControllerForOperation:(UXNavigationControllerOperation)operation fromViewController:(UXViewController *)fromViewController toViewController:(UXViewController *)toViewController;
- (nullable id<UXViewControllerInteractiveTransitioning>)navigationController:(UXNavigationController *)navigationController interactionControllerForAnimationController:(id<UXViewControllerAnimatedTransitioning>)animationController;
- (void)navigationController:(UXNavigationController *)navigationController didShowViewController:(UXViewController *)viewController;
- (BOOL)navigationController:(UXNavigationController *)navigationController shouldBeginInteractivePopFromViewController:(UXViewController *)fromViewController toViewController:(UXViewController *)toViewController;
- (BOOL)navigationController:(UXNavigationController *)navigationController shouldPopFromViewController:(UXViewController *)fromViewController toViewController:(UXViewController *)toViewController;
- (void)navigationController:(UXNavigationController *)navigationController willShowViewController:(UXViewController *)viewController;

@end
NS_HEADER_AUDIT_END(nullability, sendability)
