/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXTransitionController.h"

@class UXView;

@interface UXParallaxTransitionController : UXTransitionController {

	UXView* _dimmingView;

}
+ (void)_addShadowToView:(id)arg1 withAlpha:(double)arg2;
- (void)animateTransition:(id)arg1;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (void)startInteractiveTransition:(id)arg1;
- (void)_setupDimmingViewInContext:(id)arg1 withAlpha:(double)arg2;
- (BOOL)navigationController:(id)arg1 shouldBeginInteractivePopFromViewController:(id)arg2 toViewController:(id)arg3;
- (void)updateInteractiveTransition:(double)arg1 inContext:(id)arg2;
@end

