/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXViewController.h"
#import "UXNavigationControllerDelegate.h"
#import "_UXSourceSplitViewDelegate.h"

@protocol UXNavigationControllerDelegate, UXSourceList;
@class NSView, _UXSourceSplitView, NSLayoutConstraint, _UXViewControllerOneToOneTransitionContext, UXTransitionController, NSMapTable, NSOperationQueue, UXView, UXViewController, NSString, NSArray, NSSegmentedControl, NSPopUpButton, NSWindow, NSSearchToolbarItem, UXNavigationController;

@interface UXSourceController : UXViewController <UXNavigationControllerDelegate, _UXSourceSplitViewDelegate> {

	NSView* _tabBarView;
	_UXSourceSplitView* _splitView;
	NSLayoutConstraint* _popUpWidthContraint;
	BOOL _needsToSetInitialSourceListWidth;
	double _preferredSourceListWidthFraction;
	BOOL _isTransitioning;
	_UXViewControllerOneToOneTransitionContext* _transitionCtx;
	UXTransitionController* _transitionController;
	NSMapTable* _navigationControllerByRootViewController;
	NSMapTable* _transitionControllerClassByToViewControllerClass;
	NSOperationQueue* _viewControllerOperations;
	BOOL _navigatingToDestination;
	id<UXNavigationControllerDelegate> _currentNavigationDelegate;
	id _localEdgeHoverEventMonitor;
	id _globalEdgeHoverEventMonitor;
	id _windowResizeObserver;
	id _windowDeactivateObserver;
	UXView* _transientlyUncollapsedView;
	BOOL _hasItemToRevealOnEdgeHover;
	BOOL _wantsDetachedNavigationBars;
	long long _preferredStyle;
	long long _style;
	UXViewController<UXSourceList>* _sourceListViewController;
	double _minimumWidthForInlineSourceList;
	NSString* _sourceListAutosaveName;
	NSArray* _rootViewControllers;
	UXViewController* _selectedViewController;
	NSSegmentedControl* _segmentedControl;
	NSPopUpButton* _popUpButton;
	NSWindow* _observedWindow;
	NSSearchToolbarItem* _searchToolbarItem;

}

@property (nonatomic, readonly) NSSegmentedControl *segmentedControl;                                  //@synthesize segmentedControl=_segmentedControl - In the implementation block
@property (nonatomic, readonly) NSPopUpButton *popUpButton;                                            //@synthesize popUpButton=_popUpButton - In the implementation block
@property (nonatomic, weak) NSWindow *observedWindow;                                                  //@synthesize observedWindow=_observedWindow - In the implementation block
@property (nonatomic, strong) UXViewController *selectedViewController;                                //@synthesize selectedViewController=_selectedViewController - In the implementation block
@property (nonatomic) long long style;                                                                 //@synthesize style=_style - In the implementation block
@property (nonatomic, readonly) BOOL alternateTitleEnabled; 
@property (nonatomic, readonly) NSSearchToolbarItem *searchToolbarItem;                                //@synthesize searchToolbarItem=_searchToolbarItem - In the implementation block
@property (nonatomic) BOOL wantsDetachedNavigationBars;                                                //@synthesize wantsDetachedNavigationBars=_wantsDetachedNavigationBars - In the implementation block
@property (nonatomic) long long preferredStyle;                                                        //@synthesize preferredStyle=_preferredStyle - In the implementation block
@property (nonatomic, readonly) BOOL wantsSourceListCollapsed; 
@property (getter=isSourceListCollapsed, nonatomic, readonly) BOOL sourceListCollapsed; 
@property (nonatomic, strong) UXViewController<UXSourceList> *sourceListViewController;                //@synthesize sourceListViewController=_sourceListViewController - In the implementation block
@property (nonatomic) double minimumWidthForInlineSourceList;                                          //@synthesize minimumWidthForInlineSourceList=_minimumWidthForInlineSourceList - In the implementation block
@property (nonatomic) double preferredSourceListWidthFraction;                                         //@synthesize preferredSourceListWidthFraction=_preferredSourceListWidthFraction - In the implementation block
@property (nonatomic, copy) NSString *sourceListAutosaveName;                                          //@synthesize sourceListAutosaveName=_sourceListAutosaveName - In the implementation block
@property (nonatomic, copy) NSArray *rootViewControllers;                                              //@synthesize rootViewControllers=_rootViewControllers - In the implementation block
@property (nonatomic) unsigned long long selectedIndex; 
@property (nonatomic, readonly) UXNavigationController *selectedNavigationController; 
@property (nonatomic, readonly) id<UXNavigationDestination> currentNavigationDestination; 
@property (nonatomic, readonly) BOOL isNavigating; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy, readonly) NSString *description; 
@property (copy, readonly) NSString *debugDescription; 
+ (Class)_defaultTransitionControllerClass;
+ (id)_widthDefaultsKeyForAutosaveName:(id)arg1;
- (void)dealloc;
- (long long)style;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)setStyle:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)_setHasItemToRevealOnEdgeHover:(BOOL)arg1;
- (void)_didChangeCollapsed;
- (void)_didEnterFullscreen:(id)arg1;
- (void)_didExitFullscreen:(id)arg1;
- (BOOL)_hasItemToRevealOnEdgeHover;
- (void)_startObservingEdgeHover;
- (void)_startObservingFullscreenForWindow:(id)arg1;
- (void)_stopObservingEdgeHover;
- (void)_stopObservingFullscreenForWindow:(id)arg1;
- (void)_uncollapseEdgeRevealItem:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (BOOL)isNavigating;
- (void)keyDown:(id)arg1;
- (long long)preferredStyle;
- (id)segmentedControl;
- (unsigned long long)selectedIndex;
- (id)selectedViewController;
- (void)setPreferredStyle:(long long)arg1;
- (void)setSelectedIndex:(unsigned long long)arg1;
- (void)setSelectedIndex:(unsigned long long)arg1 animated:(BOOL)arg2;
- (void)setSelectedViewController:(id)arg1;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewWillDisappear;
- (id)navigationController;
- (void)_setStyle:(long long)arg1;
- (id)popUpButton;
- (void)dismissViewControllerAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2;
- (id)tabBarView;
- (id)transitionCoordinator;
- (BOOL)_reduceMotionEnabled;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (id)preferredFirstResponder;
- (void)presentViewController:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
- (void)didChangeSelectedViewController;
- (double)minimumWidthForInlineSourceList;
- (void)segmentChanged:(id)arg1;
- (void)_cancelOrDismissUncollapsedItem;
- (void)setWantsDetachedNavigationBars:(BOOL)arg1;
- (void)_addRootViewController:(id)arg1;
- (void)_beginTransitionWithContext:(id)arg1 operation:(long long)arg2;
- (void)_configureManagedNavigationController:(id)arg1;
- (id)_contextForTransitionOperation:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 transition:(unsigned long long)arg4;
- (void)_didChangeSelectedViewControllerFromSender:(id)arg1;
- (long long)_effectiveStyleForViewController:(id)arg1;
- (void)_handleEdgeHoverEvent:(id)arg1;
- (void)_navigateToDestination:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
- (id)_popTransitoryViewControllersInNavigationController:(id)arg1 animated:(BOOL)arg2;
- (double)_preferredSourceListWidth;
- (void)_prepareViewController:(id)arg1 forAnimationInContext:(id)arg2 completion:(/*^block*/id)arg3;
- (void)_removeDestination:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
- (id)_rootViewControllerProvidingViewControllersForNavigationDestination:(id)arg1;
- (void)_saveSourceListWidth:(double)arg1;
- (void)_setLeadingContentInset:(double)arg1;
- (void)_setPreferredStyle:(long long)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
- (void)_setRootViewControllers:(id)arg1 destination:(id)arg2 completion:(/*^block*/id)arg3;
- (void)_setSelectedIndex:(long long)arg1 animated:(BOOL)arg2 sender:(id)arg3;
- (void)_setSelectedViewController:(id)arg1 animated:(BOOL)arg2 sender:(id)arg3;
- (void)_setStyle:(long long)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
- (void)_setWantsSourceListCollapsed:(BOOL)arg1;
- (void)_setWantsSourceListCollapsed:(BOOL)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
- (void)_setupDelegateForNavigationController:(id)arg1 operation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)_updateSelectionControls;
- (BOOL)_wantsSourceListCollapsedForViewController:(id)arg1;
- (void)addRootViewController:(id)arg1;
- (BOOL)alternateTitleEnabled;
- (CGSize)contentSizeForWantsSourceListCollapsed:(BOOL)arg1;
- (id<UXNavigationDestination>)currentNavigationDestination;
- (void)didChangeTopViewControllerForNavigationController:(id)arg1;
- (id)fallbackNavigationDestination;
- (void)insertRootViewController:(id)arg1 atIndex:(long long)arg2;
- (BOOL)isSourceListCollapsed;
- (void)navigateToDestination:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2;
- (BOOL)navigationController:(id)arg1 shouldBeginInteractivePopFromViewController:(id)arg2 toViewController:(id)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2;
- (id)observedWindow;
- (void)popUpChanged:(id)arg1;
- (double)preferredSourceListWidthFraction;
- (void)registerTranistionControllerClass:(Class)arg1 forViewControllerClass:(Class)arg2;
- (void)registerTransitionControllerClass:(Class)arg1 forViewControllerClass:(Class)arg2;
- (void)registerTransitoryViewController:(id)arg1;
- (void)removeDestination:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
- (void)removeRootViewControllerAtIndex:(long long)arg1;
- (id)rootViewControllers;
- (id)searchToolbarItem;
- (id)selectedNavigationController;
- (void)setMinimumWidthForInlineSourceList:(double)arg1;
- (void)setObservedWindow:(id)arg1;
- (void)setPreferredSourceListWidthFraction:(double)arg1;
- (void)setRootViewControllers:(id)arg1;
- (void)setRootViewControllers:(id)arg1 destination:(id)arg2 completion:(/*^block*/id)arg3;
- (void)setSelectedViewController:(id)arg1 animated:(BOOL)arg2;
- (void)setSourceListAutosaveName:(id)arg1;
- (void)setSourceListViewController:(id)arg1;
- (id)sourceListAutosaveName;
- (id)sourceListViewController;
- (BOOL)sourceSplitView:(id)arg1 canSpringLoadRevealSubview:(id)arg2;
- (void)sourceSplitView:(id)arg1 didChangeAutoCollapsedValue:(BOOL)arg2;
- (void)sourceSplitView:(id)arg1 didResizeMasterWidth:(double)arg2;
- (void)unregisterTransitionControllerForTransitionToViewControllerClass:(Class)arg1;
- (void)unregisterTransitoryViewController:(id)arg1;
- (BOOL)wantsDetachedNavigationBars;
- (BOOL)wantsSourceListCollapsed;
- (void)willAddNavigationController:(id)arg1;
- (void)willChangeTopViewController:(id)arg1;
- (void)willSelectViewController:(id)arg1;
- (void)willUpdateToolbarForNavigationController:(id)arg1;
- (void)windowDidUpdateFirstResponder;
@end

