/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXToolbar.h"

@class NSLayoutConstraint;

@interface UXSubtoolbar : UXToolbar {

	NSLayoutConstraint* _heightConstraint;

}

@property (nonatomic, readonly) NSLayoutConstraint *heightConstraint;              //@synthesize heightConstraint=_heightConstraint - In the implementation block
+ (double)defaultHeight;
- (void)setHeight:(double)arg1;
- (id)heightConstraint;
- (id)initWithFrame:(CGRect)arg1;
@end

