/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXCollectionViewCell.h"

@class _UXButton, UXView, NSLayoutConstraint, UXLabel, NSColor, NSMutableArray;

@interface UXTableViewCell : UXCollectionViewCell {

	long long _style;
	_UXButton* _internalAccessoryView;
	UXView* _internalHighlightedBackgroundView;
	UXView* _defaultSelectedBackgroundView;
	UXView* __lineView;
	UXView* _upperSpace;
	UXView* _lowerSpace;
	NSLayoutConstraint* _leadingInsetConstraint;
	NSLayoutConstraint* _trailingInsetConstraint;
	NSLayoutConstraint* _lineHeightConstraint;
	BOOL __highlightingForContext;
	UXView* _backgroundView;
	UXView* _selectedBackgroundView;
	UXLabel* _textLabel;
	UXLabel* _detailTextLabel;
	long long _accessoryType;
	UXView* _accessoryView;
	NSColor* _highlightColor;
	long long _selectionStyle;
	long long _indentationLevel;
	double _indentationWidth;
	NSMutableArray* __addedConstraints;
	long long __separatorStyle;
	double __separatorHeight;
	NSColor* __separatorColor;
	NSEdgeInsets _separatorInset;

}

@property (nonatomic, readonly) _UXButton *internalAccessoryView; 
@property (nonatomic, readonly) UXView *defaultSelectedBackgroundView; 
@property (nonatomic, readonly) UXView *internalHighlightedBackgroundView;                           //@synthesize internalHighlightedBackgroundView=_internalHighlightedBackgroundView - In the implementation block
@property (nonatomic, readonly) UXView *upperSpace; 
@property (nonatomic, readonly) UXView *lowerSpace; 
@property (nonatomic, strong) NSMutableArray *_addedConstraints;                                     //@synthesize _addedConstraints=__addedConstraints - In the implementation block
@property (nonatomic, strong) UXLabel *textLabel;                                                    //@synthesize textLabel=_textLabel - In the implementation block
@property (nonatomic, strong) UXLabel *detailTextLabel;                                              //@synthesize detailTextLabel=_detailTextLabel - In the implementation block
@property (setter=_setHighlightingForContext:, nonatomic) BOOL _highlightingForContext;              //@synthesize _highlightingForContext=__highlightingForContext - In the implementation block
@property (setter=_setSeparatorStyle:, nonatomic) long long _separatorStyle;                         //@synthesize _separatorStyle=__separatorStyle - In the implementation block
@property (setter=_setSeparatorHeight:, nonatomic) double _separatorHeight;                          //@synthesize _separatorHeight=__separatorHeight - In the implementation block
@property (setter=_setSeparatorColor:, nonatomic, strong) NSColor *_separatorColor;                  //@synthesize _separatorColor=__separatorColor - In the implementation block
@property (nonatomic) long long style;                                                               //@synthesize style=_style - In the implementation block
@property (nonatomic, strong) UXView *backgroundView;                                                //@synthesize backgroundView=_backgroundView - In the implementation block
@property (nonatomic, strong) UXView *selectedBackgroundView;                                        //@synthesize selectedBackgroundView=_selectedBackgroundView - In the implementation block
@property (nonatomic) long long accessoryType;                                                       //@synthesize accessoryType=_accessoryType - In the implementation block
@property (nonatomic, strong) UXView *accessoryView;                                                 //@synthesize accessoryView=_accessoryView - In the implementation block
@property (nonatomic, strong) NSColor *highlightColor;                                               //@synthesize highlightColor=_highlightColor - In the implementation block
@property (nonatomic) long long selectionStyle;                                                      //@synthesize selectionStyle=_selectionStyle - In the implementation block
@property (nonatomic) long long indentationLevel;                                                    //@synthesize indentationLevel=_indentationLevel - In the implementation block
@property (nonatomic) double indentationWidth;                                                       //@synthesize indentationWidth=_indentationWidth - In the implementation block
@property (nonatomic) NSEdgeInsets separatorInset;                                                   //@synthesize separatorInset=_separatorInset - In the implementation block
- (void)prepareForReuse;
- (void)setAccessoryView:(id)arg1;
- (long long)style;
- (long long)indentationLevel;
- (void)setStyle:(long long)arg1;
- (id)_separatorColor;
- (void)setHighlighted:(BOOL)arg1;
- (id)accessibilityLabel;
- (id)accessoryView;
- (id)backgroundView;
- (id)highlightColor;
- (id)initWithFrame:(CGRect)arg1;
- (long long)selectionStyle;
- (void)setBackgroundView:(id)arg1;
- (void)setIndentationLevel:(long long)arg1;
- (void)setIndentationWidth:(double)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)setSelectionStyle:(long long)arg1;
- (void)updateConstraints;
- (void)viewDidMoveToWindow;
- (void)setHighlightColor:(id)arg1;
- (void)_updateTextColor;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)detailTextLabel;
- (NSEdgeInsets)separatorInset;
- (void)setDetailTextLabel:(id)arg1;
- (void)setTextLabel:(id)arg1;
- (id)textLabel;
- (long long)_separatorStyle;
- (double)_separatorHeight;
- (long long)accessoryType;
- (double)indentationWidth;
- (id)selectedBackgroundView;
- (void)setAccessoryType:(long long)arg1;
- (void)setSelectedBackgroundView:(id)arg1;
- (void)setSeparatorInset:(NSEdgeInsets)arg1;
- (id)_addedConstraints;
- (void)_configureInternalAccessoryViewForType:(long long)arg1;
- (long long)_detailTextAlignment;
- (BOOL)_highlightingForContext;
- (void)_setHighlightingForContext:(BOOL)arg1;
- (void)_setSeparatorColor:(id)arg1;
- (void)_setSeparatorHeight:(double)arg1;
- (void)_setSeparatorStyle:(long long)arg1;
- (id)defaultSelectedBackgroundView;
- (id)internalAccessoryView;
- (id)internalHighlightedBackgroundView;
- (id)lowerSpace;
- (void)set_addedConstraints:(id)arg1;
- (id)upperSpace;
@end

