/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import "UXCollectionViewFlowLayout.h"
@protocol UXCollectionViewDelegateFlowLayout;
@class NSMutableArray, NSMutableDictionary;

@interface UXTableLayout : UXCollectionViewFlowLayout {

	struct {
		unsigned delegateSupplementaryViewDidBeginFloating : 1;
		unsigned delegateSupplementaryViewDidEndFloating : 1;
		unsigned delegateRreferenceSizeForHeaderInSection : 1;
		unsigned delegateLayoutInsetForSectionAtIndex : 1;
		unsigned needsDelegateFlagsUpdate : 1;
		unsigned floatingHeadersDisabled : 1;
		unsigned preparingForUpdates : 1;
		unsigned showsSectionHeaderForSingleSection : 1;
		unsigned showsSectionFooterForSingleSection : 1;
	}  _tableLayoutFlags;
	NSMutableArray* _layoutAttributesArray;
	NSMutableDictionary* _headerAttributesByIndexPath;

}

@property (nonatomic, readonly) NSMutableArray *layoutAttributesArray;                                  //@synthesize layoutAttributesArray=_layoutAttributesArray - In the implementation block
@property (nonatomic, readonly) NSMutableDictionary *headerAttributesByIndexPath;                       //@synthesize headerAttributesByIndexPath=_headerAttributesByIndexPath - In the implementation block
@property (nonatomic, readonly) id<UXCollectionViewDelegateFlowLayout> delegateFlowLayout; 
@property (nonatomic) BOOL showsSectionHeaderForSingleSection; 
@property (nonatomic) BOOL showsSectionFooterForSingleSection; 
@property (nonatomic) BOOL floatingHeadersDisabled; 
- (id)init;
- (void)_setCollectionView:(id)arg1;
- (void)invalidateLayoutWithContext:(id)arg1;
- (id)invalidationContextForBoundsChange:(CGRect)arg1;
- (id)layoutAttributesForElementsInRect:(CGRect)arg1;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (void)prepareLayout;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1;
- (BOOL)_wantsHeaderForSection:(unsigned long long)arg1;
- (id<UXCollectionViewDelegateFlowLayout>)delegateFlowLayout;
- (BOOL)floatingHeadersDisabled;
- (id)headerAttributesByIndexPath;
- (NSEdgeInsets)insetForSection:(long long)arg1;
- (id)layoutAttributesArray;
- (void)setFloatingHeadersDisabled:(BOOL)arg1;
- (void)setShowsSectionFooterForSingleSection:(BOOL)arg1;
- (void)setShowsSectionHeaderForSingleSection:(BOOL)arg1;
- (BOOL)showsSectionFooterForSingleSection;
- (BOOL)showsSectionHeaderForSingleSection;
@end

