/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXViewControllerAnimatedTransitioning.h"
#import "UXViewControllerInteractiveTransitioning.h"

@class NSString;

@interface UXTransitionController : NSObject <UXViewControllerAnimatedTransitioning, UXViewControllerInteractiveTransitioning> {

	long long _operation;
	double _percentComplete;

}

@property (nonatomic) long long operation;                           //@synthesize operation=_operation - In the implementation block
@property (nonatomic, readonly) double percentComplete;              //@synthesize percentComplete=_percentComplete - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy, readonly) NSString *description; 
@property (copy, readonly) NSString *debugDescription; 
- (long long)operation;
- (void)setOperation:(long long)arg1;
- (double)percentComplete;
- (void)animateTransition:(id)arg1;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (void)startInteractiveTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (BOOL)navigationController:(id)arg1 shouldBeginInteractivePopFromViewController:(id)arg2 toViewController:(id)arg3;
- (void)updateInteractiveTransition:(double)arg1 inContext:(id)arg2;
@end

