/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSViewController.h>

@protocol UXLayoutSupport, UXNavigationDestination;
@class UXNavigationItem, UXTabBarItem, NSArray, UXView, UXNavigationController, UXTabBarController, UXWindowController, UXSourceController, NSView, NSResponder;

@interface UXViewController : NSViewController {

	UXNavigationItem* _navigationItem;
	UXTabBarItem* _tabBarItem;
	UXViewController* _accessoryViewController;
	NSArray* _accessoryBarItems;
	UXViewController* _toolbarViewController;
	NSArray* _toolbarItems;
	NSArray* _subtoolbarItems;
	BOOL _hidesBottomBarWhenPushed;
	CGSize _ux_preferredContentSize;
	BOOL _viewDidLoad;
	BOOL _ignoreViewController;
	id<UXLayoutSupport> _topLayoutGuide;
	id<UXLayoutSupport> _bottomLayoutGuide;
	BOOL _transitioningIntoFullScreen;
	BOOL _transitioningOutOfFullScreen;
	BOOL _isEditing;
	BOOL _automaticallyAdjustsScrollViewInsets;
	long long _modalPresentationStyle;
	unsigned long long _edgesForExtendedLayout;
	UXView* _presentedViewControllerContainerView;
	double _preferredToolbarHeight;
	double _preferredToolbarBaselineOffsetFromBottom;
	long long _preferredSubtoolbarPosition;
	double _preferredSubtoolbarHeight;
	double _preferredSubtoolbarBaselineOffsetFromBottom;
	long long _preferredToolbarStyle;
	CGRect _preferredInitialFrame;
	NSEdgeInsets _preferredToolbarDecorationInsets;

}

@property (nonatomic, readonly) UXNavigationController *navigationController; 
@property (nonatomic, readonly) UXNavigationItem *navigationItem; 
@property (nonatomic) BOOL hidesBottomBarWhenPushed; 
@property (nonatomic, strong) UXTabBarItem *tabBarItem; 
@property (nonatomic, weak, readonly) UXTabBarController *tabBarController; 
@property (nonatomic, readonly) UXWindowController *windowController; 
@property (nonatomic, readonly) long long interfaceOrientation; 
@property (nonatomic, readonly) UXSourceController *sourceController; 
@property (nonatomic) BOOL hidesSourceListWhenPushed; 
@property (nonatomic, readonly) id<UXNavigationDestination> navigationDestination; 
@property (nonatomic) BOOL isEditing;                                                                                  //@synthesize isEditing=_isEditing - In the implementation block
@property (nonatomic, strong) UXView *presentedViewControllerContainerView;                                            //@synthesize presentedViewControllerContainerView=_presentedViewControllerContainerView - In the implementation block
@property (nonatomic) double preferredToolbarHeight;                                                                   //@synthesize preferredToolbarHeight=_preferredToolbarHeight - In the implementation block
@property (nonatomic) double preferredToolbarBaselineOffsetFromBottom;                                                 //@synthesize preferredToolbarBaselineOffsetFromBottom=_preferredToolbarBaselineOffsetFromBottom - In the implementation block
@property (nonatomic) long long preferredSubtoolbarPosition;                                                           //@synthesize preferredSubtoolbarPosition=_preferredSubtoolbarPosition - In the implementation block
@property (nonatomic) double preferredSubtoolbarHeight;                                                                //@synthesize preferredSubtoolbarHeight=_preferredSubtoolbarHeight - In the implementation block
@property (nonatomic) double preferredSubtoolbarBaselineOffsetFromBottom;                                              //@synthesize preferredSubtoolbarBaselineOffsetFromBottom=_preferredSubtoolbarBaselineOffsetFromBottom - In the implementation block
@property (nonatomic) long long preferredToolbarStyle;                                                                 //@synthesize preferredToolbarStyle=_preferredToolbarStyle - In the implementation block
@property (nonatomic) NSEdgeInsets preferredToolbarDecorationInsets;                                                   //@synthesize preferredToolbarDecorationInsets=_preferredToolbarDecorationInsets - In the implementation block
@property (nonatomic, readonly) UXViewController *ux_parentViewController; 
@property (nonatomic, readonly) UXViewController *ux_presentingViewController; 
@property (nonatomic, readonly) UXViewController *contentRepresentingViewController; 
@property (nonatomic, readonly) UXView *uxView; 
@property (nonatomic, readonly) NSView *viewIfLoaded; 
@property (nonatomic, readonly) NSResponder *preferredFirstResponder; 
@property (nonatomic, readonly) UXViewController *presentedViewController; 
@property  CGSize preferredContentSize; 
@property (nonatomic) CGRect preferredInitialFrame;                                                                    //@synthesize preferredInitialFrame=_preferredInitialFrame - In the implementation block
@property (getter=isWindowInFullScreen, nonatomic, readonly) BOOL windowInFullScreen; 
@property (getter=isWindowConsideredInFullScreen, nonatomic, readonly) BOOL windowConsideredInFullScreen; 
@property (nonatomic, readonly) BOOL prefersSidebarAndToolbarHiddenInFullscreenWindowMode; 
@property (nonatomic, readonly) BOOL delegatesSidebarAndToolbarFullscreenVisibilityManagement; 
@property (nonatomic) long long modalPresentationStyle;                                                                //@synthesize modalPresentationStyle=_modalPresentationStyle - In the implementation block
@property (nonatomic) unsigned long long edgesForExtendedLayout;                                                       //@synthesize edgesForExtendedLayout=_edgesForExtendedLayout - In the implementation block
@property (nonatomic) BOOL automaticallyAdjustsScrollViewInsets;                                                       //@synthesize automaticallyAdjustsScrollViewInsets=_automaticallyAdjustsScrollViewInsets - In the implementation block
+ (Class)viewClass;
+ (double)defaultToolbarHeight;
+ (id)toolbarPropertyNames;
- (id)description;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setPreferredContentSize:(CGSize)arg1;
- (void)setView:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)_sendViewDidLoad;
- (BOOL)acceptsFirstResponder;
- (id)accessoryViewController;
- (void)addChildViewController:(id)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (BOOL)isEditing;
- (void)loadView;
- (id)menuForEvent:(id)arg1;
- (CGSize)preferredContentSize;
- (void)removeChildViewControllerAtIndex:(long long)arg1;
- (void)removeFromParentViewController;
- (void)setAccessoryViewController:(id)arg1;
- (void)setTabBarItem:(id)arg1;
- (id)sourceController;
- (id)tabBarItem;
- (void)updateViewConstraints;
- (void)viewDidAppear;
- (void)viewDidDisappear;
- (id)viewIfLoaded;
- (void)viewWillAppear;
- (void)viewWillDisappear;
- (id)windowController;
- (id<UXNavigationDestination>)navigationDestination;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillLayoutSubviews;
- (long long)interfaceOrientation;
- (id)navigationController;
- (id)navigationItem;
- (id)toolbarViewController;
- (void)setIsEditing:(BOOL)arg1;
- (long long)modalPresentationStyle;
- (void)setModalPresentationStyle:(long long)arg1;
- (void)setToolbarViewController:(id)arg1;
- (void)dismissViewControllerAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2;
- (id)presentedViewController;
- (id)transitionCoordinator;
- (BOOL)automaticallyAdjustsScrollViewInsets;
- (id)bottomLayoutGuide;
- (unsigned long long)edgesForExtendedLayout;
- (BOOL)hidesBottomBarWhenPushed;
- (id)popoverController;
- (id)preferredFirstResponder;
- (void)presentViewController:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3;
- (void)setAutomaticallyAdjustsScrollViewInsets:(BOOL)arg1;
- (void)setEdgesForExtendedLayout:(unsigned long long)arg1;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setHidesBottomBarWhenPushed:(BOOL)arg1;
- (void)setToolbarItems:(id)arg1;
- (void)setToolbarItems:(id)arg1 animated:(BOOL)arg2;
- (id)tabBarController;
- (id)toolbarItems;
- (id)topLayoutGuide;
- (void)_animateView:(id)arg1 fromFrame:(CGRect)arg2 toFrame:(CGRect)arg3;
- (void)_didExitFullScreenNotification:(id)arg1;
- (void)invalidateIntrinsicLayoutInsets;
- (id)subtoolbarItems;
- (id)_ancestorViewControllerOfClass:(Class)arg1;
- (void)setPreferredSubtoolbarPosition:(long long)arg1;
- (void)setShouldAnimateToolbarsChanges;
- (void)viewUpdateLayer;
- (void)windowDidRecalculateKeyViewLoop;
- (CGRect)_defaultInitialFrame;
- (void)_didEnterFullScreenNotification:(id)arg1;
- (void)_loadViewIfNotLoaded;
- (void)_prepareForAnimationInContext:(id)arg1 completion:(/*^block*/id)arg2;
- (BOOL)_requiresWindowForTransitionPreparation;
- (void)_setupLayoutGuidesForView:(id)arg1;
- (void)_startObservingFullScreenNotifications;
- (void)_stopObservingFullScreenNotifications;
- (void)_willEnterFullScreenNotification:(id)arg1;
- (void)_willExitFullScreenNotification:(id)arg1;
- (id)accessoryBarItems;
- (BOOL)canProvideViewControllersForNavigationDestination:(id)arg1;
- (id)contentRepresentingViewController;
- (void)contentRepresentingViewControllerDidChange;
- (BOOL)delegatesSidebarAndToolbarFullscreenVisibilityManagement;
- (void)didUpdateLayoutGuides;
- (BOOL)hidesSourceListWhenPushed;
- (NSEdgeInsets)intrinsicLayoutInsets;
- (BOOL)isTransitory;
- (BOOL)isWindowConsideredInFullScreen;
- (BOOL)isWindowInFullScreen;
- (void)performActionForSelectingCurrentTabBarItemSegment;
- (void)performToolbarsChanges:(/*^block*/id)arg1;
- (CGSize)preferredContentSizeCappedToSize:(CGSize)arg1;
- (CGRect)preferredInitialFrame;
- (double)preferredSubtoolbarBaselineOffsetFromBottom;
- (double)preferredSubtoolbarHeight;
- (long long)preferredSubtoolbarPosition;
- (id)preferredTabBarItemSegmentForNavigationDestination:(id)arg1;
- (double)preferredToolbarBaselineOffsetFromBottom;
- (NSEdgeInsets)preferredToolbarDecorationInsets;
- (double)preferredToolbarHeight;
- (long long)preferredToolbarPosition;
- (long long)preferredToolbarStyle;
- (BOOL)prefersSidebarAndToolbarHiddenInFullscreenWindowMode;
- (void)prepareForTransitionToSelectedTabBarItemSegmentWithCompletion:(/*^block*/id)arg1;
- (void)prepareForTransitionWithContext:(id)arg1 completion:(/*^block*/id)arg2;
- (id)presentedViewControllerContainerView;
- (void)requestViewControllersForNavigationDestination:(id)arg1 completion:(/*^block*/id)arg2;
- (void)setAccessoryBarItems:(id)arg1;
- (void)setHidesSourceListWhenPushed:(BOOL)arg1;
- (void)setPreferredInitialFrame:(CGRect)arg1;
- (void)setPreferredSubtoolbarBaselineOffsetFromBottom:(double)arg1;
- (void)setPreferredSubtoolbarHeight:(double)arg1;
- (void)setPreferredToolbarBaselineOffsetFromBottom:(double)arg1;
- (void)setPreferredToolbarDecorationInsets:(NSEdgeInsets)arg1;
- (void)setPreferredToolbarHeight:(double)arg1;
- (void)setPreferredToolbarStyle:(long long)arg1;
- (void)setPresentedViewControllerContainerView:(id)arg1;
- (void)setSubtoolbarItems:(id)arg1;
- (void)setTransitory:(BOOL)arg1;
- (void)updateFirstResponderIfNeeded;
- (void)updateForEqualNavigationDestination:(id)arg1;
- (id)uxView;
- (id)ux_parentViewController;
- (id)ux_presentingViewController;
- (void)viewDidLiveResize;
- (void)viewWillLiveResize;
- (void)willEncodeNavigationDestination:(id)arg1;
- (void)windowDidEnterFullScreen;
- (void)windowDidExitFullScreen;
- (void)windowWillEnterFullScreen;
- (void)windowWillExitFullScreen;
- (void)windowWillRecalculateKeyViewLoop;
@end

