/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSView.h>

@class NSColor, NSVisualEffectView, UXViewController;

@interface UXView : NSView {

	BOOL _blurEnabled;
	long long _blurMaterial;
	NSColor* _backgroundColor;
	NSColor* _borderColor;
	NSVisualEffectView* _contentBackgroundVisualEffectsView;
	BOOL _opaque;
	BOOL _exclusiveTouch;
	BOOL _userInteractionEnabled;
	BOOL _needsContentBackgroundVisualEffect;
	BOOL _accessibilityChildrenHidden;
	UXViewController* _viewControllerProxy;
	NSVisualEffectView* __visualEffectsView;

}

@property (nonatomic, weak) UXViewController *viewControllerProxy;                            //@synthesize viewControllerProxy=_viewControllerProxy - In the implementation block
@property (readonly) NSVisualEffectView *_visualEffectsView;                                  //@synthesize _visualEffectsView=__visualEffectsView - In the implementation block
@property (nonatomic) BOOL accessibilityChildrenHidden;                                       //@synthesize accessibilityChildrenHidden=_accessibilityChildrenHidden - In the implementation block
@property (nonatomic) long long contentMode; 
@property (nonatomic, readonly) CGPoint center; 
@property (nonatomic) CGAffineTransform transform; 
@property  BOOL clipsToBounds; 
@property (getter=isExclusiveTouch, nonatomic) BOOL exclusiveTouch;                           //@synthesize exclusiveTouch=_exclusiveTouch - In the implementation block
@property (getter=isOpaque) BOOL opaque;                                                      //@synthesize opaque=_opaque - In the implementation block
@property (nonatomic, readonly) long long effectiveUserInterfaceLayoutDirection; 
@property (nonatomic) BOOL userInteractionEnabled;                                            //@synthesize userInteractionEnabled=_userInteractionEnabled - In the implementation block
@property (nonatomic, strong) NSColor *borderColor;                                           //@synthesize borderColor=_borderColor - In the implementation block
@property (nonatomic) BOOL needsContentBackgroundVisualEffect;                                //@synthesize needsContentBackgroundVisualEffect=_needsContentBackgroundVisualEffect - In the implementation block
+ (void)animateWithDuration:(double)arg1 animations:(/*^block*/id)arg2;
+ (void)animateWithDuration:(double)arg1 animations:(/*^block*/id)arg2 completion:(/*^block*/id)arg3;
+ (void)animateWithDuration:(double)arg1 delay:(double)arg2 options:(unsigned long long)arg3 animations:(/*^block*/id)arg4 completion:(/*^block*/id)arg5;
+ (void)performWithoutAnimation:(/*^block*/id)arg1;
+ (Class)layerClass;
+ (void)_animateUsingDefaultTimingWithOptions:(unsigned long long)arg1 animations:(/*^block*/id)arg2 completion:(/*^block*/id)arg3;
+ (void)animateWithDuration:(double)arg1 delay:(double)arg2 usingSpringWithDamping:(double)arg3 initialSpringVelocity:(double)arg4 options:(unsigned long long)arg5 animations:(/*^block*/id)arg6 completion:(/*^block*/id)arg7;
+ (id)defaultSpringAnimationForKey:(id)arg1 mass:(double)arg2 stiffness:(double)arg3 damping:(double)arg4 velocity:(double)arg5;
+ (long long)_contentModeForLayerContentsGravity:(id)arg1;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)layout;
- (CGAffineTransform)transform;
- (id)accessibilityChildren;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (void)addSubview:(id)arg1;
- (void)addSubview:(id)arg1 positioned:(long long)arg2 relativeTo:(id)arg3;
- (CGPoint)center;
- (BOOL)isOpaque;
- (id)recursiveDescription;
- (void)setBackgroundColor:(id)arg1;
- (void)setOpaque:(BOOL)arg1;
- (void)setTransform:(CGAffineTransform)arg1;
- (CGSize)sizeThatFits:(CGSize)arg1;
- (void)updateConstraintsForSubtreeIfNeeded;
- (void)updateLayer;
- (void)viewDidEndLiveResize;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)viewWillStartLiveResize;
- (BOOL)wantsUpdateLayer;
- (void)setContentMode:(long long)arg1;
- (long long)contentMode;
- (void)setUserInteractionEnabled:(BOOL)arg1;
- (BOOL)userInteractionEnabled;
- (long long)effectiveUserInterfaceLayoutDirection;
- (void)bringSubviewToFront:(id)arg1;
- (void)sendSubviewToBack:(id)arg1;
- (id)snapshotView;
- (void)setBlurEnabled:(BOOL)arg1;
- (id)_autoresizingDescription;
- (id)_superDescription;
- (void)insertSubview:(id)arg1 aboveSubview:(id)arg2;
- (void)insertSubview:(id)arg1 belowSubview:(id)arg2;
- (BOOL)isExclusiveTouch;
- (void)setExclusiveTouch:(BOOL)arg1;
- (BOOL)blurEnabled;
- (void)_disableBlur;
- (void)_enableBlur;
- (void)setAccessibilityChildrenHidden:(BOOL)arg1;
- (void)_applyTintColorIfNotUXView:(id)arg1;
- (id)_infoForWindow;
- (id)_infoWithChildren;
- (id)_infoWithParents;
- (id)_makeContentBackgroundVisualEffectsView;
- (void)_updateContentBackgroundVisualEffectsView;
- (id)_visualEffectsView;
- (BOOL)accessibilityChildrenHidden;
- (BOOL)needsContentBackgroundVisualEffect;
- (void)setBlurMaterial:(long long)arg1;
- (void)setNeedsContentBackgroundVisualEffect:(BOOL)arg1;
- (id)snapshotForRect:(CGRect)arg1;
- (id)snapshotViewFromRect:(CGRect)arg1;
@end

