/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

@protocol UXViewControllerTransitionCoordinatorContext <NSObject>
@end
@protocol UXViewControllerTransitionCoordinator <UXViewControllerTransitionCoordinatorContext>
@required
-(BOOL)animateAlongsideTransition:(/*^block*/id)arg1 completion:(/*^block*/id)arg2;
-(BOOL)animateAlongsideTransitionInView:(id)arg1 animation:(/*^block*/id)arg2 completion:(/*^block*/id)arg3;
-(void)notifyWhenInteractionEndsUsingBlock:(/*^block*/id)arg1;

@end

