/*
    * This header is generated by classdump-dyld 1.0
    * on Friday, February 2, 2024 at 1:02:18 AM China Standard Time
    * Operating System: Version 14.2.1 (Build 23C71)
    * Image Source: /System/Library/PrivateFrameworks/UXKit.framework/Versions/A/UXKit
    * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
    */

#import "UXKit-Structs.h"
#import <AppKit/NSWindowController.h>
#import "_UXAccessoryBarContainer.h"
#import <Cocoa/Cocoa.h>

@class NSTitlebarAccessoryViewController, UXToolbar, UXWindowToolbarController, NSToolbarItem, UXNavigationItem, UXViewController, NSString;

@interface UXWindowController : NSWindowController <NSToolbarDelegate, _UXAccessoryBarContainer, NSWindowDelegate> {

	NSTitlebarAccessoryViewController* _titlebarAccessoryViewController;
	UXToolbar* _currentAccessoryToolbar;
	UXWindowToolbarController* _toolbarController;
	NSToolbarItem* _navigationBarToolbarItem;
	UXNavigationItem* _toolbarNavigationItem;

}

@property (weak) NSToolbarItem *navigationBarToolbarItem;                                                        //@synthesize navigationBarToolbarItem=_navigationBarToolbarItem - In the implementation block
@property (nonatomic, readonly) NSTitlebarAccessoryViewController *titlebarAccessoryViewController; 
@property (nonatomic, strong) UXNavigationItem *toolbarNavigationItem;                                           //@synthesize toolbarNavigationItem=_toolbarNavigationItem - In the implementation block
@property (nonatomic, strong) UXViewController *rootViewController; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy, readonly) NSString *description; 
@property (copy, readonly) NSString *debugDescription; 
@property (nonatomic, readonly) double _accessoryBarHeight; 
+ (id)defaultWindow;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)initWithWindow:(id)arg1;
- (void)_updateToolbar;
- (void)setWindow:(id)arg1;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (CGRect)window:(id)arg1 willPositionSheet:(id)arg2 usingRect:(CGRect)arg3;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)windowWillExitFullScreen:(id)arg1;
- (id)initWithRootViewController:(id)arg1;
- (id)rootViewController;
- (void)setRootViewController:(id)arg1;
- (void)_popoverWillShow:(id)arg1;
- (void)_updateToolbarItems;
- (void)_updateNavigationBarToolbarItem;
- (void)teardownViewControllerHierarchy;
- (id)titlebarAccessoryViewController;
- (double)_accessoryBarHeight;
- (void)_setAccessoryBarHidden:(BOOL)arg1;
- (void)_setupAccessoryBar;
- (void)_setupNavigationBarToolbarItem;
- (BOOL)_shouldUseToolbarViewForCentering;
- (void)_tearDownViewControllerHierarchyForViewController:(id)arg1;
- (void)_updateAccessoryBar;
- (void)_updateFirstResponder;
- (void)_updateToolbarNavigationItem;
- (id)navigationBarToolbarItem;
- (id)rootNavigationController;
- (void)setNavigationBarToolbarItem:(id)arg1;
- (void)setToolbarNavigationItem:(id)arg1;
- (id)toolbarNavigationItem;
- (void)windowDidBecomeFirstResponder:(id)arg1;
- (void)windowDidRecalculateKeyViewLoop:(id)arg1;
- (void)windowWillRecalculateKeyViewLoop:(id)arg1;
@end

