ln -s ../../Commons/Public/UXBase.h UXBase.h
ln -s ../../Commons/Public/UXKitDefines.h UXKitDefines.h
ln -s ../../Components/Public/UXView.h UXView.h
ln -s ../../Components/Public/UXViewController.h UXViewController.h
ln -s ../../Components/Public/UXBar.h UXBar.h
ln -s ../../Components/Public/UXToolbar.h UXToolbar.h
ln -s ../../Components/Public/UXBarItem.h UXBarItem.h
ln -s ../../Components/Public/UXBarButtonItem.h UXBarButtonItem.h
ln -s ../../Components/Public/UXNavigationBar.h UXNavigationBar.h
ln -s ../../Components/Public/UXNavigationController.h UXNavigationController.h
ln -s ../../Components/Public/UXNavigationItem.h UXNavigationItem.h
ln -s ../../Components/Public/UXLabel.h UXLabel.h
ln -s ../../Components/Public/UXImageView.h UXImageView.h
ln -s ../../Protocols/Public/UXKitAppearance.h UXKitAppearance.h
ln -s ../../Protocols/Public/UXViewControllerTransitionCoordinator.h UXViewControllerTransitionCoordinator.h
ln -s ../../Protocols/Public/UXViewControllerTransitioning.h UXViewControllerTransitioning.h
ln -s ../../Protocols/Public/UXBarCommon.h UXBarCommon.h
ln -s ../../Protocols/Public/UXLayoutSupport.h UXLayoutSupport.h
ln -s ../../Categories/Public/NSImage+UXKit.h NSImage+UXKit.h
ln -s ../../Categories/Public/NSResponder+UXKit.h NSResponder+UXKit.h
ln -s ../../Categories/Public/NSView+UXKit.h NSView+UXKit.h
ln -s ../../Categories/Public/NSViewController+UXViewController.h NSViewController+UXViewController.h
ln -s ../../Categories/Public/NSWindow+UXKit.h NSWindow+UXKit.h
