//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

typedef NS_OPTIONS(NSUInteger, UXControlState) {
    UXControlStateNormal       = 0,
    UXControlStateHighlighted  = 1 << 0,                  // used when UIControl isHighlighted is set
    UXControlStateDisabled     = 1 << 1,
    UXControlStateSelected     = 1 << 2,                  // flag usable by app (see below)
    UXControlStateFocused      = 1 << 3,                  // Applicable only when the screen supports focus
    UXControlStateApplication  = 0x00FF0000,              // additional flags available for application use
    UXControlStateReserved     = 0xFF000000               // flags reserved for internal framework use
};


@interface _UXButton : NSButton
{
    NSMutableDictionary *_titlesByState;	// 112 = 0x70
    NSMutableDictionary *_titleAttributesByState;	// 120 = 0x78
}

- (NSColor *)_textColorForState:(UXControlState)state;
- (NSAttributedString *)_attributedStringForState:(UXControlState)state;
- (void)tintColorDidChange;
- (void)setTitleAttributes:(NSDictionary<NSAttributedStringKey, id> *)titleAttributes forState:(UXControlState)state;
- (void)setTitle:(NSString *)title forState:(UXControlState)state;

@end

