//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSButton.h>

@class NSMutableDictionary;

@interface _UXButton : NSButton
{
    NSMutableDictionary *_titlesByState;	// 112 = 0x70
    NSMutableDictionary *_titleAttributesByState;	// 120 = 0x78
}

+ (Class)cellClass;

- (BOOL)accessibilityPerformPress;
- (id)accessibilityLabel;
- (id)_textColorForState:(NSUInteger)arg1;
- (id)_attributedStringForState:(NSUInteger)arg1;
- (void)setTitle:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)tintColorDidChange;
- (void)setTitleAttributes:(id)arg1 forState:(NSUInteger)arg2;
- (void)setTitle:(id)arg1 forState:(NSUInteger)arg2;
- (id)initWithFrame:(CGRect)arg1;

@end

