//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface _UXCollectionDocumentView
{
    BOOL _overdrawEnabled;	// 108 = 0x6c
}

@property(nonatomic) BOOL overdrawEnabled; // @synthesize overdrawEnabled=_overdrawEnabled;
- (void)prepareContentInRect:(CGRect)arg1;

@end

