//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSButton, NSMutableArray, NSProgressIndicator, NSString, NSTextField, UXView;

@interface _UXContentUnavailableView
{
    BOOL _showProgress;	// 108 = 0x6c
    NSString *_title;	// 112 = 0x70
    NSString *_message;	// 120 = 0x78
    NSString *_buttonTitle;	// 128 = 0x80
    NSButton *_actionButton;	// 136 = 0x88
    id _buttonAction;	// 144 = 0x90
    NSProgressIndicator *_progressIndicator;	// 152 = 0x98
    NSUInteger _progressIndicatorStyle;	// 160 = 0xa0
    NSUInteger _vibrantOptions;	// 168 = 0xa8
    UXView *_containerView;	// 176 = 0xb0
    NSTextField *_titleLabel;	// 184 = 0xb8
    NSTextField *_messageLabel;	// 192 = 0xc0
    NSMutableArray *_containerViewContraints;	// 200 = 0xc8
}


@property(retain, nonatomic) NSMutableArray *containerViewContraints; // @synthesize containerViewContraints=_containerViewContraints;
@property(retain, nonatomic) NSTextField *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UXView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) NSUInteger vibrantOptions; // @synthesize vibrantOptions=_vibrantOptions;
@property(nonatomic) NSUInteger progressIndicatorStyle; // @synthesize progressIndicatorStyle=_progressIndicatorStyle;
@property(retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(nonatomic) BOOL showProgress; // @synthesize showProgress=_showProgress;
@property(copy, nonatomic) id buttonAction; // @synthesize buttonAction=_buttonAction;
@property(retain, nonatomic) NSButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void)layout;
- (void)_updateProgressLayout;
- (void)updateConstraints;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;
- (void)_updateTextField:(id)arg1 withAttributedText:(id)arg2;
- (id)_textFieldWithFontSize:(double)arg1;
- (void)_actionButtonPressed:(id)arg1;
- (id)placeholderMessageTextAttributes;
- (id)placeholderTitleTextAttributes;
- (id)_buttonTitleAttributes;
- (double)_buttonAlpha;
- (double)_labelAlpha;
- (id)_tintColor;
- (id)_textColor;
- (id)_vibrantBaseColor;
- (BOOL)_hasVibrantButton;
- (BOOL)_hasVibrantText;

@end

