//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class _UXFlowLayoutRow, _UXFlowLayoutSection;

@interface _UXFlowLayoutItem : NSObject
{
    CGRect _itemFrame;	// 8 = 0x8
    _UXFlowLayoutSection *_section;	// 40 = 0x28
    _UXFlowLayoutRow *_rowObject;	// 48 = 0x30
}

@property(nonatomic) CGRect itemFrame; // @synthesize itemFrame=_itemFrame;
@property(nonatomic) _UXFlowLayoutRow *rowObject; // @synthesize rowObject=_rowObject;
@property(nonatomic) _UXFlowLayoutSection *section; // @synthesize section=_section;
- (id)copy;

@end

