//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSLayoutGuide.h>

#import "UXLayoutSupport-Protocol.h"

@class NSLayoutConstraint, NSLayoutDimension, NSLayoutYAxisAnchor, NSString;

@interface _UXLayoutSpacer : NSLayoutGuide <UXLayoutSupport>

+ (instancetype)_horizontalLayoutSpacer;
+ (instancetype)_verticalLayoutSpacer;

@property (nonatomic, copy) id lengthUpdateBlock; // @synthesize lengthUpdateBlock=_lengthUpdateBlock;
@property (nonatomic) BOOL horizontal; // @synthesize horizontal=_horizontal;
- (void)_activate;
- (void)_setUpDimensionConstraintWithLength:(CGFloat)arg1;
- (void)_setUpCounterDimensionConstraint;


@end
