//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSLayoutGuide.h>

#import "UXLayoutSupport-Protocol.h"

@class NSLayoutConstraint, NSLayoutDimension, NSLayoutYAxisAnchor, NSString;

@interface _UXLayoutSpacer : NSLayoutGuide <UXLayoutSupport>
{
    NSLayoutConstraint *_counterDimensionConstraint;	// 8 = 0x8
    NSLayoutConstraint *_dimensionConstraint;	// 16 = 0x10
    BOOL _horizontal;	// 24 = 0x18
    id _lengthUpdateBlock;	// 32 = 0x20
}

+ (instancetype)_horizontalLayoutSpacer;
+ (instancetype)_verticalLayoutSpacer;

@property(copy, nonatomic) id lengthUpdateBlock; // @synthesize lengthUpdateBlock=_lengthUpdateBlock;
@property(nonatomic) BOOL horizontal; // @synthesize horizontal=_horizontal;
- (void)_activate;
- (void)_setUpDimensionConstraintWithLength:(double)arg1;
- (void)_setUpCounterDimensionConstraint;


@end

