//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "AppKit/AppKit.h"
#import "UXNavigationControllerOperation.h"

@class UXViewController;

@interface _UXNavigationRequest : NSObject

@property (nonatomic, readonly) NSArray<UXViewController *> *viewControllers;
@property (nonatomic, readonly) UXViewController *viewController;
@property (nonatomic, readonly) UXNavigationControllerOperation operation;
@property (nonatomic, readonly) BOOL animated;

+ (_UXNavigationRequest *)setRequestWithViewControllers:(NSArray<UXViewController *> *)viewControllers animated:(BOOL)animated;
+ (_UXNavigationRequest *)popRequestWithViewController:(UXViewController *)viewController animated:(BOOL)animated;
+ (_UXNavigationRequest *)pushRequestWithViewController:(UXViewController *)viewController animated:(BOOL)animated;
+ (_UXNavigationRequest *)_requestWithOperation:(UXNavigationControllerOperation)operation viewControllers:(NSArray<UXViewController *> *)viewControllers animated:(BOOL)animated;
- (BOOL)isEqualToNavigationRequest:(_UXNavigationRequest *)request;
- (void)tearDownContainmentIfNeeded;
- (void)setupContainmentIfNeededInParentViewController:(UXViewController *)parentViewController;

@end
