//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "_UXBarItemsContainer-Protocol.h"

@class NSLayoutConstraint, NSMutableArray, NSMutableDictionary, NSString, NSView, UXImageView, UXNavigationBar, UXNavigationItem;

@interface _UXNavigationItemContainerView <_UXBarItemsContainer>
{
    UXImageView *_snaphotView;	// 112 = 0x70
    BOOL _hidesGlobalTrailingView;	// 120 = 0x78
    UXNavigationItem *_item;	// 128 = 0x80
    UXNavigationBar *_navigationBar;	// 136 = 0x88
    NSUInteger _state;	// 144 = 0x90
    double _minimumWidthForExpandedTitle;	// 152 = 0x98
    double _minimumWidthForExpandedItems;	// 160 = 0xa0
    NSView *_leftView;	// 168 = 0xa8
    NSMutableArray *_leftItemViews;	// 176 = 0xb0
    NSView *_titleView;	// 184 = 0xb8
    NSMutableArray *_rightItemViews;	// 192 = 0xc0
    NSView *_rightView;	// 200 = 0xc8
    NSMutableArray *_itemsSortedByPriority;	// 208 = 0xd0
    NSMutableDictionary *_overflowItemsByMinimumWidth;	// 216 = 0xd8
    NSMutableArray *_addedConstraints;	// 224 = 0xe0
    NSLayoutConstraint *_titleCenteringConstraint;	// 232 = 0xe8
    NSView *_titleCenteringConstrainedTitleView;	// 240 = 0xf0
    NSView *_titleCenteringTrackedView;	// 248 = 0xf8
    NSView *_titleCenteringConstraintOwnerView;	// 256 = 0x100
}

+ (id)layoutContainerForItem:(id)arg1 navigationBar:(id)arg2;

@property(nonatomic) __weak NSView *titleCenteringConstraintOwnerView; // @synthesize titleCenteringConstraintOwnerView=_titleCenteringConstraintOwnerView;
@property(nonatomic) __weak NSView *titleCenteringTrackedView; // @synthesize titleCenteringTrackedView=_titleCenteringTrackedView;
@property(nonatomic) __weak NSView *titleCenteringConstrainedTitleView; // @synthesize titleCenteringConstrainedTitleView=_titleCenteringConstrainedTitleView;
@property(retain, nonatomic) NSLayoutConstraint *titleCenteringConstraint; // @synthesize titleCenteringConstraint=_titleCenteringConstraint;
@property(retain, nonatomic) NSMutableArray *addedConstraints; // @synthesize addedConstraints=_addedConstraints;
@property(retain, nonatomic) NSMutableDictionary *overflowItemsByMinimumWidth; // @synthesize overflowItemsByMinimumWidth=_overflowItemsByMinimumWidth;
@property(retain, nonatomic) NSMutableArray *itemsSortedByPriority; // @synthesize itemsSortedByPriority=_itemsSortedByPriority;
@property(retain, nonatomic) NSView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) NSMutableArray *rightItemViews; // @synthesize rightItemViews=_rightItemViews;
@property(retain, nonatomic) NSView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) NSMutableArray *leftItemViews; // @synthesize leftItemViews=_leftItemViews;
@property(retain, nonatomic) NSView *leftView; // @synthesize leftView=_leftView;
@property(nonatomic) double minimumWidthForExpandedItems; // @synthesize minimumWidthForExpandedItems=_minimumWidthForExpandedItems;
@property(nonatomic) double minimumWidthForExpandedTitle; // @synthesize minimumWidthForExpandedTitle=_minimumWidthForExpandedTitle;
@property(nonatomic) NSUInteger state; // @synthesize state=_state;
@property(readonly, nonatomic) __weak UXNavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(readonly, nonatomic) UXNavigationItem *item; // @synthesize item=_item;
- (void)_updateItemsViews:(id)arg1 withNewViews:(id)arg2;
- (void)setTitleCenteringTrackedView:(id)arg1 updateConstraints:(BOOL)arg2;
- (void)layout;
- (void)updateConstraints;
- (id)hitTest:(CGPoint)arg1;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (id)subviewsIntersectedWithViews:(id)arg1 excludingHidden:(BOOL)arg2;
- (void)updateRightItemViewsAnimated:(BOOL)arg1;
- (void)updateLeftItemViewsAnimated:(BOOL)arg1;
- (void)_updateItemViews;
- (void)_updateItemsSortedByPriority;
- (void)_updateTitleView;
@property(readonly, nonatomic) BOOL hidesGlobalTrailingView; // @synthesize hidesGlobalTrailingView=_hidesGlobalTrailingView;
- (void)cancelTransistion;
- (void)prepareForTransition;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

