//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, UXViewController;

@interface _UXNavigationRequest : NSObject


+ (_UXNavigationRequest *)setRequestWithViewControllers:(NSArray<UXViewController *> *)viewControllers animated:(BOOL)animated;
+ (_UXNavigationRequest *)popRequestWithViewController:(UXViewController *)viewController animated:(BOOL)animated;
+ (_UXNavigationRequest *)pushRequestWithViewController:(UXViewController *)viewController animated:(BOOL)animated;
+ (_UXNavigationRequest *)_requestWithOperation:(NSInteger)operation viewControllers:(NSArray<UXViewController *> *)viewControllers animated:(BOOL)animated;

@property(readonly, nonatomic) BOOL animated; // @synthesize animated=_animated;
@property(readonly, nonatomic) NSArray<UXViewController *> *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(readonly, nonatomic) NSInteger operation; // @synthesize operation=_operation;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToNavigationRequest:(id)arg1;
- (id)description;
- (void)tearDownContainmentIfNeeded;
- (void)setupContainmentIfNeededInParentViewController:(id)arg1;
@property(readonly, nonatomic) UXViewController *viewController;

@end

