//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSImage.h>

@interface _UXResizableImage : NSImage
{
    NSImage *_topLeftCorner;	// 8 = 0x8
    NSImage *_topEdgeFill;	// 16 = 0x10
    NSImage *_topRightCorner;	// 24 = 0x18
    NSImage *_leftEdgeFill;	// 32 = 0x20
    NSImage *_centerFill;	// 40 = 0x28
    NSImage *_rightEdgeFill;	// 48 = 0x30
    NSImage *_bottomLeftCorner;	// 56 = 0x38
    NSImage *_bottomEdgeFill;	// 64 = 0x40
    NSImage *_bottomRightCorner;	// 72 = 0x48
    double _scale;	// 80 = 0x50
    BOOL _alwaysStretches;	// 88 = 0x58
}


@property(nonatomic) BOOL alwaysStretches; // @synthesize alwaysStretches=_alwaysStretches;
- (CGRect)_contentRectInPixels;
- (BOOL)_isTiledWhenStretchedToSize:(CGSize)arg1;
- (CGRect)_contentStretchInPixels;
- (CGSize)_sizeInPixels;
- (CGRect)_contentInsetsInPixels:(NSEdgeInsets)arg1 emptySizeFallback:(id)arg2;
- (void)drawInRect:(CGRect)arg1 fromRect:(CGRect)arg2 operation:(NSUInteger)arg3 fraction:(double)arg4 respectFlipped:(BOOL)arg5 hints:(id)arg6;
- (void)drawInRect:(CGRect)arg1 fromRect:(CGRect)arg2 operation:(NSUInteger)arg3 fraction:(double)arg4;
- (void)_setupNinePartFromImage:(id)arg1;
- (id)initWithImage:(id)arg1 capInsets:(NSEdgeInsets)arg2;

@end

