//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSView.h>

@protocol _UXSourceSplitViewCursorProvider;

@interface _UXSourceSplitViewFullScreenOverlayContentView : NSView
{
    NSView *_separatorView;	// 112 = 0x70
    id <_UXSourceSplitViewCursorProvider> _cursorProvider;	// 120 = 0x78
}


@property(nonatomic) __weak id <_UXSourceSplitViewCursorProvider> cursorProvider; // @synthesize cursorProvider=_cursorProvider;
@property(nonatomic) __weak NSView *separatorView; // @synthesize separatorView=_separatorView;
- (id)description;
- (id)hitTest:(CGPoint)arg1;
- (void)resetCursorRects;

@end

