//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

@class UXView, _UXSourceSplitView;

@protocol _UXSourceSplitViewDelegate <NSObject>
- (BOOL)sourceSplitView:(_UXSourceSplitView *)arg1 canSpringLoadRevealSubview:(UXView *)arg2;
- (void)sourceSplitView:(_UXSourceSplitView *)arg1 didChangeAutoCollapsedValue:(BOOL)arg2;
- (void)sourceSplitView:(_UXSourceSplitView *)arg1 didResizeMasterWidth:(double)arg2;
@end

