//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSView.h>

@interface _UXSourceSplitViewShadowView : NSView
{
    CGFloat _shadowRevealAmount;	// 112 = 0x70
    NSUInteger _shadowEdge;	// 120 = 0x78
}

@property(nonatomic) NSUInteger shadowEdge; // @synthesize shadowEdge=_shadowEdge;
@property(nonatomic) CGFloat shadowRevealAmount; // @synthesize shadowRevealAmount=_shadowRevealAmount;
- (id)makeShadowImage;
- (CGSize)intrinsicContentSize;
- (void)setFrameOrigin:(CGPoint)arg1;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (id)hitTest:(CGPoint)arg1;

@end

