//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSBox, UXLabel, UXView;

@interface _UXTableHeaderView
{
    BOOL _floating;	// 108 = 0x6c
    UXView *_contentView;	// 112 = 0x70
    UXLabel *_titleLabel;	// 120 = 0x78
    NSBox *_separator;	// 128 = 0x80
}


@property(readonly, nonatomic) NSBox *separator; // @synthesize separator=_separator;
@property(readonly, nonatomic) UXLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) UXView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic, getter=isFloating) BOOL floating; // @synthesize floating=_floating;
- (void)mouseDown:(id)arg1;
- (void)prepareForReuse;
- (id)initWithFrame:(CGRect)arg1;

@end

