//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "_UXBarItemsContainer-Protocol.h"

@class NSArray, NSMutableArray, NSString;

@interface _UXToolbarItemsContainer <_UXBarItemsContainer>
{
    NSMutableArray *__addedConstraints;	// 112 = 0x70
    BOOL _singleItemMode;	// 120 = 0x78
    BOOL _isTransitioning;	// 121 = 0x79
    NSArray *_items;	// 128 = 0x80
    double _interitemSpacing;	// 136 = 0x88
    double _baselineOffsetFromBottom;	// 144 = 0x90
}

+ (id)toolbarItemsContainerForToolbar:(id)arg1 items:(id)arg2;

@property(nonatomic) double baselineOffsetFromBottom; // @synthesize baselineOffsetFromBottom=_baselineOffsetFromBottom;
@property(nonatomic) double interitemSpacing; // @synthesize interitemSpacing=_interitemSpacing;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
- (double)lastBaselineOffsetFromBottom;
- (void)updateConstraints;
@property(readonly, nonatomic) BOOL hidesGlobalTrailingView;
- (void)prepareForTransition;
- (id)initWithFrame:(CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

