//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

#import "UXViewControllerContextTransitioning-Protocol.h"

@class NSArray, NSString, UXView, _UXViewControllerTransitionCoordinator;
@protocol UXViewControllerAnimatedTransitioning, UXViewControllerInteractiveTransitioning;

@interface _UXViewControllerTransitionContext : NSObject <UXViewControllerContextTransitioning>


@property (nonatomic, copy) id completionHandler; // @synthesize completionHandler=_completionHandler;
@property (nonatomic, copy) id willCompleteHandler; // @synthesize willCompleteHandler=_willCompleteHandler;
@property (nonatomic) __weak UXView *containerView; // @synthesize containerView=_containerView;
@property (nonatomic) __weak id <UXViewControllerInteractiveTransitioning> interactor; // @synthesize interactor=_interactor;
@property (nonatomic) __weak id <UXViewControllerAnimatedTransitioning> animator; // @synthesize animator=_animator;
@property (nonatomic) CGFloat percentOffset; // @synthesize percentOffset=_percentOffset;
@property (nonatomic, getter = isPresentation) BOOL presentation; // @synthesize presentation=_presentation;
@property (nonatomic) NSInteger presentationStyle; // @synthesize presentationStyle=_presentationStyle;
@property (nonatomic, copy) id interactiveUpdateHandler; // @synthesize interactiveUpdateHandler=_interactiveUpdateHandler;
@property (nonatomic) NSInteger state; // @synthesize state=_state;
@property (nonatomic) CGFloat duration; // @synthesize duration=_duration;
@property (nonatomic, strong, setter = _setAuxContext:) _UXViewControllerTransitionCoordinator *_auxContext; // @synthesize _auxContext=__auxContext;
@property (nonatomic) NSInteger completionCurve; // @synthesize completionCurve=_completionCurve;
@property (nonatomic) CGFloat completionVelocity; // @synthesize completionVelocity=_completionVelocity;
@property (nonatomic, getter = isAnimated) BOOL animated; // @synthesize animated=_animated;
@property (nonatomic, getter = isCurrentlyInteractive) BOOL currentlyInteractive; // @synthesize currentlyInteractive=_currentlyInteractive;
@property (nonatomic) BOOL initiallyInteractive; // @synthesize initiallyInteractive=_initiallyInteractive;
- (void)_enableInteractionForDisabledViews;
- (void)_disableInteractionForViews:(id)arg1;
- (void)__runAlongsideAnimations;
- (void)_interactivityDidChange:(BOOL)arg1;
- (void)_runAlongsideCompletions;
- (void)_setTransitionIsCompleting:(BOOL)arg1;
- (BOOL)_transitionIsCompleting;
@property (nonatomic) BOOL transitionIsInFlight;
- (BOOL)transitionWasCancelled;
- (CGRect)finalFrameForViewController:(id)arg1;
- (CGRect)initialFrameForViewController:(id)arg1;
- (id)viewControllerForKey:(id)arg1;
- (void)completeTransition:(BOOL)arg1;
- (void)cancelInteractiveTransition;
- (void)finishInteractiveTransition;
- (void)updateInteractiveTransition:(CGFloat)arg1;
- (void)_updateInteractiveTransitionWithoutTrackingPercentComplete:(CGFloat)arg1;
- (void)_setPreviousPercentComplete:(CGFloat)arg1;
- (CGFloat)_previousPercentComplete;
- (id)_transitionCoordinator;
- (BOOL)isInteractive;

@end
