//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import "UXViewControllerContextTransitioning-Protocol.h"

@class NSArray, NSString, UXView, _UXViewControllerTransitionCoordinator;
@protocol UXViewControllerAnimatedTransitioning, UXViewControllerInteractiveTransitioning;

@interface _UXViewControllerTransitionContext : NSObject <UXViewControllerContextTransitioning>
{
    double _previousPercentComplete;	// 8 = 0x8
    NSArray *_disabledViews;	// 16 = 0x10
    struct {
        unsigned int interactorImplementsCompletionSpeed:1;
        unsigned int interactorImplementsCompletionCurve:1;
        unsigned int transitionWasCancelled:1;
        unsigned int transitionIsCompleting:1;
    } _transitionContextFlags;	// 24 = 0x18
    BOOL _initiallyInteractive;	// 28 = 0x1c
    BOOL _currentlyInteractive;	// 29 = 0x1d
    BOOL _animated;	// 30 = 0x1e
    BOOL _presentation;	// 31 = 0x1f
    double _completionVelocity;	// 32 = 0x20
    NSInteger _completionCurve;	// 40 = 0x28
    _UXViewControllerTransitionCoordinator *__auxContext;	// 48 = 0x30
    double _duration;	// 56 = 0x38
    NSInteger _state;	// 64 = 0x40
    id _interactiveUpdateHandler;	// 72 = 0x48
    NSInteger _presentationStyle;	// 80 = 0x50
    double _percentOffset;	// 88 = 0x58
    id <UXViewControllerAnimatedTransitioning> _animator;	// 96 = 0x60
    id <UXViewControllerInteractiveTransitioning> _interactor;	// 104 = 0x68
    UXView *_containerView;	// 112 = 0x70
    id _willCompleteHandler;	// 120 = 0x78
    id _completionHandler;	// 128 = 0x80
}


@property(copy, nonatomic) id completionHandler; // @synthesize completionHandler=_completionHandler;
@property(copy, nonatomic) id willCompleteHandler; // @synthesize willCompleteHandler=_willCompleteHandler;
@property(nonatomic) __weak UXView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <UXViewControllerInteractiveTransitioning> interactor; // @synthesize interactor=_interactor;
@property(nonatomic) __weak id <UXViewControllerAnimatedTransitioning> animator; // @synthesize animator=_animator;
@property(nonatomic) double percentOffset; // @synthesize percentOffset=_percentOffset;
@property(nonatomic, getter=isPresentation) BOOL presentation; // @synthesize presentation=_presentation;
@property(nonatomic) NSInteger presentationStyle; // @synthesize presentationStyle=_presentationStyle;
@property(copy, nonatomic) id interactiveUpdateHandler; // @synthesize interactiveUpdateHandler=_interactiveUpdateHandler;
@property(nonatomic) NSInteger state; // @synthesize state=_state;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic, setter=_setAuxContext:) _UXViewControllerTransitionCoordinator *_auxContext; // @synthesize _auxContext=__auxContext;
@property(nonatomic) NSInteger completionCurve; // @synthesize completionCurve=_completionCurve;
@property(nonatomic) double completionVelocity; // @synthesize completionVelocity=_completionVelocity;
@property(nonatomic, getter=isAnimated) BOOL animated; // @synthesize animated=_animated;
@property(nonatomic, getter=isCurrentlyInteractive) BOOL currentlyInteractive; // @synthesize currentlyInteractive=_currentlyInteractive;
@property(nonatomic) BOOL initiallyInteractive; // @synthesize initiallyInteractive=_initiallyInteractive;
- (void)_enableInteractionForDisabledViews;
- (void)_disableInteractionForViews:(id)arg1;
- (void)__runAlongsideAnimations;
- (void)_interactivityDidChange:(BOOL)arg1;
- (void)_runAlongsideCompletions;
- (void)_setTransitionIsCompleting:(BOOL)arg1;
- (BOOL)_transitionIsCompleting;
@property(nonatomic) BOOL transitionIsInFlight;
- (BOOL)transitionWasCancelled;
- (CGRect)finalFrameForViewController:(id)arg1;
- (CGRect)initialFrameForViewController:(id)arg1;
- (id)viewControllerForKey:(id)arg1;
- (void)completeTransition:(BOOL)arg1;
- (void)cancelInteractiveTransition;
- (void)finishInteractiveTransition;
- (void)updateInteractiveTransition:(double)arg1;
- (void)_updateInteractiveTransitionWithoutTrackingPercentComplete:(double)arg1;
- (void)_setPreviousPercentComplete:(double)arg1;
- (double)_previousPercentComplete;
- (id)_transitionCoordinator;
- (BOOL)isInteractive;
- (id)init;

// Remaining properties
@property(copy, nonatomic) id arbitraryTransitionCompletionHandler;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

