//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UXView, UXViewController;

@interface _UXViewControllerOneToOneTransitionContext
{
    id arbitraryTransitionCompletionHandler;	// 136 = 0x88
    UXViewController *_fromViewController;	// 144 = 0x90
    UXViewController *_toViewController;	// 152 = 0x98
    CGRect _fromStartFrame;	// 160 = 0xa0
    CGRect _fromEndFrame;	// 192 = 0xc0
    CGRect _toEndFrame;	// 224 = 0xe0
    CGRect _toStartFrame;	// 256 = 0x100
}


@property(nonatomic) CGRect toStartFrame; // @synthesize toStartFrame=_toStartFrame;
@property(nonatomic) CGRect toEndFrame; // @synthesize toEndFrame=_toEndFrame;
@property(nonatomic) CGRect fromEndFrame; // @synthesize fromEndFrame=_fromEndFrame;
@property(nonatomic) CGRect fromStartFrame; // @synthesize fromStartFrame=_fromStartFrame;
@property(retain, nonatomic) UXViewController *toViewController; // @synthesize toViewController=_toViewController;
@property(retain, nonatomic) UXViewController *fromViewController; // @synthesize fromViewController=_fromViewController;
- (void)setArbitraryTransitionCompletionHandler:(id)arg1;
- (id)arbitraryTransitionCompletionHandler;
@property(readonly, nonatomic) UXView *fromView;
@property(readonly, nonatomic) UXView *toView;
- (CGRect)finalFrameForViewController:(id)arg1;
- (CGRect)initialFrameForViewController:(id)arg1;
- (id)viewControllerForKey:(id)arg1;

@end

