//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _UXWindowState : NSObject
{
    NSUInteger _styleMask;	// 8 = 0x8
    NSUInteger _collectionBehavior;	// 16 = 0x10
}

+ (id)windowStateWithStyleMask:(NSUInteger)arg1 collectionBehavior:(NSUInteger)arg2;
@property(readonly) NSUInteger collectionBehavior; // @synthesize collectionBehavior=_collectionBehavior;
@property(readonly) NSUInteger styleMask; // @synthesize styleMask=_styleMask;
- (void)applyToWindow:(id)arg1;

@end

