//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#pragma mark Typedef'd Structures

typedef struct {
    NSUInteger _field1;
    id _field2;
    NSUInteger *_field3;
    NSUInteger _field4[5];
} CDStruct_70511ce9;

