//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSIndexPath.h>

@interface NSIndexPath (UXCollectionViewAdditions)
+ (id)indexPathForItem:(NSInteger)arg1 inSection:(NSInteger)arg2;
+ (id)indexPathForRow:(NSInteger)arg1 inSection:(NSInteger)arg2;
@property(readonly, nonatomic) NSInteger section;
@property(readonly, nonatomic) NSInteger item;
@property(readonly, nonatomic) NSInteger row;
@end

