//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSProgressIndicator.h>

@class NSColor;

@interface NSProgressIndicator (Compatibility)
- (BOOL)isAnimating;
- (void)stopAnimating;
- (void)startAnimating;
@property(retain, nonatomic) NSColor *color;
@property(nonatomic) BOOL hidesWhenStopped;
@property(nonatomic) NSInteger activityIndicatorViewStyle;
- (void)setProgress:(double)arg1 animated:(BOOL)arg2;
@property(nonatomic) double progress;
@property(nonatomic) NSInteger progressViewStyle;
- (id)initWithProgressViewStyle:(NSInteger)arg1;
- (id)initWithActivityIndicatorStyle:(NSInteger)arg1;
@end

