//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSTextField.h>

#import "UITextInputTraits-Protocol.h"

@class NSString;

@interface NSTextField (Compatibility) <UITextInputTraits>
@property(nonatomic) NSInteger textAlignment;
@property(copy, nonatomic) NSString *placeholder;
@property(copy, nonatomic) NSString *text;

// Remaining properties
@property(nonatomic) NSInteger autocapitalizationType;
@property(nonatomic) NSInteger autocorrectionType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) BOOL enablesReturnKeyAutomatically;
@property(readonly) NSUInteger hash;
@property(nonatomic) NSInteger keyboardAppearance;
@property(nonatomic) NSInteger keyboardType;
@property(nonatomic) NSInteger returnKeyType;
@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property(nonatomic) NSInteger spellCheckingType;
@property(readonly) Class superclass;
@end

