//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

#import "UXKitAppearance-Protocol.h"

@class NSColor, NSString;

@interface NSView (UXKit) <UXKitAppearance>
- (CGFloat)ux_backingScaleFactor;
- (id)enclosingViewOfClass:(Class)arg1;
- (void)tintColorDidChange;
@property(nonatomic) NSInteger tintAdjustmentMode;
@property(strong, nonatomic) NSColor *tintColor;
- (void)setContentCompressionResistancePriority:(float)arg1 forAxis:(NSInteger)arg2;
- (float)contentCompressionResistancePriorityForAxis:(NSInteger)arg1;
- (void)setContentHuggingPriority:(float)arg1 forAxis:(NSInteger)arg2;
- (float)contentHuggingPriorityForAxis:(NSInteger)arg1;
@property(nonatomic) CGFloat alpha;
- (BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutIfNeeded;
- (void)layoutSubviews;
- (void)setNeedsUpdateConstraints;
- (void)updateConstraintsIfNeeded;
- (void)setNeedsDisplay;
- (void)setNeedsLayout;
- (void)didMoveToWindow;

// Remaining properties
@property(copy) NSColor *backgroundColor; // @dynamic backgroundColor;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly, nonatomic, getter=isHidden) BOOL hidden;
@property(readonly) Class superclass;
@end

