//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

#import "UXKitAppearance-Protocol.h"

@class NSColor, NSString;

NS_HEADER_AUDIT_BEGIN(nullability, sendability)

@interface NSView (UXKit) <UXKitAppearance>
@property (nonatomic) NSInteger tintAdjustmentMode;
@property (nonatomic, strong, nullable) NSColor *tintColor;
@property (nonatomic) CGFloat alpha;
- (CGFloat)ux_backingScaleFactor;
- (nullable id)enclosingViewOfClass:(Class)cls;
- (void)tintColorDidChange;
- (void)setContentCompressionResistancePriority:(float)arg1 forAxis:(NSInteger)arg2;
- (float)contentCompressionResistancePriorityForAxis:(NSInteger)arg1;
- (void)setContentHuggingPriority:(float)arg1 forAxis:(NSInteger)arg2;
- (float)contentHuggingPriorityForAxis:(NSInteger)arg1;
- (BOOL)pointInside:(CGPoint)point withEvent:(NSEvent *)event;
- (void)layoutIfNeeded;
- (void)layoutSubviews;
- (void)setNeedsUpdateConstraints;
- (void)updateConstraintsIfNeeded;
- (void)setNeedsDisplay;
- (void)setNeedsLayout;
- (void)didMoveToWindow;

// Remaining properties
@property (copy, nullable) NSColor *backgroundColor;

@end

NS_HEADER_AUDIT_END(nullability, sendability)
