//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSIndexPath.h>

@interface UIMutableIndexPath : NSIndexPath
{
    NSUInteger *_mutableIndexes;	// 32 = 0x20
    BOOL _locked;	// 40 = 0x28
}

+ (void)setIndex:(NSUInteger)arg1 atPosition:(NSUInteger)arg2 forIndexPath:(id *)arg3;
- (id)retain;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (NSInteger)compare:(id)arg1;
- (void)getIndexes:(NSUInteger *)arg1;
- (NSUInteger)indexAtPosition:(NSUInteger)arg1;
- (void)dealloc;
- (id)initWithIndexes:(const NSUInteger *)arg1 length:(NSUInteger)arg2;

@end

