//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

@protocol UITextInputTraits <NSObject>

@optional
@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property(nonatomic) BOOL enablesReturnKeyAutomatically;
@property(nonatomic) NSInteger returnKeyType;
@property(nonatomic) NSInteger keyboardAppearance;
@property(nonatomic) NSInteger keyboardType;
@property(nonatomic) NSInteger spellCheckingType;
@property(nonatomic) NSInteger autocorrectionType;
@property(nonatomic) NSInteger autocapitalizationType;
@end

