//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSSegmentedControl.h>

@class NSImage, NSString;

@interface UXBackButton : NSSegmentedControl

@property(strong, nonatomic) NSImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) BOOL hidesTitle; // @synthesize hidesTitle=_hidesTitle;
- (id)description;
- (id)init;

@end

