//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UXKitAppearance-Protocol.h"

@class NSColor, NSLayoutAnchor, NSString, NSView, UXViewController;

@interface UXBarButtonItem <UXKitAppearance>
{
    NSView *__view;	// 8 = 0x8
    BOOL _ignoresMultiClick;	// 16 = 0x10
    BOOL _condensed;	// 17 = 0x11
    float _visibilityPriority;	// 20 = 0x14
    NSColor *_tintColor;	// 24 = 0x18
    NSInteger _tintAdjustmentMode;	// 32 = 0x20
    SEL _action;	// 40 = 0x28
    id _target;	// 48 = 0x30
    NSString *_toolTip;	// 56 = 0x38
    NSString *_keyEquivalent;	// 64 = 0x40
    NSUInteger _keyEquivalentModifierMask;	// 72 = 0x48
    NSInteger _buttonState;	// 80 = 0x50
    NSInteger _style;	// 88 = 0x58
    double _width;	// 96 = 0x60
    NSView *_customView;	// 104 = 0x68
    NSLayoutAnchor *_baselineAnchor;	// 112 = 0x70
    UXViewController *_contentViewController;	// 120 = 0x78
    NSInteger _systemItem;	// 128 = 0x80
    UXBarButtonItem *__widthConstrainingItem;	// 136 = 0x88
}


@property(nonatomic, setter=_setWidthConstrainingItem:) __weak UXBarButtonItem *_widthConstrainingItem; // @synthesize _widthConstrainingItem=__widthConstrainingItem;
@property(nonatomic) float visibilityPriority; // @synthesize visibilityPriority=_visibilityPriority;
@property(nonatomic, getter=isCondensed) BOOL condensed; // @synthesize condensed=_condensed;
@property(readonly, nonatomic) NSInteger systemItem; // @synthesize systemItem=_systemItem;
@property(readonly, nonatomic) UXViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
@property(retain, nonatomic) NSLayoutAnchor *baselineAnchor; // @synthesize baselineAnchor=_baselineAnchor;
@property(retain, nonatomic) NSView *customView; // @synthesize customView=_customView;
@property(nonatomic) double width; // @synthesize width=_width;
@property(nonatomic) NSInteger style; // @synthesize style=_style;
@property(readonly, nonatomic) NSView *_view;
- (id)_viewOfClass:(Class)arg1;
@property(readonly, copy) NSString *description;
- (id)image;
- (void)setImage:(id)arg1;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)arg1;
@property(nonatomic) BOOL ignoresMultiClick; // @synthesize ignoresMultiClick=_ignoresMultiClick;
@property(nonatomic) NSInteger buttonState; // @synthesize buttonState=_buttonState;
@property(nonatomic) NSUInteger keyEquivalentModifierMask; // @synthesize keyEquivalentModifierMask=_keyEquivalentModifierMask;
@property(retain, nonatomic) NSString *keyEquivalent; // @synthesize keyEquivalent=_keyEquivalent;
@property(retain, nonatomic) NSString *toolTip; // @synthesize toolTip=_toolTip;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) SEL action; // @synthesize action=_action;
- (void)setAccessibilityLabel:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)tintColorDidChange;
@property(nonatomic) NSInteger tintAdjustmentMode; // @synthesize tintAdjustmentMode=_tintAdjustmentMode;
@property(retain, nonatomic) NSColor *tintColor; // @synthesize tintColor=_tintColor;
- (double)preferredSpacingToItem:(id)arg1 proposedSpacing:(double)arg2;
- (id)initWithStyle:(NSInteger)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)initWithContentViewController:(id)arg1;
- (id)initWithCustomView:(id)arg1;
- (id)initWithBarButtonSystemItem:(NSInteger)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)initWithTitle:(id)arg1 style:(NSInteger)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)initWithImage:(id)arg1 style:(NSInteger)arg2 target:(id)arg3 action:(SEL)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

