//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>
#import "UXBarPositioning-Protocol.h"

@class NSColor, NSMutableSet, NSString, NSView, UXView, _UXSinglePixelLine;
@protocol _UXBarItemsContainer;

@interface UXBar <NSAccessibilityGroup, UXBarPositioning>
{
    _UXSinglePixelLine *_decorationLine;	// 112 = 0x70
    NSMutableSet *_previousBarItemContainers;	// 120 = 0x78
    NSInteger _containerTransitionAnimationCount;	// 128 = 0x80
    NSView *_placeholderTrailingView;	// 136 = 0x88
    BOOL _isInteractiveTransitioning;	// 144 = 0x90
    BOOL _trailingViewNeedsRemoval;	// 145 = 0x91
    NSColor *_barTintColor;	// 152 = 0x98
    double _interitemSpacing;	// 160 = 0xa0
    double _height;	// 168 = 0xa8
    double _baselineOffsetFromBottom;	// 176 = 0xb0
    double _percent;	// 184 = 0xb8
    UXView<_UXBarItemsContainer> *_nextItemContainer;	// 192 = 0xc0
    NSView *_globalTrailingView;	// 200 = 0xc8
    double _globalTrailingViewWidthMultiplier;	// 208 = 0xd0
    UXView<_UXBarItemsContainer> *_barItemsContainer;	// 216 = 0xd8
    NSEdgeInsets _decorationInsets;	// 224 = 0xe0
}


@property(nonatomic) NSEdgeInsets decorationInsets; // @synthesize decorationInsets=_decorationInsets;
@property(retain, nonatomic) UXView<_UXBarItemsContainer> *barItemsContainer; // @synthesize barItemsContainer=_barItemsContainer;
@property(nonatomic) double globalTrailingViewWidthMultiplier; // @synthesize globalTrailingViewWidthMultiplier=_globalTrailingViewWidthMultiplier;
@property(retain, nonatomic) NSView *globalTrailingView; // @synthesize globalTrailingView=_globalTrailingView;
@property(retain, nonatomic) UXView<_UXBarItemsContainer> *nextItemContainer; // @synthesize nextItemContainer=_nextItemContainer;
@property(nonatomic) double percent; // @synthesize percent=_percent;
@property(nonatomic) BOOL trailingViewNeedsRemoval; // @synthesize trailingViewNeedsRemoval=_trailingViewNeedsRemoval;
@property(nonatomic) BOOL isInteractiveTransitioning; // @synthesize isInteractiveTransitioning=_isInteractiveTransitioning;
@property(nonatomic) double baselineOffsetFromBottom; // @synthesize baselineOffsetFromBottom=_baselineOffsetFromBottom;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double interitemSpacing; // @synthesize interitemSpacing=_interitemSpacing;
@property(retain, nonatomic) NSColor *barTintColor; // @synthesize barTintColor=_barTintColor;
- (void)_updateDecorationLine;
@property(readonly, nonatomic) NSInteger barPosition;
- (CGSize)intrinsicContentSize;
- (void)_completeInteractiveTransition:(BOOL)arg1 duration:(double)arg2;
- (void)_finishInteractiveTransition:(BOOL)arg1 duration:(double)arg2 completion:(id)arg3;
- (void)_updateInteractiveTransition:(double)arg1;
- (void)_beginInteractiveTransitionToItemContainer:(id)arg1;
- (void)_animateTransitionFromContainer:(id)arg1 toContainer:(id)arg2 transition:(NSUInteger)arg3 duration:(double)arg4 fromValue:(double)arg5 toValue:(double)arg6 completion:(id)arg7;
- (void)_didCompleteContainerTransitionAnimation;
- (void)_transitionToContainer:(id)arg1 transition:(NSUInteger)arg2 duration:(double)arg3;
- (void)_updateTrailingViewWithItemContainer:(id)arg1;
- (id)borderColor;
- (void)setBorderColor:(id)arg1;
@property(nonatomic) BOOL bordered;
- (void)viewWillMoveToSuperview:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSUInteger hash;
@property(readonly) Class superclass;

@end

