//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>
#import "UXView.h"
#import "UXBarCommon.h"

@class NSColor, NSMutableSet, NSString, NSView, UXView, _UXSinglePixelLine;
@protocol _UXBarItemsContainer;

@interface UXBar: UXView <NSAccessibilityGroup, UXBarPositioning>


@property(nonatomic) NSEdgeInsets decorationInsets; // @synthesize decorationInsets=_decorationInsets;
@property(retain, nonatomic) UXView<_UXBarItemsContainer> *barItemsContainer; // @synthesize barItemsContainer=_barItemsContainer;
@property(nonatomic) double globalTrailingViewWidthMultiplier; // @synthesize globalTrailingViewWidthMultiplier=_globalTrailingViewWidthMultiplier;
@property(retain, nonatomic) NSView *globalTrailingView; // @synthesize globalTrailingView=_globalTrailingView;
@property(retain, nonatomic) UXView<_UXBarItemsContainer> *nextItemContainer; // @synthesize nextItemContainer=_nextItemContainer;
@property(nonatomic) double percent; // @synthesize percent=_percent;
@property(nonatomic) BOOL trailingViewNeedsRemoval; // @synthesize trailingViewNeedsRemoval=_trailingViewNeedsRemoval;
@property(nonatomic) BOOL isInteractiveTransitioning; // @synthesize isInteractiveTransitioning=_isInteractiveTransitioning;
@property(nonatomic) double baselineOffsetFromBottom; // @synthesize baselineOffsetFromBottom=_baselineOffsetFromBottom;
@property (nonatomic) NSEdgeInsets layoutMargins; 
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double interitemSpacing; // @synthesize interitemSpacing=_interitemSpacing;
@property(retain, nonatomic) NSColor *barTintColor; // @synthesize barTintColor=_barTintColor;
- (void)_updateDecorationLine;
@property(readonly, nonatomic) NSInteger barPosition;
- (CGSize)intrinsicContentSize;
- (void)_completeInteractiveTransition:(BOOL)arg1 duration:(double)arg2;
- (void)_finishInteractiveTransition:(BOOL)arg1 duration:(double)arg2 completion:(id)arg3;
- (void)_updateInteractiveTransition:(double)arg1;
- (void)_beginInteractiveTransitionToItemContainer:(id)arg1;
- (void)_animateTransitionFromContainer:(id)arg1 toContainer:(id)arg2 transition:(NSUInteger)arg3 duration:(double)arg4 fromValue:(double)arg5 toValue:(double)arg6 completion:(id)arg7;
- (void)_didCompleteContainerTransitionAnimation;
- (void)_transitionToContainer:(id)arg1 transition:(NSUInteger)arg2 duration:(double)arg3;
- (void)_updateTrailingViewWithItemContainer:(id)arg1;
- (id)borderColor;
- (void)setBorderColor:(id)arg1;
@property(nonatomic) BOOL bordered;
- (void)viewWillMoveToSuperview:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;
@end

