//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSIndexPath;

@interface UXCollectionViewUpdateItem : NSObject
{
    NSIndexPath *_initialIndexPath;	// 8 = 0x8
    NSIndexPath *_finalIndexPath;	// 16 = 0x10
    NSInteger _updateAction;	// 24 = 0x18
    id _gap;	// 32 = 0x20
}

@property(readonly, nonatomic) NSInteger updateAction; // @synthesize updateAction=_updateAction;
@property(readonly, strong, nonatomic) NSIndexPath *indexPathAfterUpdate; // @synthesize indexPathAfterUpdate=_finalIndexPath;
@property(readonly, strong, nonatomic) NSIndexPath *indexPathBeforeUpdate; // @synthesize indexPathBeforeUpdate=_initialIndexPath;
- (NSInteger)inverseCompareIndexPaths:(id)arg1;
- (NSInteger)compareIndexPaths:(id)arg1;
- (BOOL)_isSectionOperation;
- (void)_setGap:(id)arg1;
- (id)_gap;
- (id)_indexPath;
- (NSInteger)_action;
- (id)description;
- (void)_setNewIndexPath:(id)arg1;
- (id)_newIndexPath;
- (void)dealloc;
- (id)initWithOldIndexPath:(id)arg1 newIndexPath:(id)arg2;
- (id)initWithAction:(NSInteger)arg1 forIndexPath:(id)arg2;
- (id)initWithInitialIndexPath:(id)arg1 finalIndexPath:(id)arg2 updateAction:(NSInteger)arg3;

@end

