//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/NSFilePromiseProvider.h>

@class NSArray, NSMutableArray;

@interface UXCollectionViewFilePromiseProvider : NSFilePromiseProvider
{
    NSMutableArray *_auxiliaryFilePromiseProviders;	// 8 = 0x8
}


- (void)addAuxiliaryFilePromiseProvider:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *auxiliaryFilePromiseProviders;

@end

