//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>
#import "UXView.h"

@class NSImage, NSString;

@interface UXImageView: UXView <NSAccessibilityImage>
{
    CGFloat _backingScaleFactor;	// 112 = 0x70
    CGSize _proposedSize;	// 120 = 0x78
    BOOL _allowsVibrancy;	// 136 = 0x88
    BOOL _highlighted;	// 137 = 0x89
    NSString *accessibilityLabel;	// 144 = 0x90
    NSImage *_image;	// 152 = 0x98
    NSImage *_highlightedImage;	// 160 = 0xa0
}


@property(nonatomic, getter=isHighlighted) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(retain, nonatomic) NSImage *highlightedImage; // @synthesize highlightedImage=_highlightedImage;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
@property(nonatomic) BOOL allowsVibrancy; // @synthesize allowsVibrancy=_allowsVibrancy;
@property(retain, nonatomic) NSString *accessibilityLabel; // @synthesize accessibilityLabel;
- (void)viewDidChangeEffectiveAppearance;
- (void)sizeToFit;
- (void)_updateForCurrentImage;
- (void)_updateProposedSize;
- (void)_updateBackingScaleFactorForWindow:(id)arg1;
- (void)_updateLayerContentsForWindow:(id)arg1;
- (void)_updateLayerContents;
- (CGSize)_proposedSize;
- (void)_setContentStretchInPixels:(CGRect)arg1 forContentSize:(CGSize)arg2 shouldTile:(BOOL)arg3;
@property(readonly, nonatomic) NSImage *_currentImage;
- (void)setFrameSize:(CGSize)arg1;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewDidChangeBackingProperties;
- (CGSize)intrinsicContentSize;
- (instancetype)initWithImage:(NSImage *)arg1 highlightedImage:(NSImage *)arg2;
- (instancetype)initWithImage:(NSImage *)arg1;

@end

