//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString, NSTextField, NSView, UXBarButtonItem;

@interface UXNavigationItem : NSObject <NSUserInterfaceItemIdentification>
{
    NSArray *_leftBarButtonItems;	// 8 = 0x8
    NSArray *_rightBarButtonItems;	// 16 = 0x10
    NSTextField *_internalTitleView;	// 24 = 0x18
    BOOL _hidesBackButton;	// 32 = 0x20
    BOOL _hidesAlternateTitleView;	// 33 = 0x21
    BOOL _hidesGlobalTrailingView;	// 34 = 0x22
    BOOL _leftItemsSupplementBackButton;	// 35 = 0x23
    NSString *_title;	// 40 = 0x28
    UXBarButtonItem *_backBarButtonItem;	// 48 = 0x30
    NSView *_titleView;	// 56 = 0x38
    NSString *_prompt;	// 64 = 0x40
    NSView *_condensedTitleView;	// 72 = 0x48
}


@property(retain, nonatomic) NSView *condensedTitleView; // @synthesize condensedTitleView=_condensedTitleView;
@property(nonatomic) BOOL leftItemsSupplementBackButton; // @synthesize leftItemsSupplementBackButton=_leftItemsSupplementBackButton;
@property(nonatomic) BOOL hidesGlobalTrailingView; // @synthesize hidesGlobalTrailingView=_hidesGlobalTrailingView;
@property(nonatomic) BOOL hidesAlternateTitleView; // @synthesize hidesAlternateTitleView=_hidesAlternateTitleView;
@property(nonatomic) BOOL hidesBackButton; // @synthesize hidesBackButton=_hidesBackButton;
@property(copy, nonatomic) NSString *prompt; // @synthesize prompt=_prompt;
@property(retain, nonatomic) NSView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UXBarButtonItem *backBarButtonItem; // @synthesize backBarButtonItem=_backBarButtonItem;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UXBarButtonItem *rightBarButtonItem;
@property(retain, nonatomic) NSArray *rightBarButtonItems;
@property(retain, nonatomic) NSArray *leftBarButtonItems;
@property(retain, nonatomic) UXBarButtonItem *leftBarButtonItem;
- (void)_updateInternalTitleView;
@property(readonly, nonatomic) NSTextField *internalTitleView;
@property(retain, nonatomic) NSArray *trailingBarButtonItems;
- (void)setTrailingBarButtonItems:(id)arg1 animated:(BOOL)arg2;
@property(retain, nonatomic) NSArray *leadingBarButtonItems;
- (void)setLeadingBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (void)setRightBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (void)setRightBarButtonItem:(id)arg1 animated:(BOOL)arg2;
- (void)setLeftBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (void)setLeftBarButtonItem:(id)arg1 animated:(BOOL)arg2;
- (id)initWithTitle:(id)arg1;

@end

