//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>
#import "UXKitDefines.h"
#import "UXToolbar.h"
#import "UXToolbarDelegate-Protocol.h"
#import "UXViewController.h"

NS_HEADER_AUDIT_BEGIN(nullability, sendability)

typedef NS_ENUM(NSInteger, UXNavigationControllerOperation) {
    UXNavigationControllerOperationNone,
    UXNavigationControllerOperationPush,
    UXNavigationControllerOperationPop,
};

@class UXNavigationBar, UXToolbar, UXView, UXViewController, UXBarButtonItem;
@protocol UXNavigationControllerDelegate, UXViewControllerAnimatedTransitioning;

@interface UXNavigationController : UXViewController <UXToolbarDelegate, NSMenuDelegate>

@property (nonatomic, weak, nullable) id <UXNavigationControllerDelegate> delegate;
@property (nonatomic, readonly) UXToolbar *toolbar;
@property (nonatomic, getter = isToolbarHidden) BOOL toolbarHidden;
@property (nonatomic, readonly) UXToolbar *subtoolbar;
@property (nonatomic, getter = isSubtoolbarHidden) BOOL subtoolbarHidden;
@property (nonatomic, readonly) UXToolbar *accessoryBar;
@property (nonatomic, readonly, getter = isAccessoryBarHidden) BOOL accessoryBarHidden;
@property (nonatomic, readonly) UXNavigationBar *navigationBar;
@property (nonatomic, getter = isNavigationBarHidden) BOOL navigationBarHidden;
@property (nonatomic, getter = isNavigationBarDetached) BOOL navigationBarDetached;
@property (nonatomic, copy) NSArray<UXViewController *> *viewControllers;
@property (nonatomic, readonly) UXViewController *visibleViewController;
@property (nonatomic, readonly) UXViewController *topViewController;
@property (nonatomic, readonly) NSGestureRecognizer *interactivePopGestureRecognizer;

- (instancetype)initWithNavigationBarClass:(nullable Class)navigationBarClass toolbarClass:(nullable Class)toolbarClass;
- (instancetype)initWithRootViewController:(UXViewController *)rootViewController;
- (nullable instancetype)initWithCoder:(NSCoder *)coder NS_UNAVAILABLE;
- (nullable UXViewController *)popViewControllerAnimated:(BOOL)animated;
- (nullable NSArray<__kindof UXViewController *> *)popToRootViewControllerAnimated:(BOOL)animated;
- (nullable NSArray<__kindof UXViewController *> *)popToViewController:(UXViewController *)viewController animated:(BOOL)animated;
- (void)pushViewController:(UXViewController *)viewController animated:(BOOL)animated;
- (void)setViewControllers:(NSArray<UXViewController *> *)viewControllers animated:(BOOL)animated;
- (void)detachNavigationBar;
- (void)setToolbarHidden:(BOOL)hidden animated:(BOOL)animated;
- (void)setNavigationBarHidden:(BOOL)hidden animated:(BOOL)animated;

@end

NS_HEADER_AUDIT_END(nullability, sendability)
