//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSImage, NSMutableArray, NSView, UXNavigationItem, _UXNavigationItemContainerView;
@protocol UXNavigationBarDelegate;

@interface UXNavigationBar
{
    BOOL _needsRecalculateWindowKeyViewLoop;	// 108 = 0x6c
    BOOL _recalculatingKeyViewLoop;	// 109 = 0x6d
    BOOL _translucent;	// 110 = 0x6e
    BOOL _recalculatingWindowKeyViewLoop;	// 111 = 0x6f
    BOOL _alternateTitleEnabled;	// 112 = 0x70
    BOOL _detached;	// 113 = 0x71
    id <UXNavigationBarDelegate> _delegate;	// 120 = 0x78
    NSView *_titleCenteringTrackedView;	// 128 = 0x80
    NSArray *_items;	// 136 = 0x88
    NSImage *_backIndicatorImage;	// 144 = 0x90
    NSView *_globalTrailingView;	// 152 = 0x98
    double _globalTrailingViewWidthMultiplier;	// 160 = 0xa0
    NSMutableArray *_internalItems;	// 168 = 0xa8
    _UXNavigationItemContainerView *_topItemContainer;	// 176 = 0xb0
    NSInteger _currentOperation;	// 184 = 0xb8
    UXNavigationItem *_transitioningItem;	// 192 = 0xc0
    NSView *_alternateTitleView;	// 200 = 0xc8
    NSView *_alternateCondensedTitleView;	// 208 = 0xd0
    double _leftInteritemSpacing;	// 216 = 0xd8
    double _rightInteritemSpacing;	// 224 = 0xe0
    double _centerYOffset;	// 232 = 0xe8
    NSEdgeInsets _edgeInsets;	// 240 = 0xf0
}

+ (id)_itemKeyPathsToObserve;

@property(nonatomic) double centerYOffset; // @synthesize centerYOffset=_centerYOffset;
@property(nonatomic) double rightInteritemSpacing; // @synthesize rightInteritemSpacing=_rightInteritemSpacing;
@property(nonatomic) double leftInteritemSpacing; // @synthesize leftInteritemSpacing=_leftInteritemSpacing;
@property(nonatomic, getter=isDetached) BOOL detached; // @synthesize detached=_detached;
@property(nonatomic) BOOL alternateTitleEnabled; // @synthesize alternateTitleEnabled=_alternateTitleEnabled;
@property(retain, nonatomic) NSView *alternateCondensedTitleView; // @synthesize alternateCondensedTitleView=_alternateCondensedTitleView;
@property(retain, nonatomic) NSView *alternateTitleView; // @synthesize alternateTitleView=_alternateTitleView;
@property(nonatomic) BOOL recalculatingWindowKeyViewLoop; // @synthesize recalculatingWindowKeyViewLoop=_recalculatingWindowKeyViewLoop;
@property(retain, nonatomic) UXNavigationItem *transitioningItem; // @synthesize transitioningItem=_transitioningItem;
@property(nonatomic) NSInteger currentOperation; // @synthesize currentOperation=_currentOperation;
@property(retain, nonatomic) _UXNavigationItemContainerView *topItemContainer; // @synthesize topItemContainer=_topItemContainer;
@property(retain, nonatomic) NSMutableArray *internalItems; // @synthesize internalItems=_internalItems;
@property(nonatomic) double globalTrailingViewWidthMultiplier; // @synthesize globalTrailingViewWidthMultiplier=_globalTrailingViewWidthMultiplier;
@property(retain, nonatomic) NSView *globalTrailingView; // @synthesize globalTrailingView=_globalTrailingView;
@property(retain, nonatomic) NSImage *backIndicatorImage; // @synthesize backIndicatorImage=_backIndicatorImage;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) __weak NSView *titleCenteringTrackedView; // @synthesize titleCenteringTrackedView=_titleCenteringTrackedView;
@property(nonatomic) NSEdgeInsets edgeInsets; // @synthesize edgeInsets=_edgeInsets;
@property(nonatomic, getter=isTranslucent) BOOL translucent; // @synthesize translucent=_translucent;
@property(nonatomic) __weak id <UXNavigationBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void)setNeedsRecalcuateWindowKeyViewLoop;
- (void)recalculateKeyViewLoop;
- (void)_completeInteractiveTransition:(BOOL)arg1 duration:(double)arg2;
- (void)beginInteractivePop;
- (void)beginInteractivePushToItem:(id)arg1;
- (void)_updateItemContainer;
- (void)_snapshot;
- (id)_popNavigationItemAnimated:(BOOL)arg1 duration:(double)arg2;
- (void)_pushNavigationItem:(id)arg1 animated:(BOOL)arg2 duration:(double)arg3;
- (void)_prepareForNavigationItemTransition;
- (void)_updateTitleView;
- (id)_popNavigationItem;
- (void)_removeItem:(id)arg1;
- (void)_pushItem:(id)arg1;
- (void)_removeObserversForItem:(id)arg1;
- (void)_addObserversForItem:(id)arg1;
- (id)popNavigationItemAnimated:(BOOL)arg1;
- (void)pushNavigationItem:(id)arg1 animated:(BOOL)arg2;
@property(readonly, nonatomic) UXNavigationItem *backItem;
@property(readonly, nonatomic) UXNavigationItem *topItem;
- (void)mouseDown:(id)arg1;
- (void)updateConstraints;
- (void)layout;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (NSInteger)barPosition;
- (void)dealloc;
- (id)initWithFrame:(CGRect)arg1;

@end

