//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>
#import "UXViewController.h"
#import "UXToolbarDelegate-Protocol.h"

typedef NS_ENUM(NSInteger, UXNavigationControllerOperation) {
    UXNavigationControllerOperationNone,
    UXNavigationControllerOperationPush,
    UXNavigationControllerOperationPop,
};
NS_HEADER_AUDIT_BEGIN(nullability, sendability)
@class NSArray, NSGestureRecognizer, NSLayoutConstraint, NSMutableArray, NSString, NSVisualEffectView, UXNavigationBar, UXToolbar, UXTransitionController, UXView, UXViewController, _UXContainerView, _UXViewControllerOneToOneTransitionContext, _UXWindowState, _UXNavigationRequest;
@protocol UXNavigationControllerDelegate, _UXAccessoryBarContainer, UXViewControllerAnimatedTransitioning;

@interface UXNavigationController: UXViewController <UXToolbarDelegate, NSMenuDelegate>


+ (id)topViewControllerObservationKeyPathsByContext;
+ (id)keyPathsForValuesAffectingPreferredContentSize;

@property(readonly, nonatomic) BOOL isInteractive; // @synthesize isInteractive=_isInteractive;
@property(readonly, nonatomic) BOOL isTransitioning; // @synthesize isTransitioning=_isTransitioning;
@property(nonatomic, setter=_setHidesBackTitles:) BOOL _hidesBackTitles; // @synthesize _hidesBackTitles=__hidesBackTitles;
@property(nonatomic, weak, nullable) id <_UXAccessoryBarContainer> accessoryBarContainer; // @synthesize accessoryBarContainer=_accessoryBarContainer;
@property(nonatomic, setter=_setDefaultPopTransition:) NSUInteger _defaultPopTransition; // @synthesize _defaultPopTransition=__defaultPopTransition;
@property(nonatomic, setter=_setDefaultPushTransition:) NSUInteger _defaultPushTransition; // @synthesize _defaultPushTransition=__defaultPushTransition;
@property(readonly, nonatomic) UXBarPosition _subtoolbarPosition; // @synthesize _subtoolbarPosition=__subtoolbarPosition;
@property(readonly, nonatomic) UXBarPosition _toolbarPosition; // @synthesize _toolbarPosition=__toolbarPosition;
@property(readonly, nonatomic) double _leadingContentInset; // @synthesize _leadingContentInset=__leadingContentInset;
@property(nonatomic, getter=_isLocked, setter=_setLocked:) BOOL _locked; // @synthesize _locked=__locked;
@property(nonatomic, getter=_isFullScreenMode, setter=_setFullScreenMode:) BOOL _fullScreenMode; // @synthesize _fullScreenMode=__fullScreenMode;
@property(retain, nonatomic) NSVisualEffectView *subtoolbarVisualEffectsView; // @synthesize subtoolbarVisualEffectsView=_subtoolbarVisualEffectsView;
@property(retain, nonatomic) NSVisualEffectView *toolbarVisualEffectsView; // @synthesize toolbarVisualEffectsView=_toolbarVisualEffectsView;
@property(copy, nonatomic) id testingTransitionAnimationCompletionHandler; // @synthesize testingTransitionAnimationCompletionHandler=_testingTransitionAnimationCompletionHandler;
@property(nonatomic) BOOL shouldAnimateToolbarUpdates; // @synthesize shouldAnimateToolbarUpdates=_shouldAnimateToolbarUpdates;
@property(readonly, nonatomic) UXView *toolbarExtendedBackgroundView; // @synthesize toolbarExtendedBackgroundView=_toolbarExtendedBackgroundView;
@property(nonatomic, getter=isBackButtonMenuEnabled) BOOL backButtonMenuEnabled; // @synthesize backButtonMenuEnabled=_backButtonMenuEnabled;
@property(retain, nonatomic) UXViewController *provisionalPreviousViewController; // @synthesize provisionalPreviousViewController=_provisionalPreviousViewController;
@property(retain, nonatomic) UXViewController *observedViewController; // @synthesize observedViewController=_observedViewController;
@property(retain, nonatomic) UXTransitionController *defaultTransitionController; // @synthesize defaultTransitionController=_defaultTransitionController;
@property(nonatomic) UXNavigationControllerOperation currentOperation; // @synthesize currentOperation=_currentOperation;
@property(retain, nonatomic) _UXViewControllerOneToOneTransitionContext *currentTransitionContext; // @synthesize currentTransitionContext=_currentTransitionContext;
@property(retain, nonatomic) NSArray *topViewControllerOtherConstraints; // @synthesize topViewControllerOtherConstraints=_topViewControllerOtherConstraints;
@property(retain, nonatomic) NSLayoutConstraint *topViewControllerLeftConstraint; // @synthesize topViewControllerLeftConstraint=_topViewControllerLeftConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarLeadingConstraint; // @synthesize toolbarLeadingConstraint=_toolbarLeadingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *toolbarVerticalConstraint; // @synthesize toolbarVerticalConstraint=_toolbarVerticalConstraint;
@property(retain, nonatomic) NSArray *navigationBarConstraints; // @synthesize navigationBarConstraints=_navigationBarConstraints;
@property(retain, nonatomic) NSLayoutConstraint *navigationBarTopConstraint; // @synthesize navigationBarTopConstraint=_navigationBarTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *bottomConstraint; // @synthesize bottomConstraint=_bottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
@property(retain, nonatomic) NSMutableArray *addedConstraints; // @synthesize addedConstraints=_addedConstraints;
@property(retain, nonatomic) _UXContainerView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) _UXWindowState *windowState; // @synthesize windowState=_windowState;
@property(retain, nonatomic) Class toolbarClass; // @synthesize toolbarClass=_toolbarClass;
@property(retain, nonatomic) Class navigationBarClass; // @synthesize navigationBarClass=_navigationBarClass;
@property(readonly, nonatomic) NSGestureRecognizer *interactivePopGestureRecognizer; // @synthesize interactivePopGestureRecognizer=_interactivePopGestureRecognizer;
@property(nonatomic, weak, nullable) id <UXNavigationControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isSubtoolbarHidden) BOOL subtoolbarHidden; // @synthesize subtoolbarHidden=_subtoolbarHidden;
@property(readonly, nonatomic) UXToolbar *subtoolbar; // @synthesize subtoolbar=_subtoolbar;
@property(nonatomic, getter=isToolbarHidden) BOOL toolbarHidden; // @synthesize toolbarHidden=_toolbarHidden;
@property(nonatomic, getter=isNavigationBarDetached) BOOL navigationBarDetached; // @synthesize navigationBarDetached=_navigationBarDetached;
@property(nonatomic, getter=isNavigationBarHidden) BOOL navigationBarHidden; // @synthesize navigationBarHidden=_navigationBarHidden;
- (void)goBackWithMenuItem:(NSMenuItem *)menuItem;
- (UXBarPosition)positionForBar:(id<UXBarPositioning>)bar;
- (id)contentRepresentingViewController;
- (void)_endObservingCurrentTopViewController;
- (void)_beginObservingCurrentTopViewController;
- (id)_backItemWithTitle:(NSString *)title target:(id)target action:(SEL)action;
- (void)_addBackBarItemFromNavigationItem:(UXNavigationItem *)fromNavigationItem toNavigationItem:(UXNavigationItem *)toNavigationItem;
- (void)_setupLayoutGuidesForViewController:(UXViewController *)viewController;
- (id)_customInteractionControllerForAnimationController:(id<UXViewControllerAnimatedTransitioning>)animationController transition:(NSUInteger)transition;
- (id)_customAnimationControllerForOperation:(UXNavigationControllerOperation)operation fromViewController:(UXViewController *)fromViewController toViewController:(UXViewController *)toViewController transition:(NSUInteger)transition;
- (id)_contextForTransitionOperation:(UXNavigationControllerOperation)operation fromViewController:(UXViewController *)fromViewController toViewController:(UXViewController *)toViewController transition:(NSUInteger)transition;
- (void)_handleInteractiveUpdateWithEvent:(NSEvent *)event;
- (void)_beginTransitionWithContext:(id)context operation:(UXNavigationControllerOperation)operation;
- (void)_removeConstraintsForContainedView:(UXView *)containedView;
- (void)_addConstraintsForContainedView:(UXView *)containedView leftInset:(CGFloat)leftInset;
- (void)_prepareViewController:(UXViewController *)viewController forAnimationInContext:(id)context completion:(id)completion;
- (void)_setViewControllers:(UXViewController *)viewController animated:(BOOL)animated;
- (id)_popToViewController:(UXViewController *)viewController transition:(NSUInteger)transition;
- (void)_pushViewController:(UXViewController *)viewController transition:(NSUInteger)transition;
- (id)_dequeueNavigationRequest;
- (id)_performOrEnqueueNavigationRequest:(_UXNavigationRequest *)navigationRequest;
- (BOOL)_hasNoNavigationRequests;
- (void)_removeAllNavigationRequests;
- (id)_checkinPopNavigationRequest:(_UXNavigationRequest *)navigationRequest;
- (void)_checkinPushNavigationRequest:(_UXNavigationRequest *)navigationRequest;
- (void)_checkinSetNavigationRequest:(_UXNavigationRequest *)navigationRequest;
- (id)_performNavigationRequest:(_UXNavigationRequest *)navigationRequest;
- (UXViewController *)visibleViewController;
- (UXViewController *)topViewController;
@property(readonly, nonatomic) UXViewController *currentTopViewController;
- (UXViewController *)popViewControllerAnimated:(BOOL)animated;
- (UXViewController *)popToRootViewControllerAnimated:(BOOL)animated;
- (UXViewController *)popToViewController:(UXViewController *)viewController animated:(BOOL)animated;
- (void)pushViewController:(UXViewController *)viewController animated:(BOOL)animated;
- (void)setViewControllers:(UXViewController *)viewController animated:(BOOL)animated;
- (void)detachNavigationBar;
- (void)__back:(id)arg1;
@property(readonly, nonatomic) NSGestureRecognizer *interactivePopEventTracker;
@property(readonly, nonatomic) UXToolbar *toolbar;
@property(readonly, nonatomic) UXToolbar *accessoryBar;
@property(readonly, nonatomic, getter=isAccessoryBarHidden) BOOL accessoryBarHidden;
@property(readonly, nonatomic) UXNavigationBar *navigationBar;
- (void)_updateToolbarAppearanceUsingTopViewController:(UXViewController *)topViewController animated:(BOOL)animated duration:(NSTimeInterval)duration;
- (void)_updateToolbarVisibilityUsingTopViewController:(UXViewController *)topViewController animated:(BOOL)animated duration:(NSTimeInterval)duration animateSubtree:(BOOL)animateSubtree;
- (void)_updateToolbarsPositionsUsingTopViewController:(UXViewController *)topViewController;
- (void)_setToolbarPosition:(UXBarPosition)toolbarPosition subtoolbarPosition:(UXBarPosition)subtoolbarPosition;
- (void)_updateToolbarsIfNeeded;
- (void)_invalidateToolbarsAppearance;
- (void)_invalidateToolbarsVisibility;
- (void)_invalidateToolbarsPositions;
- (void)_invalidateSubtoolbarItems;
- (void)_invalidateToolbarItems;
- (void)_setToolbarsNeedUpdate;
- (BOOL)_toolbarsNeedUpdate;
- (CGFloat)_leftContentInset;
- (void)_setLeadingContentInset:(CGFloat)contentInset forViewController:(UXViewController *)viewController;
- (CGFloat)_visibleToolbarOffset;
- (CGFloat)_hiddenToolbarOffset;
- (void)_setToolbarHidden:(BOOL)toolbarHidden subtoolbarHidden:(BOOL)subtoolbarHidden animated:(BOOL)animated duration:(NSTimeInterval)duration animateSubtree:(BOOL)animateSubtree;
- (BOOL)_toolbarNeedsVerticalOffsetUpdate;
- (void)setToolbarHidden:(BOOL)hidden animated:(BOOL)animated;
- (void)_setAccessoryBarHidden:(BOOL)hidden;
- (void)setNavigationBarHidden:(BOOL)hidden animated:(BOOL)animated;
@property(copy, nonatomic) NSArray<UXViewController *> *viewControllers;
- (id)transitionCoordinator;
- (id)currentTransitionCoordinator;
- (BOOL)_requiresWindowForTransitionPreparation;
- (NSEdgeInsets)_intrinsicLayoutInsetsForChildViewController:(UXViewController *)childViewController;
- (id)_verticalToolbarLayoutConstraint;
- (double)_toolbarVerticalOffset;
- (double)_navigationBarVerticalOffset;
- (void)_invalidateIntrinsicLayoutInsetsForViewController:(UXViewController *)viewController;
- (void)invalidateIntrinsicLayoutInsets;
- (NSEdgeInsets)intrinsicLayoutInsets;
- (id)preferredFirstResponder;
- (instancetype)initWithNavigationBarClass:(nullable Class)navigationBarClass toolbarClass:(nullable Class)toolbarClass NS_DESIGNATED_INITIALIZER;
- (instancetype)initWithNibName:(nullable NSString *)nibNameOrNil bundle:(nullable NSBundle *)nibBundleOrNil NS_DESIGNATED_INITIALIZER;
- (instancetype)initWithRootViewController:(UXViewController *)rootViewController NS_DESIGNATED_INITIALIZER;
- (void)testing_notifyTransitionAnimationDidComplete;
- (void)testing_installTransitionAnimationCompletionHandler:(id)handler;
@end

NS_HEADER_AUDIT_END(nullability, sendability)
