//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

@class NSArray, NSString, NSTextField, NSView, UXBarButtonItem;

@interface UXNavigationItem : NSObject <NSUserInterfaceItemIdentification>


@property(strong, nonatomic) NSView *condensedTitleView; // @synthesize condensedTitleView=_condensedTitleView;
@property(nonatomic) BOOL leftItemsSupplementBackButton; // @synthesize leftItemsSupplementBackButton=_leftItemsSupplementBackButton;
@property(nonatomic) BOOL hidesGlobalTrailingView; // @synthesize hidesGlobalTrailingView=_hidesGlobalTrailingView;
@property(nonatomic) BOOL hidesAlternateTitleView; // @synthesize hidesAlternateTitleView=_hidesAlternateTitleView;
@property(nonatomic) BOOL hidesBackButton; // @synthesize hidesBackButton=_hidesBackButton;
@property(copy, nonatomic) NSString *prompt; // @synthesize prompt=_prompt;
@property(strong, nonatomic) NSView *titleView; // @synthesize titleView=_titleView;
@property(strong, nonatomic) UXBarButtonItem *backBarButtonItem; // @synthesize backBarButtonItem=_backBarButtonItem;
@property(strong, nonatomic) NSString *title; // @synthesize title=_title;
@property(strong, nonatomic) UXBarButtonItem *rightBarButtonItem;
@property(strong, nonatomic) NSArray *rightBarButtonItems;
@property(strong, nonatomic) NSArray *leftBarButtonItems;
@property(strong, nonatomic) UXBarButtonItem *leftBarButtonItem;
@property (nonatomic) NSEdgeInsets layoutMargins;  
- (void)_updateInternalTitleView;
@property(readonly, nonatomic) NSTextField *internalTitleView;
@property(strong, nonatomic) NSArray *trailingBarButtonItems;
- (void)setTrailingBarButtonItems:(id)arg1 animated:(BOOL)arg2;
@property(strong, nonatomic) NSArray *leadingBarButtonItems;
- (void)setLeadingBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (void)setRightBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (void)setRightBarButtonItem:(id)arg1 animated:(BOOL)arg2;
- (void)setLeftBarButtonItems:(id)arg1 animated:(BOOL)arg2;
- (void)setLeftBarButtonItem:(id)arg1 animated:(BOOL)arg2;
- (id)initWithTitle:(id)arg1;

@end

