//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>
#import "UXViewController.h"

@class NSArray, NSString, UXPopover, UXViewController;
@protocol UXPopoverControllerDelegate;

NS_HEADER_AUDIT_BEGIN(nullability, sendability)

@interface UXPopoverController: UXViewController <NSPopoverDelegate>



@property(copy, nonatomic) NSArray *passthroughViews; // @synthesize passthroughViews=_passthroughViews;
@property(nonatomic, weak, nullable) id <UXPopoverControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dismissPopoverAnimated:(BOOL)arg1;
- (void)dismissPopover;
- (void)presentPopoverFromBarButtonItem:(id)arg1 permittedArrowDirections:(NSUInteger)arg2 animated:(BOOL)arg3;
- (void)presentPopoverFromRect:(CGRect)arg1 inView:(id)arg2 preferredEdge:(NSUInteger)arg3;
@property(retain, nonatomic) UXViewController *contentViewController;
@property(nonatomic) CGSize popoverContentSize;
- (void)setPopoverContentSize:(CGSize)arg1 animated:(BOOL)arg2;
@property(readonly, nonatomic, getter=isPopoverVisible) BOOL popoverVisible;
@property(nonatomic) NSInteger popoverBehavior;
- (BOOL)popoverShouldClose:(id)arg1;
- (void)popoverDidClose:(id)arg1;
- (void)popoverWillShow:(id)arg1;
@property(readonly, nonatomic) UXPopover *popover;
- (void)_updateContentSize;
- (void)dealloc;
- (id)initWithContentViewController:(id)arg1;
@end


NS_HEADER_AUDIT_END(nullability, sendability)
