//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

@protocol UXNavigationDestination;

@protocol UXSourceList <NSObject>
@property(readonly, nonatomic) CGFloat maxSourceListWidth;
@property(readonly, nonatomic) CGFloat minSourceListWidth;
@property(nonatomic, getter=isSourceListCollapsed) BOOL sourceListCollapsed;
- (void)selectNavigationDestination:(id <UXNavigationDestination>)arg1;
@end

