//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSLayoutConstraint;

@interface UXSubtoolbar
{
    NSLayoutConstraint *_heightConstraint;	// 128 = 0x80
}

+ (double)defaultHeight;

@property(readonly, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
- (void)setHeight:(double)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

