//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UXTableView;
@protocol UXTableViewDelegate;

@interface UXTableViewController
{
    id <UXTableViewDelegate> _tableViewDelegate;	// 16 = 0x10
}

+ (Class)collectionViewClass;

@property(readonly, nonatomic) id <UXTableViewDelegate> tableViewDelegate; // @synthesize tableViewDelegate=_tableViewDelegate;
- (void)_updateContentInsetFromLayoutGuides;
- (id)preferredFirstResponder;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)didUpdateLayoutGuides;
- (void)viewDidLayoutSubviews;
@property(readonly, nonatomic) UXTableView *tableView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;
- (id)initWithStyle:(NSInteger)arg1;

@end

