//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UXBarItem.h"

@class NSArray, NSSet, UXTabBarItemSegment;

@interface UXTabBarItem: UXBarItem
{
    NSSet *_possibleTitles;	// 8 = 0x8
    NSArray *_representedSegments;	// 16 = 0x10
}


@property(copy, nonatomic) NSArray<UXTabBarItemSegment *> *representedSegments; // @synthesize representedSegments=_representedSegments;
@property(copy, nonatomic) NSSet *possibleTitles; // @synthesize possibleTitles=_possibleTitles;
- (id)initWithTitle:(NSString *)title;

@end

