//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface UXTabBarItemSegment : NSObject
{
    BOOL _enabled;	// 8 = 0x8
    NSString *_title;	// 16 = 0x10
}


@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)description;
- (id)initWithTitle:(id)arg1;
- (id)init;

@end

