//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;
@protocol UXToolbarDelegate;

@interface UXToolbar
{
    id <UXToolbarDelegate> _delegate;	// 112 = 0x70
    NSArray *_items;	// 120 = 0x78
}


@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(nonatomic) __weak id <UXToolbarDelegate> delegate; // @synthesize delegate=_delegate;
- (NSInteger)barPosition;
- (void)_beginInteractiveTransitionForItems:(id)arg1;
- (void)_setItems:(id)arg1 animated:(BOOL)arg2 duration:(double)arg3;
- (void)setItems:(id)arg1 animated:(BOOL)arg2;
- (void)otherMouseDragged:(id)arg1;
- (void)rightMouseDragged:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)otherMouseUp:(id)arg1;
- (void)rightMouseUp:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)otherMouseDown:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseDown:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;

@end

