//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

@interface UXViewAnimationContext : NSObject
@property(nonatomic) CGFloat velocity; // @synthesize velocity=_velocity;
@property(nonatomic) CGFloat damping; // @synthesize damping=_damping;
@property(nonatomic) CGFloat stiffness; // @synthesize stiffness=_stiffness;
@property(nonatomic) CGFloat mass; // @synthesize mass=_mass;
- (void)generateSpringPropertiesForDuration:(CGFloat)duration damping:(CGFloat)damping velocity:(CGFloat)velocity;

@end

