//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled Feb 25 2024 00:55:05).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppKit/AppKit.h>

@class NSString, UXView, UXViewController;

@protocol UXViewControllerContextTransitioning <NSObject>
- (CGRect)finalFrameForViewController:(UXViewController *)arg1;
- (CGRect)initialFrameForViewController:(UXViewController *)arg1;
- (UXViewController *)viewControllerForKey:(NSString *)arg1;
- (void)completeTransition:(BOOL)arg1;
- (void)cancelInteractiveTransition;
- (void)finishInteractiveTransition;
- (void)updateInteractiveTransition:(double)arg1;
- (NSInteger)presentationStyle;
- (BOOL)transitionWasCancelled;
- (BOOL)isInteractive;
- (BOOL)isAnimated;
- (UXView *)containerView;

@optional
@property(copy, nonatomic) id arbitraryTransitionCompletionHandler;
@end

